# Oe1 Family 2: A_4 (tetrahedral) GM-ansatz for <3,3,3>.
# A_4's 3-dim irrep = restriction of S_4's standard rep to A_4 (RATIONAL char
# field Q). A_4 < SO(3) so Lambda^2(rho) ~ rho (3-dim), NO sign-twisted rho' --
# antisymmetric structure differs from S_4. A_4 order 12 has SMALL orbits, so
# single- AND multi-orbit configs fit rank<=22. We:
#  1. confirm rho irreducible, char field, antisym structure;
#  2. enumerate subgroup orbits (12/|H|), fixed dims;
#  3. coverage + Groebner over Q for single orbits and the cheapest multi-orbit
#     configs <= rank 22;
#  4. Os1-style pos/neg control to validate the builder.
# SOLUTION-FOUND with rank<23 => STOP (beats Laderman).

import json, itertools
K = QQ   # A_4 standard rep is rational
def Mt(rows): return matrix(K,rows)
# A_4 = <(123),(12)(34)> in the 3-dim standard rep (signed-permutation basis from
# GM, restricted to A_4). Use the SAME generators as the Go S_4 code, A_4 subset.
# S_4 standard rep generators (GM): build S_4 then take the A_4 subgroup.
rho_12=Mt([[0,1,0],[1,0,0],[0,0,1]])
rho_23=Mt([[1,0,0],[0,0,1],[0,1,0]])
rho_34=Mt([[0,-1,0],[-1,0,0],[0,0,1]])
sigma=Mt([[0,0,1],[1,0,0],[0,1,0]])  # rho((123)), order 3, in A_4
def matkey(M): return tuple(M.list())
I3=identity_matrix(K,3)
# build S_4
elems={matkey(I3):I3}; frontier=[I3]
for _ in range(200):
    if not frontier: break
    new=[]
    for e in frontier:
        for g in [rho_12,rho_23,rho_34]:
            ne=g*e; k=matkey(ne)
            if k not in elems: elems[k]=ne; new.append(ne)
    frontier=new
S4=list(elems.values()); assert len(S4)==24
# A_4 = subgroup generated by sigma=(123) and rho((12)(34)).
r1234 = rho_12*rho_34   # (12)(34)
A4d={matkey(I3):I3}; fr=[I3]
for _ in range(200):
    if not fr: break
    new=[]
    for e in fr:
        for g in [sigma, r1234]:
            ne=g*e; k=matkey(ne)
            if k not in A4d: A4d[k]=ne; new.append(ne)
    fr=new
ELEM=list(A4d.values())
print(f"A_4 order: {len(ELEM)} (expect 12)")
from collections import Counter
def matorder(M):
    P=M; o=1
    while P!=I3 and o<50: P=P*M; o+=1
    return o
print("order dist:", dict(Counter(matorder(M) for M in ELEM)))

def conjOp(g):
    gi=g.inverse(); C=matrix(K,9,9)
    for i in range(3):
        for j in range(3):
            E=matrix(K,3,3); E[i,j]=1; img=g*E*gi; col=i*3+j
            for a in range(3):
                for b in range(3): C[a*3+b,col]=img[a,b]
    return C
# irreducibility: End dim
rows=[]; I9=identity_matrix(K,9)
for g in ELEM: rows.append(conjOp(g)-I9)
big=block_matrix(K,[[m] for m in rows])
print(f"dim End_A4(rho) = {9-big.rank()} (1 => irreducible)")

def fixedBasis_sub(H):
    rows=[]; I9=identity_matrix(K,9)
    for h in H: rows.append(conjOp(h)-I9)
    big=block_matrix(K,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(K,3,3,[v[k] for k in range(9)]) for v in ker]
def subgroup(gens):
    H={matkey(I3):I3}; fr=[I3]
    while fr:
        nn=[]
        for e in fr:
            for g in gens:
                ne=g*e; k=matkey(ne)
                if k not in H: H[k]=ne; nn.append(ne)
        fr=nn
    return list(H.values())

Eb=[]
for i in range(3):
    for j in range(3):
        E=matrix(K,3,3); E[i,j]=1; Eb.append(E)
def residual(ai,bi,ci):
    A,B,C=Eb[ai],Eb[bi],Eb[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()
Rsupport=set((a,b,c) for a in range(9) for b in range(9) for c in range(9) if residual(a,b,c)!=0)
print(f"residual support |R|={len(Rsupport)}")

# enumerate cyclic + key subgroups, orbit sizes
def cyclic(g):
    H=[I3]; P=g
    while P!=I3: H.append(P); P=P*g
    return H
# distinct subgroups by order: Z_3 (orbit4), Z_2 (orbit6), V_4 (orbit3)
subs={}
for g in ELEM:
    H=cyclic(g)
    subs.setdefault(len(H),H)
# V_4 = the three double-transpositions + id
V4 = subgroup([r1234, rho_12*rho_23*rho_12*rho_23])  # build Klein 4 inside A_4
# robust V_4: all elements of order dividing 2
V4 = [M for M in ELEM if matorder(M)<=2]
print(f"\nsubgroup orbit table:")
cands=[]
for o,H in sorted(subs.items()):
    fb=fixedBasis_sub(H); orbit=12//o
    print(f"  cyclic |H|={o} orbit={orbit} rank={1+orbit} fixed_dim={len(fb)}")
    cands.append((f"Z_{o}", H, orbit, len(fb)))
fbV=fixedBasis_sub(V4)
print(f"  V_4 |H|={len(V4)} orbit={12//len(V4)} rank={1+12//len(V4)} fixed_dim={len(fbV)}")
cands.append(("V_4", V4, 12//len(V4), len(fbV)))

# Build symbolic orbit-sum for a single orbit (given fixed basis), reach + system.
def orbit_system(fb, var_offset, allvars_ring=None):
    pass  # replaced by inline build below

def build_single(name, H, fb):
    d=len(fb); orbit=12//len(H)
    if d==0:
        print(f"  [{name}] fixed dim 0, skip"); return
    R=PolynomialRing(K, d, [f"x{i}" for i in range(d)]); xs=R.gens()
    m1=matrix(R,3,3)
    for p in range(d): m1 += xs[p]*fb[p].change_ring(R)
    s=sigma.change_ring(R); m2=s*m1*s.inverse(); s2=(sigma*sigma).change_ring(R); m3=s2*m1*s2.inverse()
    def frobR(Xc,Ms):
        acc=R(0)
        for i in range(3):
            for j in range(3):
                if Xc[i,j]!=0: acc += Xc[i,j]*Ms[i,j]
        return acc
    gm={}
    for gi,gg in enumerate(ELEM):
        gR=gg.change_ring(R); gmi=gR.inverse()
        gm[(gi,0)]=gR*m1*gmi; gm[(gi,1)]=gR*m2*gmi; gm[(gi,2)]=gR*m3*gmi
    reach=set(); polys=[]
    for ai in range(9):
        for bi in range(9):
            for ci in range(9):
                orb=R(0)
                for gi in range(len(ELEM)):
                    la=frobR(Eb[ai],gm[(gi,0)])
                    if la==0: continue
                    lb=frobR(Eb[bi],gm[(gi,1)])
                    if lb==0: continue
                    lc=frobR(Eb[ci],gm[(gi,2)])
                    if lc==0: continue
                    orb += la*lb*lc
                if orb!=0: reach.add((ai,bi,ci))
                P=orb+residual(ai,bi,ci)
                if P!=0: polys.append(P)
    covered=len(reach & Rsupport); missed=Rsupport-reach
    I=R.ideal(polys); unit=(R.one() in I)
    verdict="INFEASIBLE (unit ideal)" if unit else f"SOLUTION-FOUND dim {I.dimension()} *** STOP rank {1+orbit} ***"
    cov = f"covers {covered}/{len(Rsupport)}" + (f", MISSES {len(missed)} (const gen)" if missed else ", covers all")
    print(f"  [{name}] orbit {orbit} rank {1+orbit} dim {d}: {cov}; Groebner: {verdict}")
    return unit

print("\nSINGLE-ORBIT A_4 verdicts:")
for name,H,orbit,fdim in cands:
    fb=fixedBasis_sub(H)
    build_single(name, H, fb)
