# Or2 foundations: verify H-fixed subspace dims + effective Fourier constraints
# Standard 3-dim irrep of S_4 (signed permutation / tetrahedron basis from GM 1612.01527 sec 4.1)
import itertools, json

K.<r3> = QuadraticField(3)   # Q(sqrt 3); needed for the box irrep basis

# Build rho on generators as GM specifies (monomial / signed-permutation, det=parity)
def M(rows): return matrix(K, rows)

rho_12 = M([[0,1,0],[1,0,0],[0,0,1]])
rho_23 = M([[1,0,0],[0,0,1],[0,1,0]])
rho_34 = M([[0,-1,0],[-1,0,0],[0,0,1]])
sigma  = M([[0,0,1],[1,0,0],[0,1,0]])   # rho((123))

# Generate the whole group S_4 as a dict perm-tuple -> matrix.
# Use generators (12),(23),(34) which generate S_4.
gens = {(1,0,2,3): rho_12, (0,2,1,3): rho_23, (0,1,3,2): rho_34}
# represent permutations as tuples of images of (0,1,2,3)
def compose(p,q):  # apply q then p:  (p*q)(i)=p(q(i))
    return tuple(p[q[i]] for i in range(4))
ident = (0,1,2,3)
elems = {ident: identity_matrix(K,3)}
frontier=[ident]
genperms = list(gens.keys())
while frontier:
    new=[]
    for e in frontier:
        for gp in genperms:
            ne = compose(gp, e)
            if ne not in elems:
                elems[ne] = gens[gp]*elems[e]
                new.append(ne)
    frontier=new
print("group order:", len(elems))

# sanity: check it's a rep (multiplicativity) on a few pairs
import random
ok=True
ps=list(elems.keys())
for _ in range(50):
    a=random.choice(ps); b=random.choice(ps)
    if elems[compose(a,b)] != elems[a]*elems[b]:
        ok=False
print("rep multiplicativity ok:", ok)

# H-fixed subspace of M_3 under conjugation rho(h) X rho(h)^{-1} = X for h in H.
# dim = number of trivial subreps of rho⊗rho* restricted to H.
def fixed_dim(Hgens_perms):
    # build subgroup
    H={ident}
    fr=[ident]
    while fr:
        nn=[]
        for e in fr:
            for g in Hgens_perms:
                ne=compose(g,e)
                if ne not in H:
                    H.add(ne); nn.append(ne)
        fr=nn
    # For each h in H, conjugation acts on vec(X) in C^9 by rho(h) ⊗ rho(h)^{-T}
    # Fixed space = intersection of ker( Kron - I ).
    rows=[]
    for h in H:
        A=elems[h]
        Ainv=A.inverse()
        # vec(rho(h) X rho(h)^{-1}) = (rho(h)^{-T} ⊗ rho(h)) vec(X) ... use kron
        Kr = Ainv.transpose().tensor_product(A)   # acts on column-stacked vec
        rows.append(Kr - identity_matrix(K,9))
    big = block_matrix([[m] for m in rows])
    return 9 - big.rank(), len(H)

# Subgroup generators (as transposition/perm tuples in our 0-indexed convention)
# S_3 = <(23),(34)> fixing point 1 (0-indexed: fixes index 0)
S3   = [(0,2,1,3),(0,1,3,2)]
# K_4 = <(12)(34),(13)(24)>
t1234=(1,0,3,2); t1324=(2,3,0,1)
K4   = [t1234, t1324]
# Z_3 = <(123)>
Z3   = [(1,2,0,3)]
# Z_2 generated by a single transposition (12)
Z2t  = [(1,0,2,3)]
# Z_2 generated by double transposition (12)(34)
Z2dt = [t1234]
# Z_4 = <(1234)>
Z4   = [(1,2,3,0)]
# D_4 (order 8) = <(1234),(13)>
D4   = [(1,2,3,0),(2,1,0,3)]
# A_4 (order 12) = <(123),(12)(34)>
A4   = [(1,2,0,3), t1234]

for name,g in [("S_3",S3),("K_4",K4),("Z_3",Z3),("Z_2(transp)",Z2t),
               ("Z_2(dbl)",Z2dt),("Z_4",Z4),("D_4",D4),("A_4",A4)]:
    d,h=fixed_dim(g)
    print(f"H={name:12s} |H|={h:2d} orbit={24//h:2d}  fixed_dim(M3)={d}")
