

# This file was *autogenerated* from the file /workspace/Or2-S_3_Z_2t.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_24 = Integer(24); _sage_const_648 = Integer(648); _sage_const_192 = Integer(192); _sage_const_288 = Integer(288); _sage_const_144 = Integer(144); _sage_const_2 = Integer(2); _sage_const_12 = Integer(12); _sage_const_18 = Integer(18); _sage_const_6 = Integer(6); _sage_const_96 = Integer(96); _sage_const_64 = Integer(64); _sage_const_32 = Integer(32); _sage_const_16 = Integer(16); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_48 = Integer(48); _sage_const_0 = Integer(0)
import json
K = QuadraticField(_sage_const_3 , names=('sqrt3',)); (sqrt3,) = K._first_ngens(1)
R = PolynomialRing(K, _sage_const_7 , "x0,x1,x2,x3,x4,x5,x6")
x0,x1,x2,x3,x4,x5,x6 = R.gens()
gens = [
  (_sage_const_24 ) + (_sage_const_648 )*x1*x1*x1 + (_sage_const_192 )*x3*x3*x3 + (_sage_const_288 )*x3*x3*x6 + (_sage_const_144 )*x3*x6*x6 + (_sage_const_24 )*x6*x6*x6,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x3*x3*x3 + (_sage_const_18 )*x3*x3*x6 + (-_sage_const_6 )*x6*x6*x6,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x3*x3*x3 + (_sage_const_18 )*x3*x3*x6 + (-_sage_const_6 )*x6*x6*x6,
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x3*x3*x3 + (_sage_const_18 )*x3*x3*x6 + (-_sage_const_6 )*x6*x6*x6,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x3*x3*x3 + (_sage_const_18 )*x3*x3*x6 + (-_sage_const_6 )*x6*x6*x6,
  (-_sage_const_3 /_sage_const_4 ) + (-_sage_const_6 )*x3*x3*x3 + (_sage_const_18 )*x3*x3*x6 + (-_sage_const_18 )*x3*x6*x6 + (_sage_const_6 )*x6*x6*x6,
  (_sage_const_3 /_sage_const_4 ) + (_sage_const_6 )*x3*x3*x3 + (-_sage_const_18 )*x3*x3*x6 + (_sage_const_18 )*x3*x6*x6 + (-_sage_const_6 )*x6*x6*x6,
  (_sage_const_1 ) + (_sage_const_16 )*x2*x3*x4 + (_sage_const_16 )*x2*x3*x5 + (-_sage_const_16 )*x2*x4*x6 + (-_sage_const_16 )*x2*x5*x6 + (-_sage_const_8 )*x3*x4*x4 + (-_sage_const_16 )*x3*x4*x5 + (-_sage_const_8 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 /_sage_const_2 ) + (-_sage_const_8 )*x2*x3*x4 + (-_sage_const_8 )*x2*x3*x5 + (_sage_const_8 )*x2*x4*x6 + (_sage_const_8 )*x2*x5*x6 + (_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (_sage_const_4 )*x3*x5*x5 + (-_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (-_sage_const_4 )*x5*x5*x6,
  (-_sage_const_3 /_sage_const_2 ) + (_sage_const_12 )*x2*x3*x4 + (-_sage_const_12 )*x2*x3*x5 + (-_sage_const_12 )*x2*x4*x6 + (_sage_const_12 )*x2*x5*x6,
  (-_sage_const_1 /_sage_const_2 ) + (-_sage_const_8 )*x2*x3*x4 + (-_sage_const_8 )*x2*x3*x5 + (_sage_const_8 )*x2*x4*x6 + (_sage_const_8 )*x2*x5*x6 + (_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (_sage_const_4 )*x3*x5*x5 + (-_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (-_sage_const_4 )*x5*x5*x6,
  (_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x2*x3*x4 + (_sage_const_12 )*x2*x3*x5 + (_sage_const_12 )*x2*x4*x6 + (-_sage_const_12 )*x2*x5*x6,
  (-_sage_const_1 ) + (_sage_const_8 )*x3*x4*x4 + (-_sage_const_16 )*x3*x4*x5 + (_sage_const_8 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (_sage_const_3 /_sage_const_2 ) + (_sage_const_12 )*x2*x3*x4 + (-_sage_const_12 )*x2*x3*x5 + (-_sage_const_12 )*x2*x4*x6 + (_sage_const_12 )*x2*x5*x6,
  (_sage_const_1 /_sage_const_2 ) + (-_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (-_sage_const_4 )*x3*x5*x5 + (_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (_sage_const_4 )*x5*x5*x6,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x2*x3*x4 + (_sage_const_12 )*x2*x3*x5 + (_sage_const_12 )*x2*x4*x6 + (-_sage_const_12 )*x2*x5*x6,
  (_sage_const_1 /_sage_const_2 ) + (-_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (-_sage_const_4 )*x3*x5*x5 + (_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (_sage_const_4 )*x5*x5*x6,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x3*x3*x3 + (_sage_const_18 )*x3*x3*x6 + (-_sage_const_6 )*x6*x6*x6,
  (_sage_const_3 /_sage_const_4 ) + (_sage_const_6 )*x3*x3*x3 + (-_sage_const_18 )*x3*x3*x6 + (_sage_const_18 )*x3*x6*x6 + (-_sage_const_6 )*x6*x6*x6,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x3*x3*x3 + (_sage_const_18 )*x3*x3*x6 + (-_sage_const_6 )*x6*x6*x6,
  (_sage_const_3 /_sage_const_4 ) + (_sage_const_6 )*x3*x3*x3 + (-_sage_const_18 )*x3*x3*x6 + (_sage_const_18 )*x3*x6*x6 + (-_sage_const_6 )*x6*x6*x6,
  ((_sage_const_1 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((-_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6 + ((-_sage_const_4 )*sqrt3)*x3*x4*x4 + ((-_sage_const_8 )*sqrt3)*x3*x4*x5 + ((-_sage_const_4 )*sqrt3)*x3*x5*x5 + ((_sage_const_4 )*sqrt3)*x4*x4*x6 + ((_sage_const_8 )*sqrt3)*x4*x5*x6 + ((_sage_const_4 )*sqrt3)*x5*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((-_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((_sage_const_8 )*sqrt3)*x2*x5*x6 + ((_sage_const_4 )*sqrt3)*x3*x4*x4 + ((_sage_const_8 )*sqrt3)*x3*x4*x5 + ((_sage_const_4 )*sqrt3)*x3*x5*x5 + ((-_sage_const_4 )*sqrt3)*x4*x4*x6 + ((-_sage_const_8 )*sqrt3)*x4*x5*x6 + ((-_sage_const_4 )*sqrt3)*x5*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  ((-_sage_const_1 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x3*x4*x4 + ((-_sage_const_8 )*sqrt3)*x3*x4*x5 + ((_sage_const_4 )*sqrt3)*x3*x5*x5 + ((-_sage_const_4 )*sqrt3)*x4*x4*x6 + ((_sage_const_8 )*sqrt3)*x4*x5*x6 + ((-_sage_const_4 )*sqrt3)*x5*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((-_sage_const_4 )*sqrt3)*x3*x4*x4 + ((_sage_const_8 )*sqrt3)*x3*x4*x5 + ((-_sage_const_4 )*sqrt3)*x3*x5*x5 + ((_sage_const_4 )*sqrt3)*x4*x4*x6 + ((-_sage_const_8 )*sqrt3)*x4*x5*x6 + ((_sage_const_4 )*sqrt3)*x5*x5*x6,
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (_sage_const_1 ) + (_sage_const_16 )*x2*x3*x4 + (_sage_const_16 )*x2*x3*x5 + (-_sage_const_16 )*x2*x4*x6 + (-_sage_const_16 )*x2*x5*x6 + (-_sage_const_8 )*x3*x4*x4 + (-_sage_const_16 )*x3*x4*x5 + (-_sage_const_8 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  ((-_sage_const_1 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6,
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (_sage_const_1 ) + (_sage_const_16 )*x2*x3*x4 + (_sage_const_16 )*x2*x3*x5 + (-_sage_const_16 )*x2*x4*x6 + (-_sage_const_16 )*x2*x5*x6 + (-_sage_const_8 )*x3*x4*x4 + (-_sage_const_16 )*x3*x4*x5 + (-_sage_const_8 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 ) + (_sage_const_64 )*x0*x0*x0 + (_sage_const_32 )*x2*x2*x2 + (_sage_const_24 )*x2*x4*x4 + (_sage_const_48 )*x2*x4*x5 + (_sage_const_24 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (_sage_const_24 )*x4*x4*x5 + (_sage_const_24 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (_sage_const_64 )*x0*x0*x0 + (_sage_const_32 )*x2*x2*x2 + (_sage_const_24 )*x2*x4*x4 + (_sage_const_48 )*x2*x4*x5 + (_sage_const_24 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (_sage_const_24 )*x4*x4*x5 + (_sage_const_24 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  ((_sage_const_1 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 /_sage_const_2 ) + (-_sage_const_8 )*x2*x3*x4 + (-_sage_const_8 )*x2*x3*x5 + (_sage_const_8 )*x2*x4*x6 + (_sage_const_8 )*x2*x5*x6 + (_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (_sage_const_4 )*x3*x5*x5 + (-_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (-_sage_const_4 )*x5*x5*x6,
  (_sage_const_3 /_sage_const_2 ) + (_sage_const_12 )*x2*x3*x4 + (-_sage_const_12 )*x2*x3*x5 + (-_sage_const_12 )*x2*x4*x6 + (_sage_const_12 )*x2*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((-_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6 + ((-_sage_const_4 )*sqrt3)*x3*x4*x4 + ((-_sage_const_8 )*sqrt3)*x3*x4*x5 + ((-_sage_const_4 )*sqrt3)*x3*x5*x5 + ((_sage_const_4 )*sqrt3)*x4*x4*x6 + ((_sage_const_8 )*sqrt3)*x4*x5*x6 + ((_sage_const_4 )*sqrt3)*x5*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  (-_sage_const_1 ) + (_sage_const_64 )*x0*x0*x0 + (_sage_const_32 )*x2*x2*x2 + (_sage_const_24 )*x2*x4*x4 + (_sage_const_48 )*x2*x4*x5 + (_sage_const_24 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (_sage_const_24 )*x4*x4*x5 + (_sage_const_24 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 /_sage_const_2 ) + (-_sage_const_8 )*x2*x3*x4 + (-_sage_const_8 )*x2*x3*x5 + (_sage_const_8 )*x2*x4*x6 + (_sage_const_8 )*x2*x5*x6 + (_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (_sage_const_4 )*x3*x5*x5 + (-_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (-_sage_const_4 )*x5*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((-_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6 + ((-_sage_const_4 )*sqrt3)*x3*x4*x4 + ((-_sage_const_8 )*sqrt3)*x3*x4*x5 + ((-_sage_const_4 )*sqrt3)*x3*x5*x5 + ((_sage_const_4 )*sqrt3)*x4*x4*x6 + ((_sage_const_8 )*sqrt3)*x4*x5*x6 + ((_sage_const_4 )*sqrt3)*x5*x5*x6,
  (-_sage_const_1 ) + (_sage_const_64 )*x0*x0*x0 + (_sage_const_32 )*x2*x2*x2 + (_sage_const_24 )*x2*x4*x4 + (_sage_const_48 )*x2*x4*x5 + (_sage_const_24 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (_sage_const_24 )*x4*x4*x5 + (_sage_const_24 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_1 ),
  (_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_3 /_sage_const_2 ) + (_sage_const_12 )*x2*x3*x4 + (-_sage_const_12 )*x2*x3*x5 + (-_sage_const_12 )*x2*x4*x6 + (_sage_const_12 )*x2*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 /_sage_const_2 ) + (-_sage_const_8 )*x2*x3*x4 + (-_sage_const_8 )*x2*x3*x5 + (_sage_const_8 )*x2*x4*x6 + (_sage_const_8 )*x2*x5*x6 + (_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (_sage_const_4 )*x3*x5*x5 + (-_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (-_sage_const_4 )*x5*x5*x6,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x2*x3*x4 + (_sage_const_12 )*x2*x3*x5 + (_sage_const_12 )*x2*x4*x6 + (-_sage_const_12 )*x2*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((-_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((_sage_const_8 )*sqrt3)*x2*x5*x6 + ((_sage_const_4 )*sqrt3)*x3*x4*x4 + ((_sage_const_8 )*sqrt3)*x3*x4*x5 + ((_sage_const_4 )*sqrt3)*x3*x5*x5 + ((-_sage_const_4 )*sqrt3)*x4*x4*x6 + ((-_sage_const_8 )*sqrt3)*x4*x5*x6 + ((-_sage_const_4 )*sqrt3)*x5*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  (-_sage_const_1 ) + (_sage_const_64 )*x0*x0*x0 + (_sage_const_32 )*x2*x2*x2 + (_sage_const_24 )*x2*x4*x4 + (_sage_const_48 )*x2*x4*x5 + (_sage_const_24 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (_sage_const_24 )*x4*x4*x5 + (_sage_const_24 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (_sage_const_64 )*x0*x0*x0 + (_sage_const_32 )*x2*x2*x2 + (_sage_const_24 )*x2*x4*x4 + (_sage_const_48 )*x2*x4*x5 + (_sage_const_24 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (_sage_const_24 )*x4*x4*x5 + (_sage_const_24 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (-_sage_const_2 ) + (-_sage_const_96 )*x0*x0*x1 + (_sage_const_64 )*x2*x3*x4 + (_sage_const_64 )*x2*x3*x5 + (_sage_const_32 )*x2*x4*x6 + (_sage_const_32 )*x2*x5*x6 + (_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (_sage_const_16 )*x3*x5*x5 + (_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 /_sage_const_2 ) + (-_sage_const_8 )*x2*x3*x4 + (-_sage_const_8 )*x2*x3*x5 + (_sage_const_8 )*x2*x4*x6 + (_sage_const_8 )*x2*x5*x6 + (_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (_sage_const_4 )*x3*x5*x5 + (-_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (-_sage_const_4 )*x5*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((-_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((_sage_const_8 )*sqrt3)*x2*x5*x6 + ((_sage_const_4 )*sqrt3)*x3*x4*x4 + ((_sage_const_8 )*sqrt3)*x3*x4*x5 + ((_sage_const_4 )*sqrt3)*x3*x5*x5 + ((-_sage_const_4 )*sqrt3)*x4*x4*x6 + ((-_sage_const_8 )*sqrt3)*x4*x5*x6 + ((-_sage_const_4 )*sqrt3)*x5*x5*x6,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x2*x3*x4 + (_sage_const_12 )*x2*x3*x5 + (_sage_const_12 )*x2*x4*x6 + (-_sage_const_12 )*x2*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 ) + (_sage_const_8 )*x3*x4*x4 + (-_sage_const_16 )*x3*x4*x5 + (_sage_const_8 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  ((_sage_const_1 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6,
  ((-_sage_const_1 )*sqrt3) + ((-_sage_const_8 )*sqrt3)*x2*x3*x4 + ((_sage_const_8 )*sqrt3)*x2*x3*x5 + ((_sage_const_8 )*sqrt3)*x2*x4*x6 + ((-_sage_const_8 )*sqrt3)*x2*x5*x6,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 ) + (_sage_const_8 )*x3*x4*x4 + (-_sage_const_16 )*x3*x4*x5 + (_sage_const_8 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (-_sage_const_3 /_sage_const_2 ) + (_sage_const_12 )*x2*x3*x4 + (-_sage_const_12 )*x2*x3*x5 + (-_sage_const_12 )*x2*x4*x6 + (_sage_const_12 )*x2*x5*x6,
  (_sage_const_1 /_sage_const_2 ) + (-_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (-_sage_const_4 )*x3*x5*x5 + (_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (_sage_const_4 )*x5*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x3*x4*x4 + ((-_sage_const_8 )*sqrt3)*x3*x4*x5 + ((_sage_const_4 )*sqrt3)*x3*x5*x5 + ((-_sage_const_4 )*sqrt3)*x4*x4*x6 + ((_sage_const_8 )*sqrt3)*x4*x5*x6 + ((-_sage_const_4 )*sqrt3)*x5*x5*x6,
  (_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_3 /_sage_const_2 ) + (_sage_const_12 )*x2*x3*x4 + (-_sage_const_12 )*x2*x3*x5 + (-_sage_const_12 )*x2*x4*x6 + (_sage_const_12 )*x2*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (_sage_const_1 /_sage_const_2 ) + (-_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (-_sage_const_4 )*x3*x5*x5 + (_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (_sage_const_4 )*x5*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x3*x4*x4 + ((-_sage_const_8 )*sqrt3)*x3*x4*x5 + ((_sage_const_4 )*sqrt3)*x3*x5*x5 + ((-_sage_const_4 )*sqrt3)*x4*x4*x6 + ((_sage_const_8 )*sqrt3)*x4*x5*x6 + ((-_sage_const_4 )*sqrt3)*x5*x5*x6,
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_1 ),
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x2*x3*x4 + (_sage_const_12 )*x2*x3*x5 + (_sage_const_12 )*x2*x4*x6 + (-_sage_const_12 )*x2*x5*x6,
  (_sage_const_1 /_sage_const_2 ) + (-_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (-_sage_const_4 )*x3*x5*x5 + (_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (_sage_const_4 )*x5*x5*x6,
  ((-_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((-_sage_const_4 )*sqrt3)*x3*x4*x4 + ((_sage_const_8 )*sqrt3)*x3*x4*x5 + ((-_sage_const_4 )*sqrt3)*x3*x5*x5 + ((_sage_const_4 )*sqrt3)*x4*x4*x6 + ((-_sage_const_8 )*sqrt3)*x4*x5*x6 + ((_sage_const_4 )*sqrt3)*x5*x5*x6,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_3 /_sage_const_2 ) + (-_sage_const_12 )*x2*x3*x4 + (_sage_const_12 )*x2*x3*x5 + (_sage_const_12 )*x2*x4*x6 + (-_sage_const_12 )*x2*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((_sage_const_4 )*sqrt3)*x2*x3*x4 + ((-_sage_const_4 )*sqrt3)*x2*x3*x5 + ((-_sage_const_4 )*sqrt3)*x2*x4*x6 + ((_sage_const_4 )*sqrt3)*x2*x5*x6,
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (-_sage_const_1 ),
  (-_sage_const_1 ) + (-_sage_const_8 )*x2*x4*x4 + (_sage_const_16 )*x2*x4*x5 + (-_sage_const_8 )*x2*x5*x5 + (_sage_const_8 )*x4*x4*x4 + (-_sage_const_8 )*x4*x4*x5 + (-_sage_const_8 )*x4*x5*x5 + (_sage_const_8 )*x5*x5*x5,
  (_sage_const_1 ),
  (_sage_const_2 ) + (-_sage_const_16 )*x3*x4*x4 + (_sage_const_32 )*x3*x4*x5 + (-_sage_const_16 )*x3*x5*x5 + (-_sage_const_8 )*x4*x4*x6 + (_sage_const_16 )*x4*x5*x6 + (-_sage_const_8 )*x5*x5*x6,
  (_sage_const_1 /_sage_const_2 ) + (-_sage_const_4 )*x3*x4*x4 + (_sage_const_8 )*x3*x4*x5 + (-_sage_const_4 )*x3*x5*x5 + (_sage_const_4 )*x4*x4*x6 + (-_sage_const_8 )*x4*x5*x6 + (_sage_const_4 )*x5*x5*x6,
  ((_sage_const_1 /_sage_const_2 )*sqrt3) + ((-_sage_const_4 )*sqrt3)*x3*x4*x4 + ((_sage_const_8 )*sqrt3)*x3*x4*x5 + ((-_sage_const_4 )*sqrt3)*x3*x5*x5 + ((_sage_const_4 )*sqrt3)*x4*x4*x6 + ((-_sage_const_8 )*sqrt3)*x4*x5*x6 + ((_sage_const_4 )*sqrt3)*x5*x5*x6,
]

if len(gens) == _sage_const_0 :
    print(json.dumps({"verdict":"DEGENERATE","reason":"no constraints"}))
else:
    I = R.ideal(gens)
    try:
        gb = I.groebner_basis()
    except Exception as e:
        print(json.dumps({"verdict":"ERROR","reason":str(e)}))
    else:
        gbs = [str(g) for g in gb]
        is_unit = (R.one() in I) if hasattr(R,'one') else any(str(g)=="1" for g in gb)
        if is_unit:
            print(json.dumps({"verdict":"INFEASIBLE","groebner":gbs}))
        else:
            try:
                d = I.dimension()
            except Exception as e:
                d = None
            out = {"verdict":"SOLUTION-FOUND","dimension":(int(d) if d is not None else None),"groebner":gbs}
            if d == _sage_const_0 :
                try:
                    V = I.variety(ring=QQbar)
                    out["num_points"] = len(V)
                    pts = []
                    for sol in V[:_sage_const_8 ]:
                        pts.append({str(k): str(v) for k,v in sol.items()})
                    out["points"] = pts
                except Exception as e:
                    out["variety_error"] = str(e)
            print(json.dumps(out))

