

# This file was *autogenerated* from the file /workspace/Bm-m2-calibrate.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6)# Bm5 CALIBRATION on M_2 (gold test).
#
# CHL 1911.07981 section "Mtwo" (L916-934) fully specifies the answer:
#   U=V=W=C^2. U*(x)sl(V)(x)W has dim 2*3*2 = 12.
#   Exactly 3 B-fixed 2-planes E_110' (CHL L719-723):
#     P1 = <x^2_1 (x) y^2_1, x^1_1 (x) y^2_1>            -> (210) rank 20, FAIL
#     P2 = <x^2_1 (x) y^2_1, x^2_1 (x) y^2_2>            -> (120) rank 20, FAIL
#     P3 = <x^2_1 (x) y^2_1, x^2_1 (x) y^1_1 - x^2_2 (x) y^2_1>  -> (210) rank 19, FAIL
#   All fail at r=6 => R_(M_2) > 6.
#
# This script reproduces those three ranks using the kashbari pipeline
# (matrix_11_to_21 / matrix_rank_le_eqs) ported into Bm4 infra, to validate
# the (210)/(120) test machinery BEFORE trusting the M_3 count.
#
# Basis conventions (CHL): x^i_j = u^i (x) v_j in A = U* (x) V, index (i-1)*n+(j-1).
#   y^i_j = v^i (x) w_j in B = V* (x) W, index (i-1)*n+(j-1).
# Self-contained (no load()).

from itertools import product as cart_product, combinations

# ============ generic infra (works for any n) ============

def cartan_matrix_sln(n):
    C = matrix(QQ, n - _sage_const_1 , n - _sage_const_1 )
    for i in range(n - _sage_const_1 ):
        C[i, i] = _sage_const_2 
    for i in range(n - _sage_const_2 ):
        C[i + _sage_const_1 , i] = -_sage_const_1 
        C[i, i + _sage_const_1 ] = -_sage_const_1 
    return C

def _restrict_map(m, C, B):
    I = C.pivot_rows()
    return C[I, :].solve_right((m * B)[I, :])

def module_product(reps_a, reps_b):
    return [
        [xa.tensor_product(identity_matrix(QQ, yb.dimensions()[_sage_const_0 ], sparse=True)) +
         identity_matrix(QQ, xa.dimensions()[_sage_const_0 ], sparse=True).tensor_product(yb)
         for xa, yb in zip(sa, sb)]
        for sa, sb in zip(reps_a, reps_b)
    ]

def module_dual(reps):
    return [[-x.transpose() for x in s] for s in reps]

def simultaneous_eigenspaces(matrices, n=None):
    n = matrices[_sage_const_0 ].dimensions()[_sage_const_0 ]
    spaces = [(identity_matrix(n, sparse=True), ())]
    for m in matrices:
        nspaces = []
        for B, wt in spaces:
            mrestricted = _restrict_map(m, B, B)
            for eigenval, eigenspace in mrestricted.eigenspaces_right():
                W = eigenspace.basis_matrix().transpose().sparse_matrix()
                nspaces.append((B * W, wt + (eigenval,)))
        spaces = nspaces
    return spaces

def weight_decomposition(reps, C, n=None):
    eigenspaces = simultaneous_eigenspaces(reps[_sage_const_2 ])
    totkey = lambda wt: tuple(C.solve_right(vector(QQ, wt)).list())
    eigenspaces.sort(key=lambda p: totkey(p[_sage_const_1 ]))
    M = {wt: V for V, wt in eigenspaces}
    tot = [(wt, V.dimensions()[_sage_const_1 ]) for V, wt in eigenspaces]
    wtg = DiGraph()
    for p in tot:
        wt, mult = p
        B = M[wt]
        for i, x in enumerate(reps[_sage_const_0 ]):
            wt2 = tuple((C[:, i] + vector(wt).column()).list())
            if wt2 in M:
                wtg.add_edge(p, (wt2, M[wt2].dimensions()[_sage_const_1 ]),
                             _restrict_map(x, M[wt2], B))
    return {'M': M, 'tot': tot, 'C': C, 'a': reps, 'wtg': wtg}

def build_Mn_tensor(n):
    """Matrix mult tensor M_n in A(x)B(x)C, A=U*(x)V etc, plus sl(V) reps."""
    Tdim = n**_sage_const_2 
    T = [{} for _ in range(Tdim)]
    for i in range(n):
        for j in range(n):
            alpha = i * n + j
            for k in range(n):
                beta = j * n + k
                gamma = k * n + i
                T[alpha][(beta, gamma)] = QQ(_sage_const_1 )
    T = [matrix(QQ, Tdim, Tdim, m, sparse=True) for m in T]

    def eij(i, j):
        return matrix(QQ, n, n, {(i, j): _sage_const_1 })
    # sl_n raising/lowering/cartan on V = C^n
    X = [eij(i, i + _sage_const_1 ) for i in range(n - _sage_const_1 )]
    Y = [eij(i + _sage_const_1 , i) for i in range(n - _sage_const_1 )]
    H = [eij(i, i) - eij(i + _sage_const_1 , i + _sage_const_1 ) for i in range(n - _sage_const_1 )]
    gens_V = [X, Y, H]
    gens_Vstar = [[-g.transpose() for g in gs] for gs in gens_V]
    Id = identity_matrix(QQ, n, sparse=True)
    reps_A = [[Id.tensor_product(g) for g in gs] for gs in gens_V]
    reps_B = [[g.tensor_product(Id) for g in gs] for gs in gens_Vstar]
    reps_C = [[matrix(QQ, n**_sage_const_2 , n**_sage_const_2 , sparse=True) for _ in range(n - _sage_const_1 )] for _ in range(_sage_const_3 )]
    C = cartan_matrix_sln(n)
    return T, [reps_A, reps_B, reps_C], C

def build_Tperp_and_module(T, reps, C, n):
    reps_AB = module_product(reps[_sage_const_0 ], reps[_sage_const_1 ])
    reps_AB_dual = module_dual(reps_AB)
    Tmat = matrix(QQ, [m.list() for m in T], sparse=True)
    Tperp = Tmat.right_kernel_matrix().transpose().sparse_matrix()
    M_restricted = [[_restrict_map(m, Tperp, Tperp) for m in s] for s in reps_AB_dual]
    data = weight_decomposition(M_restricted, C, n**_sage_const_2 )
    return data, Tperp

# ============ the (210) test (kashbari matrix_11_to_21) ============

def transpose_tensor(B, a):
    b = B.dimensions()[_sage_const_0 ] // a
    Bp = {}
    for I, k in B.nonzero_positions():
        i, j = I // b, I % b
        Bp[(j * a + i, k)] = B[I, k]
    return matrix(B.base_ring(), B.dimensions()[_sage_const_0 ], B.dimensions()[_sage_const_1 ], Bp)

def matrix_11_to_21(B, a):
    """Kashbari: columns of B span E_110 in A(x)B. Returns A*I -> S^2(A)(x)B."""
    b = B.dimensions()[_sage_const_0 ] // a
    S = B.dimensions()[_sage_const_1 ]
    W = {}
    for I, s in B.nonzero_positions():
        i, j = I // b, I % b
        v = B[I, s]
        for k in range(a):
            mi, ma = min(i, k), max(i, k)
            ix = (binomial(ma + _sage_const_1 , _sage_const_2 ) + mi) * b + j
            col = s * a + k
            W[(ix, col)] = W.get((ix, col), _sage_const_0 ) + v
    return matrix(B.base_ring(), binomial(a + _sage_const_1 , _sage_const_2 ) * b, S * a, W)

def skew_210_map(B, a):
    """
    CHL dual (210) map: E_110 (x) A -> Lambda^2(A) (x) B.
    For v = sum e_i (x) e_j in E_110, and basis e_k of A:
      e_k . v = sum (e_k ^ e_i) (x) e_j.
    Lambda^2(A) index for {p<q} is binomial(q,2)+p; sign +1 if k<i, -1 if k>i, 0 if k==i.
    Target dim = binomial(a,2)*b. Domain dim = S*a.
    """
    b = B.dimensions()[_sage_const_0 ] // a
    S = B.dimensions()[_sage_const_1 ]
    W = {}
    for I, s in B.nonzero_positions():
        i, j = I // b, I % b
        v = B[I, s]
        for k in range(a):
            if k == i:
                continue
            p, q = (k, i) if k < i else (i, k)
            sign = _sage_const_1  if k < i else -_sage_const_1 
            ix = (binomial(q, _sage_const_2 ) + p) * b + j
            col = s * a + k
            W[(ix, col)] = W.get((ix, col), _sage_const_0 ) + sign * v
    return matrix(B.base_ring(), binomial(a, _sage_const_2 ) * b, S * a, W)

# ============ M_2 calibration ============

n = _sage_const_2 
r = _sage_const_6 
T, reps, C = build_Mn_tensor(n)
data, em = build_Tperp_and_module(T, reps, C, n)
adim = n**_sage_const_2   # 4

print("=== M_2 calibration (CHL section Mtwo) ===")
print("n=%d, r=%d, ambient A(x)B dim=%d, dim Tperp=%d" % (n, r, em.dimensions()[_sage_const_0 ], em.dimensions()[_sage_const_1 ]))
print("U*(x)sl(V)(x)W dim should be 2*3*2=12; dim Tperp=%d" % em.dimensions()[_sage_const_1 ])
print()

# The U*(x)Id_V(x)W part is T(C*) = Id_V direction. E_110 = (U*(x)Id_V(x)W) (+) E_110'.
# We need the FULL E_110 (dim r=6) to feed matrix_11_to_21, because CHL's
# (210) test acts on E_110 = F_110^perp (dim r), not just E_110' (dim r-wu=2).
#
# T(C*) = M_n(C*) = U* (x) Id_V (x) W, dim = n*n = 4 for M_2.
# It is the column space of Tmat^T... actually T(C*) = span of {sum_gamma c_gamma * (col gamma of the A(x)B picture)}.
# Equivalently: T as a map C -> A(x)B has image = column space of [T[alpha].list() stacked]?
# T[alpha] is the (beta,gamma) matrix for fixed alpha=A-index. We want the map
# C* -> A(x)B, i.e. for each gamma (C-index) the element sum_{alpha,beta} T[alpha][beta,gamma] e_alpha (x) e_beta.
TCstar_cols = {}
for alpha in range(adim):
    for (beta, gamma) in T[alpha].dict():
        v = T[alpha][beta, gamma]
        TCstar_cols[(alpha * adim + beta, gamma)] = v  # row = alpha*b+beta in A(x)B, col = gamma
TCstar = matrix(QQ, adim * adim, adim, TCstar_cols)
print("T(C*) (= U*(x)Id_V(x)W) dims = %s, rank = %d (expect %d)" % (str(TCstar.dimensions()), TCstar.rank(), n*n))
print()

# Build the basis index helper for A = U* (x) V, x^i_j -> (i-1)*n+(j-1) (1-indexed in CHL)
def xidx(i, j):  # i,j 1-indexed
    return (i - _sage_const_1 ) * n + (j - _sage_const_1 )
def yidx(i, j):
    return (i - _sage_const_1 ) * n + (j - _sage_const_1 )
def ab_vec(pairs):
    # pairs: list of (coeff, (xi,xj), (yi,yj)). Returns a column vector in A(x)B.
    v = vector(QQ, adim * adim)
    for coeff, (xi, xj), (yi, yj) in pairs:
        v[xidx(xi, xj) * adim + yidx(yi, yj)] += coeff
    return v

# The 3 B-fixed E_110' 2-planes (CHL L719-723):
P1 = [ab_vec([(_sage_const_1 , (_sage_const_2 ,_sage_const_1 ), (_sage_const_2 ,_sage_const_1 ))]), ab_vec([(_sage_const_1 , (_sage_const_1 ,_sage_const_1 ), (_sage_const_2 ,_sage_const_1 ))])]
P2 = [ab_vec([(_sage_const_1 , (_sage_const_2 ,_sage_const_1 ), (_sage_const_2 ,_sage_const_1 ))]), ab_vec([(_sage_const_1 , (_sage_const_2 ,_sage_const_1 ), (_sage_const_2 ,_sage_const_2 ))])]
P3 = [ab_vec([(_sage_const_1 , (_sage_const_2 ,_sage_const_1 ), (_sage_const_2 ,_sage_const_1 ))]), ab_vec([(_sage_const_1 , (_sage_const_2 ,_sage_const_1 ), (_sage_const_1 ,_sage_const_1 )), (-_sage_const_1 , (_sage_const_2 ,_sage_const_2 ), (_sage_const_2 ,_sage_const_1 ))])]

planes = [("P1", P1), ("P2", P2), ("P3", P3)]

for name, Pp in planes:
    # E_110 = T(C*) (+) E_110'  (full dim-6 space)
    E110_cols = TCstar.augment(matrix(QQ, adim * adim, len(Pp), {(i, c): Pp[c][i]
                  for c in range(len(Pp)) for i in Pp[c].nonzero_positions()}))
    # sanity: dim
    rk = E110_cols.rank()
    # --- symmetric S^2 map (kashbari matrix_11_to_21) ---
    Msym = matrix_11_to_21(E110_cols, adim)
    Msym_t = matrix_11_to_21(transpose_tensor(E110_cols, adim), adim)
    # --- skew Lambda^2 map (CHL dual prop) ---
    Mskew = skew_210_map(E110_cols, adim)
    Mskew_t = skew_210_map(transpose_tensor(E110_cols, adim), adim)
    print("%s: dim E_110 = %d" % (name, rk))
    print("   SYM (210) %s rank=%d  codim_in_target=%d  rank<=domain-r? %d<=%d=%s"
          % (str(Msym.dimensions()), Msym.rank(), Msym.dimensions()[_sage_const_0 ]-Msym.rank(),
             Msym.rank(), Msym.dimensions()[_sage_const_1 ]-r, "Y" if Msym.rank()<=Msym.dimensions()[_sage_const_1 ]-r else "N"))
    print("   SKEW(210) %s rank=%d  ker=domain-rank=%d (CHL test: ker>=r i.e. rank<=domain-r=%d => %s)"
          % (str(Mskew.dimensions()), Mskew.rank(), Mskew.dimensions()[_sage_const_1 ]-Mskew.rank(),
             Mskew.dimensions()[_sage_const_1 ]-r,
             "PASS" if Mskew.rank() <= Mskew.dimensions()[_sage_const_1 ]-r else "FAIL"))
    print("   SKEW(120) %s rank=%d (CHL test: rank<=domain-r=%d => %s)"
          % (str(Mskew_t.dimensions()), Mskew_t.rank(), Mskew_t.dimensions()[_sage_const_1 ]-r,
             "PASS" if Mskew_t.rank() <= Mskew_t.dimensions()[_sage_const_1 ]-r else "FAIL"))

