

# This file was *autogenerated* from the file /workspace/Oe1-dispatch-psl27-multi.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5000 = Integer(5000); _sage_const_168 = Integer(168); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_2000 = Integer(2000); _sage_const_24 = Integer(24); _sage_const_21 = Integer(21)# Oe1 DISPATCH (medium, single-core): PSL(2,7) MULTI-ORBIT closure.
# Single-orbit PSL(2,7) is already ALL-INFEASIBLE (Oe1-family2-psl27-solve.sage:
# every stabilizer of order>=8 gives the unit ideal). This closes the multi-orbit
# case: combine the small-orbit stabilizers (orbit 7 from S_4-stab, orbit 8 from
# 7:3-stab) into configs with total orbit <= 21 (so rank <= 22) and solve each
# over the cyclotomic field. SOLUTION-FOUND rank<23 => STOP.
#
# Run:  sager Sager/Oe1-dispatch-psl27-multi.sage
# Emits one JSON line per config + summary.
#
# Configs in budget (orbit 7 = a, orbit 8 = b):
#   a+a (14), a+b (15), b+b (16), a+a+a... no (21 with three 7s => rank22 ok),
#   a+a+b (22 -> orbit 22 >21 NO). So: {a,a},{a,b},{b,b},{a,a,a}. Each orbit's
#   stabilizer (S_4 or 7:3) has fixed_dim 1, so a k-orbit config has k variables.

import json
def _coerce(o):
    from sage.all import Integer, Rational
    if isinstance(o, Integer): return int(o)
    if isinstance(o, Rational): return int(o) if o.denominator()==_sage_const_1  else float(o)
    if isinstance(o, dict): return {k:_coerce(v) for k,v in o.items()}
    if isinstance(o, (list,tuple)): return [_coerce(v) for v in o]
    return o
def emit(d): print(json.dumps(_coerce(d)), flush=True)
R7=CyclotomicField(_sage_const_7 )
G=gap.PSL(_sage_const_2 ,_sage_const_7 ); irr=gap.IrreducibleRepresentations(G); rep=irr[_sage_const_2 ]
Ggens=gap.GeneratorsOfGroup(G); ngens=Integer(gap.Length(Ggens))
def conv(s):
    s=str(s)
    if 'E(' in s: return R7(sage_eval(s.replace('E(','CyclotomicField(').replace(')',').gen()')))
    return R7(QQ(s))
genmats=[]
for k in range(_sage_const_1 ,ngens+_sage_const_1 ):
    Mg=gap.Image(rep,Ggens[k]); M=matrix(R7,_sage_const_3 ,_sage_const_3 )
    for a in range(_sage_const_1 ,_sage_const_4 ):
        for b in range(_sage_const_1 ,_sage_const_4 ): M[a-_sage_const_1 ,b-_sage_const_1 ]=conv(gap(Mg[a][b]))
    genmats.append(M)
def matkey(M): return tuple(M.list())
I3=identity_matrix(R7,_sage_const_3 )
elems={matkey(I3):I3}; frontier=[I3]
for _ in range(_sage_const_5000 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for g in genmats:
            ne=g*e; kk=matkey(ne)
            if kk not in elems: elems[kk]=ne; new.append(ne)
    frontier=new
ELEM=list(elems.values()); assert len(ELEM)==_sage_const_168 
def matorder(M):
    P=M; o=_sage_const_1 
    while P!=I3 and o<_sage_const_200 : P=P*M; o+=_sage_const_1 
    return o
sigma=[M for M in ELEM if matorder(M)==_sage_const_3 ][_sage_const_0 ]
def conjOp(g):
    gi=g.inverse(); C=matrix(R7,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(R7,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=g*E*gi; col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
    return C
def fixedBasis_sub(H):
    rows=[]; I9=identity_matrix(R7,_sage_const_9 )
    for h in H: rows.append(conjOp(h)-I9)
    big=block_matrix(R7,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(R7,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker]
def sub_mats(Hgap):
    hg=gap.GeneratorsOfGroup(Hgap); nh=Integer(gap.Length(hg))
    if nh==_sage_const_0 : return [I3]
    gm=[]
    for k in range(_sage_const_1 ,nh+_sage_const_1 ):
        Mg=gap.Image(rep,hg[k]); M=matrix(R7,_sage_const_3 ,_sage_const_3 )
        for a in range(_sage_const_1 ,_sage_const_4 ):
            for b in range(_sage_const_1 ,_sage_const_4 ): M[a-_sage_const_1 ,b-_sage_const_1 ]=conv(gap(Mg[a][b]))
        gm.append(M)
    Hd={matkey(I3):I3}; fr=[I3]
    for _ in range(_sage_const_2000 ):
        if not fr: break
        nn=[]
        for e in fr:
            for g in gm:
                ne=g*e; kk=matkey(ne)
                if kk not in Hd: Hd[kk]=ne; nn.append(ne)
        fr=nn
    return list(Hd.values())
# get one S_4 stab (orbit7) and one 7:3 stab (orbit8)
ccs=gap.ConjugacyClassesSubgroups(G); ncc=Integer(gap.Length(ccs))
H_s4=None; H_73=None
for ci in range(_sage_const_1 ,ncc+_sage_const_1 ):
    H=gap.Representative(ccs[ci]); o=Integer(gap.Order(H))
    if o==_sage_const_24  and H_s4 is None: H_s4=sub_mats(H)
    if o==_sage_const_21  and H_73 is None: H_73=sub_mats(H)
fb_s4=fixedBasis_sub(H_s4); fb_73=fixedBasis_sub(H_73)
emit({"info":"stabs","S4_orbit":_sage_const_168 //len(H_s4),"S4_fixed_dim":len(fb_s4),
      "F21_orbit":_sage_const_168 //len(H_73),"F21_fixed_dim":len(fb_73)})
Eb=[]
for i in range(_sage_const_3 ):
    for j in range(_sage_const_3 ):
        E=matrix(R7,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; Eb.append(E)
def residual(ai,bi,ci):
    A,B,C=Eb[ai],Eb[bi],Eb[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()
TYPES={"S4":(fb_s4,_sage_const_168 //len(H_s4)),"F21":(fb_73,_sage_const_168 //len(H_73))}
def build_solve(cfg):
    # cfg: list of type names; each orbit own variable block
    nv=sum(len(TYPES[t][_sage_const_0 ]) for t in cfg)
    Rr=PolynomialRing(R7,nv,[f"x{i}" for i in range(nv)]); xs=Rr.gens()
    seeds=[]; off=_sage_const_0 
    for t in cfg:
        fb,_=TYPES[t]; d=len(fb)
        mm=matrix(Rr,_sage_const_3 ,_sage_const_3 )
        for p in range(d): mm+=xs[off+p]*fb[p].change_ring(Rr)
        s=sigma.change_ring(Rr); mm2=s*mm*s.inverse(); s2=(sigma*sigma).change_ring(Rr); mm3=s2*mm*s2.inverse()
        seeds.append((mm,mm2,mm3)); off+=d
    def fR(Xc,Ms):
        acc=Rr(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ):
                if Xc[i,j]!=_sage_const_0 : acc+=Xc[i,j]*Ms[i,j]
        return acc
    polys=[]
    for ai in range(_sage_const_9 ):
        for bi in range(_sage_const_9 ):
            for cci in range(_sage_const_9 ):
                orb=Rr(_sage_const_0 )
                for (mm,mm2,mm3) in seeds:
                    for gg in ELEM:
                        gR=gg.change_ring(Rr); gmi=gR.inverse()
                        la=fR(Eb[ai],gR*mm*gmi)
                        if la==_sage_const_0 : continue
                        lb=fR(Eb[bi],gR*mm2*gmi)
                        if lb==_sage_const_0 : continue
                        lc=fR(Eb[cci],gR*mm3*gmi)
                        if lc==_sage_const_0 : continue
                        orb+=la*lb*lc
                P=orb+residual(ai,bi,cci)
                if P!=_sage_const_0 : polys.append(P)
    I=Rr.ideal(polys); unit=(Rr.one() in I)
    return unit,(None if unit else I.dimension())
CFGS=[["S4","S4"],["S4","F21"],["F21","F21"],["S4","S4","S4"]]
any_sol=False
for cfg in CFGS:
    tot=sum(TYPES[t][_sage_const_1 ] for t in cfg)
    if tot>_sage_const_21 :
        emit({"config":"+".join(cfg),"total_orbit":int(tot),"verdict":"OVER-BUDGET"}); continue
    unit,dim=build_solve(cfg)
    rec={"config":"+".join(cfg),"num_orbits":len(cfg),"total_orbit":int(tot),"rank":int(_sage_const_1 +tot)}
    if unit: rec["verdict"]="INFEASIBLE"
    else: rec["verdict"]="SOLUTION-FOUND"; rec["dimension"]=int(dim); any_sol=True
    emit(rec)
emit({"group":"PSL(2,7)","summary":True,"multi_orbit_verdict":("RANK-IMPROVED *** STOP ***" if any_sol else "ALL-INFEASIBLE")})

