

# This file was *autogenerated* from the file /workspace/Oe1-family2-psl27-control.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5000 = Integer(5000); _sage_const_168 = Integer(168); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_2000 = Integer(2000); _sage_const_8 = Integer(8)# Oe1 Family 2: PSL(2,7) builder validation (Os1-style) + multi-orbit coverage.
# Validates the cyclotomic-field builder with a planted seed (POSITIVE feasible,
# NEGATIVE T_MM infeasible), then checks whether any multi-orbit PSL(2,7) config
# (orbits 7,8 fit; total <=21) can cover the 48 residual dirs -- if not, those are
# INFEASIBLE-BY-COVERAGE without further Groebner.

R7=CyclotomicField(_sage_const_7 ); z=R7.gen()
G=gap.PSL(_sage_const_2 ,_sage_const_7 ); irr=gap.IrreducibleRepresentations(G); rep=irr[_sage_const_2 ]
Ggens=gap.GeneratorsOfGroup(G); ngens=Integer(gap.Length(Ggens))
def conv(s):
    s=str(s)
    if 'E(' in s: return R7(sage_eval(s.replace('E(','CyclotomicField(').replace(')',').gen()')))
    return R7(QQ(s))
genmats=[]
for k in range(_sage_const_1 ,ngens+_sage_const_1 ):
    Mg=gap.Image(rep,Ggens[k]); M=matrix(R7,_sage_const_3 ,_sage_const_3 )
    for a in range(_sage_const_1 ,_sage_const_4 ):
        for b in range(_sage_const_1 ,_sage_const_4 ): M[a-_sage_const_1 ,b-_sage_const_1 ]=conv(gap(Mg[a][b]))
    genmats.append(M)
def matkey(M): return tuple(M.list())
I3=identity_matrix(R7,_sage_const_3 )
elems={matkey(I3):I3}; frontier=[I3]
for _ in range(_sage_const_5000 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for g in genmats:
            ne=g*e; k=matkey(ne)
            if k not in elems: elems[k]=ne; new.append(ne)
    frontier=new
ELEM=list(elems.values()); assert len(ELEM)==_sage_const_168 
def matorder(M):
    P=M; o=_sage_const_1 
    while P!=I3 and o<_sage_const_200 : P=P*M; o+=_sage_const_1 
    return o
sigma=[M for M in ELEM if matorder(M)==_sage_const_3 ][_sage_const_0 ]
def conjOp(g):
    gi=g.inverse(); C=matrix(R7,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(R7,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=g*E*gi; col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
    return C
def fixedBasis_sub(H):
    rows=[]; I9=identity_matrix(R7,_sage_const_9 )
    for h in H: rows.append(conjOp(h)-I9)
    big=block_matrix(R7,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(R7,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker]
Eb=[]
for i in range(_sage_const_3 ):
    for j in range(_sage_const_3 ):
        E=matrix(R7,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; Eb.append(E)
def residual(ai,bi,ci):
    A,B,C=Eb[ai],Eb[bi],Eb[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()
Rsupport=set((a,b,c) for a in range(_sage_const_9 ) for b in range(_sage_const_9 ) for c in range(_sage_const_9 ) if residual(a,b,c)!=_sage_const_0 )
def ansatz_inner(seeds,A,B,C):
    val=A.trace()*B.trace()*C.trace()
    def fr(X,M):
        s=R7(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ): s+=X[i,j]*M[i,j]
        return s
    for m1 in seeds:
        m2=sigma*m1*sigma.inverse(); m3=sigma*sigma*m1*(sigma.inverse())**_sage_const_2 
        for g in ELEM:
            gi=g.inverse()
            f1=fr(A,g*m1*gi)
            if f1==_sage_const_0 : continue
            f2=fr(B,g*m2*gi)
            if f2==_sage_const_0 : continue
            f3=fr(C,g*m3*gi)
            if f3==_sage_const_0 : continue
            val+=f1*f2*f3
    return val

# Get the |H|=8 subgroup (fixed dim 2, the richest seed) for the control.
ccs=gap.ConjugacyClassesSubgroups(G); ncc=Integer(gap.Length(ccs))
def subgroup_matrices(Hgap):
    hg=gap.GeneratorsOfGroup(Hgap); nh=Integer(gap.Length(hg))
    if nh==_sage_const_0 : return [I3]
    gmats=[]
    for k in range(_sage_const_1 ,nh+_sage_const_1 ):
        Mg=gap.Image(rep,hg[k]); M=matrix(R7,_sage_const_3 ,_sage_const_3 )
        for a in range(_sage_const_1 ,_sage_const_4 ):
            for b in range(_sage_const_1 ,_sage_const_4 ): M[a-_sage_const_1 ,b-_sage_const_1 ]=conv(gap(Mg[a][b]))
        gmats.append(M)
    Hd={matkey(I3):I3}; fr=[I3]
    for _ in range(_sage_const_2000 ):
        if not fr: break
        nn=[]
        for e in fr:
            for g in gmats:
                ne=g*e; k=matkey(ne)
                if k not in Hd: Hd[k]=ne; nn.append(ne)
        fr=nn
    return list(Hd.values())
H8=None
for ci in range(_sage_const_1 ,ncc+_sage_const_1 ):
    H=gap.Representative(ccs[ci])
    if Integer(gap.Order(H))==_sage_const_8 :
        Hm=subgroup_matrices(H)
        if len(fixedBasis_sub(Hm))==_sage_const_2 : H8=Hm; break
fb=fixedBasis_sub(H8); d=len(fb); orbit=_sage_const_168 //len(H8)
print(f"PSL(2,7) |H|=8 stab: orbit {orbit}, rank {_sage_const_1 +orbit}, fixed dim {d}")
mstar=fb[_sage_const_0 ]+_sage_const_2 *fb[_sage_const_1 ] if d>=_sage_const_2  else fb[_sage_const_0 ]
Rr=PolynomialRing(R7,d,[f"x{i}" for i in range(d)]); xs=Rr.gens()
m1=matrix(Rr,_sage_const_3 ,_sage_const_3 )
for p in range(d): m1+=xs[p]*fb[p].change_ring(Rr)
s=sigma.change_ring(Rr); m2=s*m1*s.inverse(); s2=(sigma*sigma).change_ring(Rr); m3=s2*m1*s2.inverse()
def frobR(Xc,Ms):
    acc=Rr(_sage_const_0 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            if Xc[i,j]!=_sage_const_0 : acc+=Xc[i,j]*Ms[i,j]
    return acc
gm={}
for gi,gg in enumerate(ELEM):
    gR=gg.change_ring(Rr); gmi=gR.inverse()
    gm[(gi,_sage_const_0 )]=gR*m1*gmi; gm[(gi,_sage_const_1 )]=gR*m2*gmi; gm[(gi,_sage_const_2 )]=gR*m3*gmi
def bp(ti):
    polys=[]
    for ai in range(_sage_const_9 ):
        for bi in range(_sage_const_9 ):
            for cci in range(_sage_const_9 ):
                orb=Rr(_sage_const_0 )
                for gi in range(len(ELEM)):
                    la=frobR(Eb[ai],gm[(gi,_sage_const_0 )])
                    if la==_sage_const_0 : continue
                    lb=frobR(Eb[bi],gm[(gi,_sage_const_1 )])
                    if lb==_sage_const_0 : continue
                    lc=frobR(Eb[cci],gm[(gi,_sage_const_2 )])
                    if lc==_sage_const_0 : continue
                    orb+=la*lb*lc
                P=orb+(Eb[ai].trace()*Eb[bi].trace()*Eb[cci].trace()-ti(ai,bi,cci))
                if P!=_sage_const_0 : polys.append(P)
    return polys
tp={}
def tprime(ai,bi,ci):
    k=(ai,bi,ci)
    if k not in tp: tp[k]=ansatz_inner([mstar],Eb[ai],Eb[bi],Eb[ci])
    return tp[k]
pos=bp(tprime); Ipos=Rr.ideal(pos)
xstar={xs[p]:[R7(_sage_const_1 ),R7(_sage_const_2 )][p] for p in range(d)}
posvanish=all(P.subs(xstar)==_sage_const_0  for P in pos); unitpos=(Rr.one() in Ipos)
def tmm(ai,bi,ci): return (Eb[ai]*Eb[bi]*Eb[ci]).trace()
neg=bp(tmm); unitneg=(Rr.one() in Rr.ideal(neg))
print("PSL(2,7) builder validation (|H|=8, rank 22):")
print(f"  POSITIVE planted vanishes: {posvanish}, unit: {unitpos} (want True,False)")
print(f"  NEGATIVE T_MM unit: {unitneg} (want True)")
print(f"  VALIDATION: {'PASS' if (posvanish and not unitpos and unitneg) else 'FAIL'}")

