

# This file was *autogenerated* from the file /workspace/Oe1-family1-threeplus-orbits.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_24 = Integer(24); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10)# Oe1 Family 1 pre-screen: >=3 orbits under S_4 (same H-fixed seed spaces).
#
# Or2's obstruction is per-orbit and ADDITIVE: on a basis triple (A,B,C), the
# total orbit-sum is sum over orbits of that orbit's contribution. If a triple is
# obstructed (contribution identically 0 in the seed vars) for EVERY orbit type,
# then ANY multiset of orbits -- 3, 4, ... -- still contributes identically 0
# there. If such a commonly-obstructed triple also has nonzero MM residual
# tr(A)tr(B)tr(C)-tr(ABC), it is a KILLER that no number of catalog orbits can
# satisfy => the >=3-orbit family is DEAD by the same mechanism, rank budget moot.
#
# Decisive computation: intersect the 6 catalog obstructed-sets; among the common
# triples, count those with nonzero residual. If >0, Family 1 is PRE-SCREEN-DEAD.

import json, itertools

K = QuadraticField(_sage_const_3 , names=('r3',)); (r3,) = K._first_ngens(1)
def Mt(rows): return matrix(K, rows)
rho_12 = Mt([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]])
rho_23 = Mt([[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
rho_34 = Mt([[_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]])
sigma  = Mt([[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
gens = {(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 ): rho_12, (_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ): rho_23, (_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 ): rho_34}
def compose(p,q): return tuple(p[q[i]] for i in range(_sage_const_4 ))
ident = (_sage_const_0 ,_sage_const_1 ,_sage_const_2 ,_sage_const_3 )
elems = {ident: identity_matrix(K,_sage_const_3 )}
frontier=[ident]
for _ in range(_sage_const_100 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for gp in gens:
            ne = compose(gp,e)
            if ne not in elems:
                elems[ne] = gens[gp]*elems[e]; new.append(ne)
    frontier=new
assert len(elems)==_sage_const_24 
ELEM = list(elems.values())
def conjM(g, X): return g*X*g.transpose()

def rrStarBasis():
    idm = identity_matrix(K,_sage_const_3 )
    boxX = diagonal_matrix(K,[_sage_const_1 , -_sage_const_1 /_sage_const_2 , -_sage_const_1 /_sage_const_2 ])
    boxY = diagonal_matrix(K,[_sage_const_0 , r3/_sage_const_2 , -r3/_sage_const_2 ])
    def E(pairs):
        M = matrix(K,_sage_const_3 ,_sage_const_3 )
        for (i,j,v) in pairs: M[i,j]=v
        return M
    s1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_1 )]); s2=E([(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); s3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,_sage_const_1 )])
    a1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,-_sage_const_1 )]); a2=E([(_sage_const_0 ,_sage_const_2 ,-_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); a3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,-_sage_const_1 )])
    return [idm,boxX,boxY,s1,s2,s3,a1,a2,a3]
BR = rrStarBasis()
NAMES = ["id","box_x","box_y","s1","s2","s3","a1","a2","a3"]

def subgroup(genperms):
    H={ident}; fr=[ident]
    while fr:
        nn=[]
        for e in fr:
            for g in genperms:
                ne=compose(g,e)
                if ne not in H: H.add(ne); nn.append(ne)
        fr=nn
    return H
def conjOperator(g):
    C = matrix(K,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E = matrix(K,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 
            img = conjM(elems[g], E); col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b, col]=img[a,b]
    return C
def fixedBasis(genperms):
    H=subgroup(genperms); rows=[]; I9=identity_matrix(K,_sage_const_9 )
    for h in H: rows.append(conjOperator(h)-I9)
    big=block_matrix(K,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(K,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker], len(H)

S3=[(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ),(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 )]; K4=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_3 ,_sage_const_0 ,_sage_const_1 )]; Z4=[(_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_0 )]
Z3=[(_sage_const_1 ,_sage_const_2 ,_sage_const_0 ,_sage_const_3 )]; Z2t=[(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 )]; Z2d=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 )]
CATALOG=[("S_3",S3,_sage_const_4 ),("K_4",K4,_sage_const_6 ),("Z_4",Z4,_sage_const_6 ),("Z_3",Z3,_sage_const_8 ),
         ("Z_2t",Z2t,_sage_const_12 ),("Z_2d",Z2d,_sage_const_12 )]

def orbit_obstructed_set(genperms):
    fb,hord = fixedBasis(genperms); d=len(fb)
    R = PolynomialRing(K, d, [f"x{i}" for i in range(d)] if d>_sage_const_0  else ["x0"])
    xs=R.gens()
    m1=matrix(R,_sage_const_3 ,_sage_const_3 )
    for p in range(d): m1 += xs[p]*fb[p].change_ring(R)
    s=sigma.change_ring(R); m2=s*m1*s.transpose()
    s2=(sigma*sigma).change_ring(R); m3=s2*m1*s2.transpose()
    gm={}
    for gi,g in enumerate(ELEM):
        gR=g.change_ring(R)
        gm[(gi,_sage_const_0 )]=gR*m1*gR.transpose(); gm[(gi,_sage_const_1 )]=gR*m2*gR.transpose(); gm[(gi,_sage_const_2 )]=gR*m3*gR.transpose()
    def frobR(Xc,Ms):
        acc=R(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ):
                if Xc[i,j]!=_sage_const_0 : acc += Xc[i,j]*Ms[i,j]
        return acc
    obs=set()
    for ai in range(_sage_const_9 ):
        for bi in range(_sage_const_9 ):
            for ci in range(_sage_const_9 ):
                orb=R(_sage_const_0 )
                for gi in range(len(ELEM)):
                    la=frobR(BR[ai],gm[(gi,_sage_const_0 )])
                    if la==_sage_const_0 : continue
                    lb=frobR(BR[bi],gm[(gi,_sage_const_1 )])
                    if lb==_sage_const_0 : continue
                    lc=frobR(BR[ci],gm[(gi,_sage_const_2 )])
                    if lc==_sage_const_0 : continue
                    orb += la*lb*lc
                if orb==_sage_const_0 : obs.add((ai,bi,ci))
    return obs

def residual(ai,bi,ci):
    A,B,C=BR[ai],BR[bi],BR[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()

# Compute the 6 obstructed sets and intersect them.
obs_sets={}
for name,g,orb in CATALOG:
    obs_sets[name]=orbit_obstructed_set(g)
    print(f"{name}: {len(obs_sets[name])} obstructed")

common = set(range(_sage_const_9 *_sage_const_9 *_sage_const_9 ))  # placeholder; build intersection properly
common = None
for name in obs_sets:
    s = obs_sets[name]
    common = s if common is None else (common & s)
print(f"\nCOMMON obstructed (all 6 orbit types): {len(common)} of 729")

# Among the common-obstructed triples, which have NONZERO MM residual?
# These are killers that NO multiset of catalog orbits can satisfy.
common_killers = [(ai,bi,ci) for (ai,bi,ci) in common if residual(ai,bi,ci)!=_sage_const_0 ]
print(f"COMMON-KILLER triples (obstructed for all + residual!=0): {len(common_killers)}")

# Show a few, with the canonical (id,box_x,box_x)=(0,1,1) check.
for t in sorted(common_killers)[:_sage_const_10 ]:
    ai,bi,ci=t
    print(f"  ({ai},{bi},{ci})=({NAMES[ai]},{NAMES[bi]},{NAMES[ci]}): residual={residual(ai,bi,ci)}")

canonical=(_sage_const_0 ,_sage_const_1 ,_sage_const_1 )
print(f"\nCanonical box-box triple (id,box_x,box_x)=(0,1,1):")
print(f"  in COMMON obstructed set: {canonical in common}")
print(f"  residual: {residual(*canonical)}")

# Verdict logic.
if len(common_killers)>_sage_const_0 :
    print("\nVERDICT Family 1 (>=3 orbits S_4): PRE-SCREEN-DEAD")
    print(f"  {len(common_killers)} triples are obstructed for every catalog orbit type")
    print(f"  yet carry nonzero MM residual. Adding any number of these orbits keeps")
    print(f"  the contribution identically zero there => constant generator => unit ideal.")
else:
    print("\nVERDICT Family 1: SURVIVES pre-screen -- a third orbit can reach the obstructed directions; build the probe.")

