

# This file was *autogenerated* from the file /workspace/Oe1-family2-psl27-solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_5000 = Integer(5000); _sage_const_168 = Integer(168); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_4 = Integer(4); _sage_const_2000 = Integer(2000); _sage_const_8 = Integer(8); _sage_const_21 = Integer(21)# Oe1 Family 2: PSL(2,7) full feasibility. Build the 3-dim irrep (cyclotomic
# field, contains sqrt-7), enumerate subgroups of order >= 8 (=> orbit <= 21),
# compute their conjugation fixed-space dims, and solve the GM sigma-twisted
# single-orbit system over the cyclotomic field. SOLUTION-FOUND rank<23 => STOP.
#
# PSL(2,7) is 2-transitive (not 3-transitive) on 7 points, so GM's clean T_MM
# mechanism (needs 3-transitivity on 4 points) does not apply -- expect INFEASIBLE,
# but VERIFY by Groebner over the correct character field.

R7=CyclotomicField(_sage_const_7 ); z=R7.gen()
G=gap.PSL(_sage_const_2 ,_sage_const_7 )
irr=gap.IrreducibleRepresentations(G)
# 3-dim irrep index 2
rep=irr[_sage_const_2 ]
Ggens=gap.GeneratorsOfGroup(G); ngens=Integer(gap.Length(Ggens))
def conv(s):
    s=str(s)
    if 'E(' in s:
        return R7(sage_eval(s.replace('E(','CyclotomicField(').replace(')',').gen()')))
    return R7(QQ(s))
genmats=[]
for k in range(_sage_const_1 ,ngens+_sage_const_1 ):
    Mg=gap.Image(rep,Ggens[k]); rows=Integer(gap.Length(Mg))
    M=matrix(R7,rows,rows)
    for a in range(_sage_const_1 ,rows+_sage_const_1 ):
        for b in range(_sage_const_1 ,rows+_sage_const_1 ):
            M[a-_sage_const_1 ,b-_sage_const_1 ]=conv(gap(Mg[a][b]))
    genmats.append(M)
def matkey(M): return tuple(M.list())
I3=identity_matrix(R7,_sage_const_3 )
elems={matkey(I3):I3}; frontier=[I3]
for _ in range(_sage_const_5000 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for g in genmats:
            ne=g*e; k=matkey(ne)
            if k not in elems: elems[k]=ne; new.append(ne)
    frontier=new
ELEM=list(elems.values()); assert len(ELEM)==_sage_const_168 , len(ELEM)
# order-3 element for sigma
def matorder(M):
    P=M; o=_sage_const_1 
    while P!=I3 and o<_sage_const_200 : P=P*M; o+=_sage_const_1 
    return o
sigma=[M for M in ELEM if matorder(M)==_sage_const_3 ][_sage_const_0 ]
print("PSL(2,7) 3-dim irrep built, order 168, sigma order 3 found.")

# conjugation fixed space (over R7). rho irreducible: check End dim.
def conjOp(g):
    gi=g.inverse(); C=matrix(R7,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(R7,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=g*E*gi; col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
    return C
rows=[]; I9=identity_matrix(R7,_sage_const_9 )
for g in ELEM: rows.append(conjOp(g)-I9)
big=block_matrix(R7,[[m] for m in rows])
print("dim End(rho) =", _sage_const_9 -big.rank(), "(1 => irreducible)")

def fixedBasis_sub(Hmats):
    rows=[]; I9=identity_matrix(R7,_sage_const_9 )
    for h in Hmats: rows.append(conjOp(h)-I9)
    big=block_matrix(R7,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(R7,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker]

# Use GAP to get subgroups of order >=8 (=> orbit <=21). Get conjugacy class reps.
ccs=gap.ConjugacyClassesSubgroups(G)
print("num subgroup conjugacy classes:", Integer(gap.Length(ccs)))
# For each class rep H with |H|>=8, map its generators through rep, build matrix
# subgroup, compute fixed dim and orbit = 168/|H|.
Eb=[]
for i in range(_sage_const_3 ):
    for j in range(_sage_const_3 ):
        E=matrix(R7,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; Eb.append(E)
def residual(ai,bi,ci):
    A,B,C=Eb[ai],Eb[bi],Eb[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()
Rsupport=set((a,b,c) for a in range(_sage_const_9 ) for b in range(_sage_const_9 ) for c in range(_sage_const_9 ) if residual(a,b,c)!=_sage_const_0 )

def subgroup_matrices(Hgap):
    hg=gap.GeneratorsOfGroup(Hgap); nh=Integer(gap.Length(hg))
    if nh==_sage_const_0 :
        return [I3]
    gmats=[]
    for k in range(_sage_const_1 ,nh+_sage_const_1 ):
        Mg=gap.Image(rep,hg[k]); M=matrix(R7,_sage_const_3 ,_sage_const_3 )
        for a in range(_sage_const_1 ,_sage_const_4 ):
            for b in range(_sage_const_1 ,_sage_const_4 ): M[a-_sage_const_1 ,b-_sage_const_1 ]=conv(gap(Mg[a][b]))
        gmats.append(M)
    Hd={matkey(I3):I3}; fr=[I3]
    for _ in range(_sage_const_2000 ):
        if not fr: break
        nn=[]
        for e in fr:
            for g in gmats:
                ne=g*e; k=matkey(ne)
                if k not in Hd: Hd[k]=ne; nn.append(ne)
        fr=nn
    return list(Hd.values())

print("\nsubgroups order>=8 (orbit<=21): fixed dims and single-orbit feasibility")
ncc=Integer(gap.Length(ccs))
seen_orders=set()
for ci in range(_sage_const_1 ,ncc+_sage_const_1 ):
    H=gap.Representative(ccs[ci]); o=Integer(gap.Order(H))
    if o<_sage_const_8  or o>=_sage_const_168 : continue
    orbit=_sage_const_168 //o
    if orbit>_sage_const_21 : continue
    Hmats=subgroup_matrices(H)
    if len(Hmats)!=o:
        print(f"  |H|={o}: matrix subgroup order {len(Hmats)} != {o}, skip"); continue
    fb=fixedBasis_sub(Hmats); d=len(fb)
    tag=f"|H|={o} orbit={orbit} rank={_sage_const_1 +orbit} fixed_dim={d}"
    if d==_sage_const_0 :
        print(f"  {tag}: fixed dim 0 => no seed (id^3 only); skip"); continue
    # build & solve single-orbit system over R7
    Rr=PolynomialRing(R7,d,[f"x{i}" for i in range(d)]); xs=Rr.gens()
    m1=matrix(Rr,_sage_const_3 ,_sage_const_3 )
    for p in range(d): m1+=xs[p]*fb[p].change_ring(Rr)
    s=sigma.change_ring(Rr); m2=s*m1*s.inverse(); s2=(sigma*sigma).change_ring(Rr); m3=s2*m1*s2.inverse()
    def frobR(Xc,Ms):
        acc=Rr(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ):
                if Xc[i,j]!=_sage_const_0 : acc+=Xc[i,j]*Ms[i,j]
        return acc
    gm={}
    for gi,gg in enumerate(ELEM):
        gR=gg.change_ring(Rr); gmi=gR.inverse()
        gm[(gi,_sage_const_0 )]=gR*m1*gmi; gm[(gi,_sage_const_1 )]=gR*m2*gmi; gm[(gi,_sage_const_2 )]=gR*m3*gmi
    polys=[]; reach=set()
    for ai in range(_sage_const_9 ):
        for bi in range(_sage_const_9 ):
            for cci in range(_sage_const_9 ):
                orb=Rr(_sage_const_0 )
                for gi in range(len(ELEM)):
                    la=frobR(Eb[ai],gm[(gi,_sage_const_0 )])
                    if la==_sage_const_0 : continue
                    lb=frobR(Eb[bi],gm[(gi,_sage_const_1 )])
                    if lb==_sage_const_0 : continue
                    lc=frobR(Eb[cci],gm[(gi,_sage_const_2 )])
                    if lc==_sage_const_0 : continue
                    orb+=la*lb*lc
                if orb!=_sage_const_0 : reach.add((ai,bi,cci))
                P=orb+residual(ai,bi,cci)
                if P!=_sage_const_0 : polys.append(P)
    I=Rr.ideal(polys); unit=(Rr.one() in I)
    cov=len(reach&Rsupport); missed=Rsupport-reach
    v="INFEASIBLE (unit ideal)" if unit else f"SOLUTION-FOUND dim {I.dimension()} *** STOP rank {_sage_const_1 +orbit} ***"
    print(f"  {tag}: cov {cov}/{len(Rsupport)}{' MISS '+str(len(missed)) if missed else ''}; {v}")

