

# This file was *autogenerated* from the file /workspace/Oe1-family2-A5-control.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_2000 = Integer(2000); _sage_const_60 = Integer(60); _sage_const_9 = Integer(9)# Oe1 Family 2: A_5 POSITIVE/NEGATIVE control, mirroring Os1's validation of the
# S_4 builder. Before trusting the INFEASIBLE verdict for T_MM, validate the A_5
# constraint-system builder the same way Os1 validated Or2's:
#   POSITIVE: plant a concrete C_5-fixed seed m*, define T' = id^3 + A_5-orbit(m*)
#     via the SAME orbit sum, build the system against T', confirm it is FEASIBLE
#     (the planted x* is a root; Groebner NOT unit ideal) and the planted point
#     actually satisfies every constraint.
#   NEGATIVE: against T_MM (the real target) the system is the unit ideal.
# Same builder, only the target term differs => if positive=FEASIBLE(with planted
# root) and negative=INFEASIBLE, the builder discriminates and the T_MM unit-ideal
# verdict is trustworthy (not a builder bug that makes everything infeasible).

import json
K = QuadraticField(_sage_const_5 , names=('s5',)); (s5,) = K._first_ngens(1)
phi=(_sage_const_1 +s5)/_sage_const_2 ; half=K(_sage_const_1 )/_sage_const_2 
def Mt(rows): return matrix(K,rows)
g3=Mt([[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
g5=Mt([[half,-phi/_sage_const_2 ,(phi-_sage_const_1 )/_sage_const_2 ],[phi/_sage_const_2 ,(phi-_sage_const_1 )/_sage_const_2 ,-half],[(phi-_sage_const_1 )/_sage_const_2 ,half,phi/_sage_const_2 ]])
def matkey(M): return tuple(M.list())
I3=identity_matrix(K,_sage_const_3 )
elems={matkey(I3):I3}; frontier=[I3]
for _ in range(_sage_const_2000 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for g in [g3,g5]:
            ne=g*e; k=matkey(ne)
            if k not in elems: elems[k]=ne; new.append(ne)
    frontier=new
ELEM=list(elems.values()); assert len(ELEM)==_sage_const_60 
sigma=g3
def cyclic(g):
    H=[I3]; P=g
    while P!=I3: H.append(P); P=P*g
    return H
def conjOp(g):
    gi=g.inverse(); C=matrix(K,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(K,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=g*E*gi; col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
    return C
def fixedBasis_sub(H):
    rows=[]; I9=identity_matrix(K,_sage_const_9 )
    for h in H: rows.append(conjOp(h)-I9)
    big=block_matrix(K,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(K,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker]
Eb=[]
for i in range(_sage_const_3 ):
    for j in range(_sage_const_3 ):
        E=matrix(K,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; Eb.append(E)
def residual(ai,bi,ci):
    A,B,C=Eb[ai],Eb[bi],Eb[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()

# concrete orbit-sum inner product <T_ansatz, A(x)B(x)C> for concrete seed m1
def ansatz_inner(m1, A, B, C):
    val = A.trace()*B.trace()*C.trace()
    m2 = sigma*m1*sigma.inverse(); m3 = sigma*sigma*m1*(sigma.inverse())**_sage_const_2 
    def fr(X,M):
        s=K(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ): s+=X[i,j]*M[i,j]
        return s
    for g in ELEM:
        gi=g.inverse()
        f1=fr(A, g*m1*gi)
        if f1==_sage_const_0 : continue
        f2=fr(B, g*m2*gi)
        if f2==_sage_const_0 : continue
        f3=fr(C, g*m3*gi)
        if f3==_sage_const_0 : continue
        val += f1*f2*f3
    return val

g_ord5=[g for g in ELEM if len(cyclic(g))==_sage_const_5 ][_sage_const_0 ]
H=cyclic(g_ord5); fb=fixedBasis_sub(H); d=len(fb)
print(f"C_5 stab: orbit {_sage_const_60 //len(H)}, rank {_sage_const_1 +_sage_const_60 //len(H)}, fixed dim {d}")

# planted seed m* = fb[0] + 2*fb[1] - fb[2]  (a concrete C_5-fixed seed)
coef_star=[K(_sage_const_1 ),K(_sage_const_2 ),K(-_sage_const_1 )][:d]
mstar=matrix(K,_sage_const_3 ,_sage_const_3 )
for p in range(d): mstar += coef_star[p]*fb[p]
print(f"planted m* (C_5-fixed). matrix rank {mstar.rank()}")

# Build symbolic system against a target functional.
R=PolynomialRing(K, d, [f"x{i}" for i in range(d)]); xs=R.gens()
m1=matrix(R,_sage_const_3 ,_sage_const_3 )
for p in range(d): m1 += xs[p]*fb[p].change_ring(R)
s=sigma.change_ring(R); m2=s*m1*s.inverse(); s2=(sigma*sigma).change_ring(R); m3=s2*m1*s2.inverse()
def frobR(Xc,Ms):
    acc=R(_sage_const_0 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            if Xc[i,j]!=_sage_const_0 : acc += Xc[i,j]*Ms[i,j]
    return acc
gm={}
for gi,gg in enumerate(ELEM):
    gR=gg.change_ring(R); gmi=gR.inverse()
    gm[(gi,_sage_const_0 )]=gR*m1*gmi; gm[(gi,_sage_const_1 )]=gR*m2*gmi; gm[(gi,_sage_const_2 )]=gR*m3*gmi

def build_polys(targetInner):
    polys=[]
    for ai in range(_sage_const_9 ):
        for bi in range(_sage_const_9 ):
            for ci in range(_sage_const_9 ):
                orb=R(_sage_const_0 )
                for gi in range(_sage_const_60 ):
                    la=frobR(Eb[ai],gm[(gi,_sage_const_0 )])
                    if la==_sage_const_0 : continue
                    lb=frobR(Eb[bi],gm[(gi,_sage_const_1 )])
                    if lb==_sage_const_0 : continue
                    lc=frobR(Eb[ci],gm[(gi,_sage_const_2 )])
                    if lc==_sage_const_0 : continue
                    orb += la*lb*lc
                P = orb + (Eb[ai].trace()*Eb[bi].trace()*Eb[ci].trace() - targetInner(ai,bi,ci))
                if P!=_sage_const_0 : polys.append(P)
    return polys

# POSITIVE: target T' = id^3 + orbit(mstar). targetInner = ansatz_inner(mstar).
tprime = {}
def target_prime(ai,bi,ci):
    key=(ai,bi,ci)
    if key not in tprime:
        tprime[key]=ansatz_inner(mstar, Eb[ai],Eb[bi],Eb[ci])
    return tprime[key]
pos_polys = build_polys(target_prime)
Ipos=R.ideal(pos_polys)
# planted x* satisfies every constraint?
xstar={xs[p]: coef_star[p] for p in range(d)}
all_vanish = all(P.subs(xstar)==_sage_const_0  for P in pos_polys)
print(f"\nPOSITIVE control (target T'=id^3+orbit(m*)):")
print(f"  planted x*={[str(c) for c in coef_star]} satisfies all {len(pos_polys)} constraints: {all_vanish}")
gbpos=Ipos.groebner_basis()
unit_pos = (R.one() in Ipos)
print(f"  Groebner unit ideal? {unit_pos}  (expect False => FEASIBLE, planted solution exists)")
if not unit_pos:
    print(f"  dimension {Ipos.dimension()} => SOLUTION-FOUND as required")

# NEGATIVE: target T_MM. targetInner = tr(ABC).
def target_mm(ai,bi,ci):
    return (Eb[ai]*Eb[bi]*Eb[ci]).trace()
neg_polys = build_polys(target_mm)
Ineg=R.ideal(neg_polys)
unit_neg = (R.one() in Ineg)
print(f"\nNEGATIVE control (target T_MM):")
print(f"  Groebner unit ideal? {unit_neg}  (expect True => INFEASIBLE)")
print(f"  planted x* satisfies all T_MM constraints: {all(P.subs(xstar)==_sage_const_0  for P in neg_polys)}  (expect False)")

print("\nVALIDATION:", "PASS (builder discriminates; T_MM INFEASIBLE is trustworthy)"
      if (all_vanish and not unit_pos and unit_neg) else "FAIL -- investigate builder")

