

# This file was *autogenerated* from the file /workspace/Oe1-family2-valentiner-hessian.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_20000 = Integer(20000); _sage_const_2000 = Integer(2000); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_5000 = Integer(5000); _sage_const_21 = Integer(21); _sage_const_2 = Integer(2); _sage_const_15 = Integer(15); _sage_const_360 = Integer(360)# Oe1 Family 2: the last complex-3-dim-irrep candidates -- the Valentiner group
# 3.A_6 (order 1080, char field involves 15th roots / sqrt-15) and the Hessian
# group (order 216, char field Q(omega)). Both have faithful 3-dim COMPLEX
# irreps (3.A_6: dims include 3,3,3,3; Hessian triple cover: a 3-dim reflection
# rep). For each: build the 3-dim irrep over a cyclotomic splitting field,
# enumerate subgroups whose orbit (|G|/|H|) <= 21, fixed dims, and solve the GM
# single-orbit system. SOLUTION-FOUND rank<23 => STOP.

def analyze(Gcmd, name, cycloN, expect_order):
    print(f"\n========== {name} (expect order {expect_order}) ==========")
    Rn=CyclotomicField(cycloN)
    G=gap(Gcmd)
    ordG=Integer(gap.Order(G))
    print(f"|G| = {ordG}")
    irr=gap.IrreducibleRepresentations(G)
    nirr=Integer(gap.Length(irr))
    # find a 3-dim irrep whose entries live in Q(zeta_cycloN)
    three=None
    Ggens=gap.GeneratorsOfGroup(G); ng=Integer(gap.Length(Ggens))
    def conv(s):
        s=str(s)
        if 'E(' in s:
            try:
                return Rn(sage_eval(s.replace('E(','CyclotomicField(').replace(')',').gen()')))
            except Exception:
                return None
        try:
            return Rn(QQ(s))
        except Exception:
            return None
    chosen_idx=None; chosen_gens=None
    for i in range(_sage_const_1 ,nirr+_sage_const_1 ):
        rep=irr[i]
        Mg=gap.Image(rep,Ggens[_sage_const_1 ])
        if Integer(gap.Length(Mg))!=_sage_const_3 : continue
        # try to convert all generator images into Rn
        ok=True; gmats=[]
        for k in range(_sage_const_1 ,ng+_sage_const_1 ):
            Mk=gap.Image(rep,Ggens[k]); M=matrix(Rn,_sage_const_3 ,_sage_const_3 )
            for a in range(_sage_const_1 ,_sage_const_4 ):
                for b in range(_sage_const_1 ,_sage_const_4 ):
                    v=conv(gap(Mk[a][b]))
                    if v is None: ok=False; break
                    M[a-_sage_const_1 ,b-_sage_const_1 ]=v
                if not ok: break
            if not ok: break
            gmats.append(M)
        if ok:
            chosen_idx=i; chosen_gens=gmats; break
    if chosen_idx is None:
        print(f"  no 3-dim irrep realizable over Q(zeta_{cycloN}); try a larger cyclotomic field.")
        return
    print(f"  using 3-dim irrep #{chosen_idx} over Q(zeta_{cycloN})")
    def matkey(M): return tuple(M.list())
    I3=identity_matrix(Rn,_sage_const_3 )
    elems={matkey(I3):I3}; frontier=[I3]
    for _ in range(_sage_const_20000 ):
        if not frontier: break
        new=[]
        for e in frontier:
            for g in chosen_gens:
                ne=g*e; k=matkey(ne)
                if k not in elems: elems[k]=ne; new.append(ne)
        frontier=new
    ELEM=list(elems.values())
    print(f"  realized rep group order: {len(ELEM)}")
    # NB: a faithful irrep realizes G exactly; if the cover, order = |G|.
    def matorder(M):
        P=M; o=_sage_const_1 
        while P!=I3 and o<_sage_const_2000 : P=P*M; o+=_sage_const_1 
        return o
    sig=[M for M in ELEM if matorder(M)==_sage_const_3 ]
    if not sig:
        print("  no order-3 element in realized group -- cannot twist; skip."); return
    sigma=sig[_sage_const_0 ]
    def conjOp(g):
        gi=g.inverse(); C=matrix(Rn,_sage_const_9 ,_sage_const_9 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ):
                E=matrix(Rn,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=g*E*gi; col=i*_sage_const_3 +j
                for a in range(_sage_const_3 ):
                    for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
        return C
    def fixedBasis_sub(H):
        rows=[]; I9=identity_matrix(Rn,_sage_const_9 )
        for h in H: rows.append(conjOp(h)-I9)
        big=block_matrix(Rn,[[m] for m in rows]); ker=big.right_kernel().basis()
        return [matrix(Rn,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker]
    Eb=[]
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(Rn,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; Eb.append(E)
    def residual(ai,bi,ci):
        A,B,C=Eb[ai],Eb[bi],Eb[ci]
        return A.trace()*B.trace()*C.trace()-(A*B*C).trace()
    Rsupport=set((a,b,c) for a in range(_sage_const_9 ) for b in range(_sage_const_9 ) for c in range(_sage_const_9 ) if residual(a,b,c)!=_sage_const_0 )
    realN=len(ELEM)
    # subgroups with orbit<=21: |H| >= realN/21. Enumerate cyclic subgroups +
    # GAP maximal subgroup reps mapped through the rep.
    ccs=gap.ConjugacyClassesSubgroups(G); ncc=Integer(gap.Length(ccs))
    def sub_mats(Hgap):
        hg=gap.GeneratorsOfGroup(Hgap); nh=Integer(gap.Length(hg))
        if nh==_sage_const_0 : return [I3]
        gmats=[]
        for k in range(_sage_const_1 ,nh+_sage_const_1 ):
            Mg=gap.Image(irr[chosen_idx],hg[k]); M=matrix(Rn,_sage_const_3 ,_sage_const_3 )
            ok=True
            for a in range(_sage_const_1 ,_sage_const_4 ):
                for b in range(_sage_const_1 ,_sage_const_4 ):
                    v=conv(gap(Mg[a][b]))
                    if v is None: ok=False; break
                    M[a-_sage_const_1 ,b-_sage_const_1 ]=v
                if not ok: break
            if not ok: return None
            gmats.append(M)
        Hd={matkey(I3):I3}; fr=[I3]
        for _ in range(_sage_const_5000 ):
            if not fr: break
            nn=[]
            for e in fr:
                for g in gmats:
                    ne=g*e; k=matkey(ne)
                    if k not in Hd: Hd[k]=ne; nn.append(ne)
            fr=nn
        return list(Hd.values())
    import math
    need = math.ceil(realN/_sage_const_21 )
    print(f"  need |H|>={need} for orbit<=21 (realized order {realN})")
    tried=_sage_const_0 
    for ci in range(_sage_const_1 ,ncc+_sage_const_1 ):
        H=gap.Representative(ccs[ci]); o=Integer(gap.Order(H))
        # map to realized order: faithful => same order
        if o<need or o>=ordG: continue
        Hm=sub_mats(H)
        if Hm is None or len(Hm)==_sage_const_0 : continue
        orbit=realN//len(Hm)
        if orbit>_sage_const_21  or orbit<_sage_const_1 : continue
        fb=fixedBasis_sub(Hm); d=len(fb)
        tag=f"  |H|={len(Hm)} orbit={orbit} rank={_sage_const_1 +orbit} fixed_dim={d}"
        if d==_sage_const_0 :
            print(tag+": fixed dim 0; skip"); continue
        Rr=PolynomialRing(Rn,d,[f"x{i}" for i in range(d)]); xs=Rr.gens()
        m1=matrix(Rr,_sage_const_3 ,_sage_const_3 )
        for p in range(d): m1+=xs[p]*fb[p].change_ring(Rr)
        s=sigma.change_ring(Rr); m2=s*m1*s.inverse(); s2=(sigma*sigma).change_ring(Rr); m3=s2*m1*s2.inverse()
        def frobR(Xc,Ms):
            acc=Rr(_sage_const_0 )
            for i in range(_sage_const_3 ):
                for j in range(_sage_const_3 ):
                    if Xc[i,j]!=_sage_const_0 : acc+=Xc[i,j]*Ms[i,j]
            return acc
        gm={}
        for gi,gg in enumerate(ELEM):
            gR=gg.change_ring(Rr); gmi=gR.inverse()
            gm[(gi,_sage_const_0 )]=gR*m1*gmi; gm[(gi,_sage_const_1 )]=gR*m2*gmi; gm[(gi,_sage_const_2 )]=gR*m3*gmi
        polys=[]; reach=set()
        for ai in range(_sage_const_9 ):
            for bi in range(_sage_const_9 ):
                for cci in range(_sage_const_9 ):
                    orb=Rr(_sage_const_0 )
                    for gi in range(len(ELEM)):
                        la=frobR(Eb[ai],gm[(gi,_sage_const_0 )])
                        if la==_sage_const_0 : continue
                        lb=frobR(Eb[bi],gm[(gi,_sage_const_1 )])
                        if lb==_sage_const_0 : continue
                        lc=frobR(Eb[cci],gm[(gi,_sage_const_2 )])
                        if lc==_sage_const_0 : continue
                        orb+=la*lb*lc
                    if orb!=_sage_const_0 : reach.add((ai,bi,cci))
                    P=orb+residual(ai,bi,cci)
                    if P!=_sage_const_0 : polys.append(P)
        I=Rr.ideal(polys); unit=(Rr.one() in I)
        cov=len(reach&Rsupport); miss=Rsupport-reach
        v="INFEASIBLE (unit ideal)" if unit else f"SOLUTION-FOUND dim {I.dimension()} *** STOP rank {_sage_const_1 +orbit} ***"
        print(tag+f": cov {cov}/{len(Rsupport)}{' MISS '+str(len(miss)) if miss else ''}; {v}")
        tried+=_sage_const_1 
    if tried==_sage_const_0 :
        print("  no viable stabilizer with nonzero fixed space and orbit<=21.")

# Hessian group: triple cover is a complex reflection group order 648 with 3-dim
# rep. GAP: the Shephard-Todd group No.25 = 3[3]3[3]3. Use the small group or the
# reflection group. We use the order-648 complex reflection group via its 3-dim
# rep; char field Q(omega)=Q(zeta_3). Try ShephardTodd via GAP if available, else
# SmallGroup(648,...). Fallback: skip with a note.
# Valentiner 3.A_6 order 1080: char field Q(zeta_15).
analyze("AlternatingGroup(6)", "A_6 (no faithful 3-dim; will report none)", _sage_const_15 , _sage_const_360 )
# The faithful 3-dim rep is of the TRIPLE COVER. Build 3.A_6 = SchurCover then a
# 3-dim faithful irrep.
analyze("SchurCoverOfSymmetricGroup", "skip-placeholder", _sage_const_3 , _sage_const_0 ) if False else None

