

# This file was *autogenerated* from the file /workspace/Oe1-coverage-configs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12); _sage_const_21 = Integer(21)# Oe1 Family 1: enumerate which TYPE-SETS cover the 137 residual directions, and
# for each covering set find the minimum total orbit size achievable with rank
# <=22. Coverage by a config depends only on the SET of distinct stabilizer types
# present (same-type stacking does not enlarge reach). A config whose type-union
# misses any residual triple is INFEASIBLE (constant generator). Only configs
# whose type-set covers R need the Groebner probe.
#
# Reuse reach sets computed previously by recomputing them here (self-contained).

import json, itertools
K = QuadraticField(_sage_const_3 , names=('r3',)); (r3,) = K._first_ngens(1)
def Mt(rows): return matrix(K, rows)
rho_12=Mt([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); rho_23=Mt([[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
rho_34=Mt([[_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); sigma=Mt([[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
gens={(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 ):rho_12,(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ):rho_23,(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 ):rho_34}
def compose(p,q): return tuple(p[q[i]] for i in range(_sage_const_4 ))
ident=(_sage_const_0 ,_sage_const_1 ,_sage_const_2 ,_sage_const_3 ); elems={ident:identity_matrix(K,_sage_const_3 )}; frontier=[ident]
for _ in range(_sage_const_100 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for gp in gens:
            ne=compose(gp,e)
            if ne not in elems: elems[ne]=gens[gp]*elems[e]; new.append(ne)
    frontier=new
ELEM=list(elems.values())
def conjM(g,X): return g*X*g.transpose()
def rrStarBasis():
    idm=identity_matrix(K,_sage_const_3 ); boxX=diagonal_matrix(K,[_sage_const_1 ,-_sage_const_1 /_sage_const_2 ,-_sage_const_1 /_sage_const_2 ]); boxY=diagonal_matrix(K,[_sage_const_0 ,r3/_sage_const_2 ,-r3/_sage_const_2 ])
    def E(p):
        M=matrix(K,_sage_const_3 ,_sage_const_3 )
        for (i,j,v) in p: M[i,j]=v
        return M
    s1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_1 )]); s2=E([(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); s3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,_sage_const_1 )])
    a1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,-_sage_const_1 )]); a2=E([(_sage_const_0 ,_sage_const_2 ,-_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); a3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,-_sage_const_1 )])
    return [idm,boxX,boxY,s1,s2,s3,a1,a2,a3]
BR=rrStarBasis(); NAMES=["id","box_x","box_y","s1","s2","s3","a1","a2","a3"]
def subgroup(gp):
    H={ident}; fr=[ident]
    while fr:
        nn=[]
        for e in fr:
            for g in gp:
                ne=compose(g,e)
                if ne not in H: H.add(ne); nn.append(ne)
        fr=nn
    return H
def conjOperator(g):
    C=matrix(K,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(K,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=conjM(elems[g],E); col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
    return C
def fixedBasis(gp):
    H=subgroup(gp); rows=[]; I9=identity_matrix(K,_sage_const_9 )
    for h in H: rows.append(conjOperator(h)-I9)
    big=block_matrix(K,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(K,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker], len(H)
S3=[(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ),(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 )]; K4=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_3 ,_sage_const_0 ,_sage_const_1 )]; Z4=[(_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_0 )]
Z3=[(_sage_const_1 ,_sage_const_2 ,_sage_const_0 ,_sage_const_3 )]; Z2t=[(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 )]; Z2d=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 )]
CATALOG=[("S_3",S3,_sage_const_4 ),("K_4",K4,_sage_const_6 ),("Z_4",Z4,_sage_const_6 ),("Z_3",Z3,_sage_const_8 ),("Z_2t",Z2t,_sage_const_12 ),("Z_2d",Z2d,_sage_const_12 )]
def reach_set(gp):
    fb,hord=fixedBasis(gp); d=len(fb)
    R=PolynomialRing(K, d, [f"x{i}" for i in range(d)] if d>_sage_const_0  else ["x0"]); xs=R.gens()
    m1=matrix(R,_sage_const_3 ,_sage_const_3 )
    for p in range(d): m1 += xs[p]*fb[p].change_ring(R)
    s=sigma.change_ring(R); m2=s*m1*s.transpose(); s2=(sigma*sigma).change_ring(R); m3=s2*m1*s2.transpose()
    def frobR(Xc,Ms):
        acc=R(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ):
                if Xc[i,j]!=_sage_const_0 : acc += Xc[i,j]*Ms[i,j]
        return acc
    gm={}
    for gi,g in enumerate(ELEM):
        gR=g.change_ring(R); gm[(gi,_sage_const_0 )]=gR*m1*gR.transpose(); gm[(gi,_sage_const_1 )]=gR*m2*gR.transpose(); gm[(gi,_sage_const_2 )]=gR*m3*gR.transpose()
    reach=set()
    for ai in range(_sage_const_9 ):
        for bi in range(_sage_const_9 ):
            for ci in range(_sage_const_9 ):
                orb=R(_sage_const_0 )
                for gi in range(len(ELEM)):
                    la=frobR(BR[ai],gm[(gi,_sage_const_0 )])
                    if la==_sage_const_0 : continue
                    lb=frobR(BR[bi],gm[(gi,_sage_const_1 )])
                    if lb==_sage_const_0 : continue
                    lc=frobR(BR[ci],gm[(gi,_sage_const_2 )])
                    if lc==_sage_const_0 : continue
                    orb += la*lb*lc
                if orb!=_sage_const_0 : reach.add((ai,bi,ci))
    return reach
def residual(t):
    ai,bi,ci=t; A,B,C=BR[ai],BR[bi],BR[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()

Rsupport=set(t for t in [(a,b,c) for a in range(_sage_const_9 ) for b in range(_sage_const_9 ) for c in range(_sage_const_9 )] if residual(t)!=_sage_const_0 )
reach={}; orbsz={}
for name,g,orb in CATALOG:
    reach[name]=reach_set(g); orbsz[name]=orb

names=[c[_sage_const_0 ] for c in CATALOG]
# All nonempty subsets of distinct types: does the union cover R? min orbit to
# realize that type-set = sum of one orbit of each type in the set (the cheapest
# way to include a type at least once). Multi-orbit-of-a-type only adds rank.
print("type-set                         | covers R? | min_total_orbit | min_rank")
covering=[]
for r in range(_sage_const_1 ,len(names)+_sage_const_1 ):
    for combo in itertools.combinations(names, r):
        u=set().union(*[reach[c] for c in combo])
        covers = Rsupport.issubset(u)
        min_orbit = sum(orbsz[c] for c in combo)
        if covers:
            covering.append((combo,min_orbit))
        if covers and min_orbit<=_sage_const_21 :
            print(f"{'+'.join(combo):32s} | YES       | {min_orbit:2d}              | {1+min_orbit}  <= 22  CANDIDATE")
print()
# Minimum-rank covering type-set overall (ignoring rank cap), to see the wall.
covering.sort(key=lambda x:x[_sage_const_1 ])
print("Cheapest covering type-sets (by min total orbit):")
for combo,mo in covering[:_sage_const_12 ]:
    flag = "  <=21 OK" if mo<=_sage_const_21  else "  > 21 (over budget)"
    print(f"  {'+'.join(combo):32s} min_orbit={mo:2d} rank={1+mo}{flag}")

candidates=[(c,mo) for (c,mo) in covering if mo<=_sage_const_21 ]
print(f"\nNumber of distinct-type-sets that cover R within rank<=22: {len(candidates)}")
if not candidates:
    print("=> NO type-set covers R within rank<=22 => Family 1 PRE-SCREEN-DEAD (coverage wall).")
else:
    print("=> Some type-sets cover R within budget; these need the Groebner probe.")

