

# This file was *autogenerated* from the file /workspace/Oe1-coverage-prescreen.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10)# Oe1 Family 1 STRUCTURAL pre-screen via direction coverage.
#
# Each orbit type H reaches a FIXED set of basis-triple directions (those where
# its symbolic orbit-sum is not identically zero). Stacking multiple orbits of
# the SAME type does NOT enlarge this set -- it only adds parameters in the same
# directions. So a multi-orbit config can satisfy the MM constraints only if the
# UNION of its orbit types' reachable sets covers every triple with nonzero
# required residual (else that triple is a constant generator => unit ideal).
#
# There are 137 nonzero-residual triples (matches Or2's "137 constraint polys").
# Necessary condition for ANY config: union of reachable sets >= the 137.
# We compute reach(H) per catalog type, find the residual-support R (137 triples),
# and report which single types / unions cover R. A config whose union misses
# even one triple in R is INFEASIBLE by a constant generator, regardless of rank.
#
# NOTE: coverage is NECESSARY, not sufficient (covering all directions does not
# mean the nonlinear system is solvable). A config that PASSES coverage still
# needs the Groebner probe. A config that FAILS coverage is provably dead.

import json
K = QuadraticField(_sage_const_3 , names=('r3',)); (r3,) = K._first_ngens(1)
def Mt(rows): return matrix(K, rows)
rho_12=Mt([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); rho_23=Mt([[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
rho_34=Mt([[_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); sigma=Mt([[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
gens={(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 ):rho_12,(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ):rho_23,(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 ):rho_34}
def compose(p,q): return tuple(p[q[i]] for i in range(_sage_const_4 ))
ident=(_sage_const_0 ,_sage_const_1 ,_sage_const_2 ,_sage_const_3 ); elems={ident:identity_matrix(K,_sage_const_3 )}; frontier=[ident]
for _ in range(_sage_const_100 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for gp in gens:
            ne=compose(gp,e)
            if ne not in elems: elems[ne]=gens[gp]*elems[e]; new.append(ne)
    frontier=new
ELEM=list(elems.values())
def conjM(g,X): return g*X*g.transpose()
def rrStarBasis():
    idm=identity_matrix(K,_sage_const_3 ); boxX=diagonal_matrix(K,[_sage_const_1 ,-_sage_const_1 /_sage_const_2 ,-_sage_const_1 /_sage_const_2 ]); boxY=diagonal_matrix(K,[_sage_const_0 ,r3/_sage_const_2 ,-r3/_sage_const_2 ])
    def E(p):
        M=matrix(K,_sage_const_3 ,_sage_const_3 )
        for (i,j,v) in p: M[i,j]=v
        return M
    s1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_1 )]); s2=E([(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); s3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,_sage_const_1 )])
    a1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,-_sage_const_1 )]); a2=E([(_sage_const_0 ,_sage_const_2 ,-_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); a3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,-_sage_const_1 )])
    return [idm,boxX,boxY,s1,s2,s3,a1,a2,a3]
BR=rrStarBasis(); NAMES=["id","box_x","box_y","s1","s2","s3","a1","a2","a3"]
def subgroup(gp):
    H={ident}; fr=[ident]
    while fr:
        nn=[]
        for e in fr:
            for g in gp:
                ne=compose(g,e)
                if ne not in H: H.add(ne); nn.append(ne)
        fr=nn
    return H
def conjOperator(g):
    C=matrix(K,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(K,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=conjM(elems[g],E); col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
    return C
def fixedBasis(gp):
    H=subgroup(gp); rows=[]; I9=identity_matrix(K,_sage_const_9 )
    for h in H: rows.append(conjOperator(h)-I9)
    big=block_matrix(K,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(K,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker], len(H)

S3=[(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ),(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 )]; K4=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_3 ,_sage_const_0 ,_sage_const_1 )]; Z4=[(_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_0 )]
Z3=[(_sage_const_1 ,_sage_const_2 ,_sage_const_0 ,_sage_const_3 )]; Z2t=[(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 )]; Z2d=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 )]
CATALOG=[("S_3",S3,_sage_const_4 ),("K_4",K4,_sage_const_6 ),("Z_4",Z4,_sage_const_6 ),("Z_3",Z3,_sage_const_8 ),("Z_2t",Z2t,_sage_const_12 ),("Z_2d",Z2d,_sage_const_12 )]

def reach_set(gp):
    """Set of triple-indices (ai,bi,ci) where one orbit of this type has a
    NONZERO symbolic orbit-sum (i.e. reachable directions)."""
    fb,hord=fixedBasis(gp); d=len(fb)
    R=PolynomialRing(K, d, [f"x{i}" for i in range(d)] if d>_sage_const_0  else ["x0"])
    xs=R.gens(); m1=matrix(R,_sage_const_3 ,_sage_const_3 )
    for p in range(d): m1 += xs[p]*fb[p].change_ring(R)
    s=sigma.change_ring(R); m2=s*m1*s.transpose(); s2=(sigma*sigma).change_ring(R); m3=s2*m1*s2.transpose()
    def frobR(Xc,Ms):
        acc=R(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ):
                if Xc[i,j]!=_sage_const_0 : acc += Xc[i,j]*Ms[i,j]
        return acc
    gm={}
    for gi,g in enumerate(ELEM):
        gR=g.change_ring(R); gm[(gi,_sage_const_0 )]=gR*m1*gR.transpose(); gm[(gi,_sage_const_1 )]=gR*m2*gR.transpose(); gm[(gi,_sage_const_2 )]=gR*m3*gR.transpose()
    reach=set()
    for ai in range(_sage_const_9 ):
        for bi in range(_sage_const_9 ):
            for ci in range(_sage_const_9 ):
                orb=R(_sage_const_0 )
                for gi in range(len(ELEM)):
                    la=frobR(BR[ai],gm[(gi,_sage_const_0 )])
                    if la==_sage_const_0 : continue
                    lb=frobR(BR[bi],gm[(gi,_sage_const_1 )])
                    if lb==_sage_const_0 : continue
                    lc=frobR(BR[ci],gm[(gi,_sage_const_2 )])
                    if lc==_sage_const_0 : continue
                    orb += la*lb*lc
                if orb!=_sage_const_0 : reach.add((ai,bi,ci))
    return reach, d, hord

def residual(t):
    ai,bi,ci=t; A,B,C=BR[ai],BR[bi],BR[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()

# Residual support R: triples with nonzero MM residual.
Rsupport = set(t for t in [(a,b,c) for a in range(_sage_const_9 ) for b in range(_sage_const_9 ) for c in range(_sage_const_9 )] if residual(t)!=_sage_const_0 )
print(f"Residual support |R| = {len(Rsupport)} (nonzero required residual triples)")

reach={}; dims={}; orbsz={}
for name,g,orb in CATALOG:
    rs,d,hord = reach_set(g)
    reach[name]=rs; dims[name]=d; orbsz[name]=orb
    covered = len(rs & Rsupport)
    print(f"{name:5s} orbit={orb:2d} dim={d}: reaches {len(rs):3d} dirs, covers {covered:3d}/{len(Rsupport)} of R; MISSES {len(Rsupport-rs)}")

# Which residual triples does NO catalog orbit reach? (Union of all reach sets.)
union_all = set().union(*reach.values())
intrinsically_missed = Rsupport - union_all
print(f"\nResidual triples reached by NO catalog orbit: {len(intrinsically_missed)}")
if intrinsically_missed:
    print("  -> even the union of ALL catalog types cannot cover R => Family 1 PRE-SCREEN-DEAD (coverage).")
    for t in sorted(intrinsically_missed)[:_sage_const_10 ]:
        print(f"     missed {t}=({NAMES[t[_sage_const_0 ]]},{NAMES[t[_sage_const_1 ]]},{NAMES[t[_sage_const_2 ]]}) residual={residual(t)}")
else:
    print("  -> union of all catalog types covers R; coverage alone does not kill Family 1.")
    print("     Now check which SPECIFIC configs (rank<=22) cover R.")

