

# This file was *autogenerated* from the file /workspace/Oe1-family3-mincover.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12)# Oe1 Family 3 follow-up: the cheapest-covering list came back EMPTY for the
# decoupled construction. That could mean (a) no type-set covers R even unbounded,
# or (b) the smallest covering rank is just > 21. Pin it down: compute the union
# of ALL decoupled type reach sets (does it cover R?), and the minimum covering
# rank. Also report WHICH 6 residual directions decoupled Z_2t (best single,
# 131/137) misses, and whether ANY decoupled orbit reaches them -- the true wall.

import json, itertools
K = QuadraticField(_sage_const_3 , names=('r3',)); (r3,) = K._first_ngens(1)
def Mt(rows): return matrix(K, rows)
rho_12=Mt([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); rho_23=Mt([[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
rho_34=Mt([[_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); sigma=Mt([[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
gens={(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 ):rho_12,(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ):rho_23,(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 ):rho_34}
def compose(p,q): return tuple(p[q[i]] for i in range(_sage_const_4 ))
ident=(_sage_const_0 ,_sage_const_1 ,_sage_const_2 ,_sage_const_3 ); elems={ident:identity_matrix(K,_sage_const_3 )}; frontier=[ident]
for _ in range(_sage_const_100 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for gp in gens:
            ne=compose(gp,e)
            if ne not in elems: elems[ne]=gens[gp]*elems[e]; new.append(ne)
    frontier=new
ELEM=list(elems.values())
def conjM(g,X): return g*X*g.transpose()
def rrStarBasis():
    idm=identity_matrix(K,_sage_const_3 ); boxX=diagonal_matrix(K,[_sage_const_1 ,-_sage_const_1 /_sage_const_2 ,-_sage_const_1 /_sage_const_2 ]); boxY=diagonal_matrix(K,[_sage_const_0 ,r3/_sage_const_2 ,-r3/_sage_const_2 ])
    def E(p):
        M=matrix(K,_sage_const_3 ,_sage_const_3 )
        for (i,j,v) in p: M[i,j]=v
        return M
    s1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_1 )]); s2=E([(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); s3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,_sage_const_1 )])
    a1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,-_sage_const_1 )]); a2=E([(_sage_const_0 ,_sage_const_2 ,-_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); a3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,-_sage_const_1 )])
    return [idm,boxX,boxY,s1,s2,s3,a1,a2,a3]
BR=rrStarBasis(); NAMES=["id","box_x","box_y","s1","s2","s3","a1","a2","a3"]
def subgroup(gp):
    H={ident}; fr=[ident]
    while fr:
        nn=[]
        for e in fr:
            for g in gp:
                ne=compose(g,e)
                if ne not in H: H.add(ne); nn.append(ne)
        fr=nn
    return H
def conjOperator(g):
    C=matrix(K,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(K,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=conjM(elems[g],E); col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
    return C
def fixedBasis(gp):
    H=subgroup(gp); rows=[]; I9=identity_matrix(K,_sage_const_9 )
    for h in H: rows.append(conjOperator(h)-I9)
    big=block_matrix(K,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(K,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker], len(H)
S3=[(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ),(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 )]; K4=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_3 ,_sage_const_0 ,_sage_const_1 )]; Z4=[(_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_0 )]
Z3=[(_sage_const_1 ,_sage_const_2 ,_sage_const_0 ,_sage_const_3 )]; Z2t=[(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 )]; Z2d=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 )]
CATALOG=[("S_3",S3,_sage_const_4 ),("K_4",K4,_sage_const_6 ),("Z_4",Z4,_sage_const_6 ),("Z_3",Z3,_sage_const_8 ),("Z_2t",Z2t,_sage_const_12 ),("Z_2d",Z2d,_sage_const_12 )]
def residual(t):
    ai,bi,ci=t; A,B,C=BR[ai],BR[bi],BR[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()
Rsupport=set(t for t in [(a,b,c) for a in range(_sage_const_9 ) for b in range(_sage_const_9 ) for c in range(_sage_const_9 )] if residual(t)!=_sage_const_0 )
def decoupled_reach(gp):
    fb,hord=fixedBasis(gp); d=len(fb)
    R=PolynomialRing(K, _sage_const_3 *d, [f"x{i}" for i in range(d)]+[f"y{i}" for i in range(d)]+[f"z{i}" for i in range(d)] if d>_sage_const_0  else ["x0"])
    g=R.gens()
    def seed(off):
        M=matrix(R,_sage_const_3 ,_sage_const_3 )
        for p in range(d): M += g[off+p]*fb[p].change_ring(R)
        return M
    m1=seed(_sage_const_0 ); m2=seed(d); m3=seed(_sage_const_2 *d)
    def frobR(Xc,Ms):
        acc=R(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ):
                if Xc[i,j]!=_sage_const_0 : acc += Xc[i,j]*Ms[i,j]
        return acc
    gm={}
    for gi,gg in enumerate(ELEM):
        gR=gg.change_ring(R)
        gm[(gi,_sage_const_0 )]=gR*m1*gR.transpose(); gm[(gi,_sage_const_1 )]=gR*m2*gR.transpose(); gm[(gi,_sage_const_2 )]=gR*m3*gR.transpose()
    reach=set()
    for ai in range(_sage_const_9 ):
        for bi in range(_sage_const_9 ):
            for ci in range(_sage_const_9 ):
                orb=R(_sage_const_0 )
                for gi in range(len(ELEM)):
                    la=frobR(BR[ai],gm[(gi,_sage_const_0 )])
                    if la==_sage_const_0 : continue
                    lb=frobR(BR[bi],gm[(gi,_sage_const_1 )])
                    if lb==_sage_const_0 : continue
                    lc=frobR(BR[ci],gm[(gi,_sage_const_2 )])
                    if lc==_sage_const_0 : continue
                    orb += la*lb*lc
                if orb!=_sage_const_0 : reach.add((ai,bi,ci))
    return reach
dec={}; orbsz={}
for name,gp,orb in CATALOG:
    dec[name]=decoupled_reach(gp); orbsz[name]=orb

union_all=set().union(*dec.values())
print(f"Union of ALL decoupled type reach sets covers R: {Rsupport.issubset(union_all)}")
missed_by_all = Rsupport - union_all
print(f"Residual dirs reached by NO decoupled catalog orbit: {len(missed_by_all)}")
for t in sorted(missed_by_all)[:_sage_const_12 ]:
    print(f"   {t}=({NAMES[t[_sage_const_0 ]]},{NAMES[t[_sage_const_1 ]]},{NAMES[t[_sage_const_2 ]]}) residual={residual(t)}")

# minimum covering rank over distinct-type-sets (unbounded)
names=[c[_sage_const_0 ] for c in CATALOG]; covering=[]
for r in range(_sage_const_1 ,len(names)+_sage_const_1 ):
    for combo in itertools.combinations(names,r):
        u=set().union(*[dec[c] for c in combo])
        if Rsupport.issubset(u): covering.append((combo,sum(orbsz[c] for c in combo)))
covering.sort(key=lambda x:x[_sage_const_1 ])
if covering:
    print(f"\nMinimum covering type-set: {'+'.join(covering[_sage_const_0 ][_sage_const_0 ])} total orbit {covering[_sage_const_0 ][_sage_const_1 ]} rank {_sage_const_1 +covering[_sage_const_0 ][_sage_const_1 ]}")
else:
    print("\nNO distinct-type-set covers R, even unbounded (decoupled).")

# What does Z_2t miss, and does anything reach those 6?
miss_z2t = Rsupport - dec["Z_2t"]
print(f"\nDecoupled Z_2t (131/137) misses {len(miss_z2t)} residual dirs:")
for t in sorted(miss_z2t):
    reachers=[nm for nm in names if t in dec[nm]]
    print(f"   {t}=({NAMES[t[_sage_const_0 ]]},{NAMES[t[_sage_const_1 ]]},{NAMES[t[_sage_const_2 ]]}) residual={residual(t)} reached by: {reachers}")

