

# This file was *autogenerated* from the file /workspace/Oe1-family3-antisym-check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_27 = Integer(27); _sage_const_18 = Integer(18)# Oe1: verify the 6 antisymmetric directions (a1,a2,a3)-permutations are
# reachable by the FULL (H={e}, 9-dim) seed, both twisted and decoupled. If yes,
# the wall that kills restricted-symmetry orbits is purely a RESTRICTION effect
# (small H => fixed seed space too small to reach (a1,a2,a3)), consistent with
# GM's full-orbit rank-25 success -- NOT a contradiction. This pins the
# representation-theoretic story: rho'^{(x)3} contains the diagonal trivial in
# the totally-antisymmetric component, which only an UNRESTRICTED seed populates.
#
# Also: confirm the twisted H={e} reaches all 6 (matches the earlier finding that
# H={e} twisted leaves 592 obstructed, ALL with zero residual => it reaches every
# nonzero-residual direction including these antisymmetric ones).

K = QuadraticField(_sage_const_3 , names=('r3',)); (r3,) = K._first_ngens(1)
def Mt(rows): return matrix(K, rows)
rho_12=Mt([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); rho_23=Mt([[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
rho_34=Mt([[_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); sigma=Mt([[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
gens={(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 ):rho_12,(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ):rho_23,(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 ):rho_34}
def compose(p,q): return tuple(p[q[i]] for i in range(_sage_const_4 ))
ident=(_sage_const_0 ,_sage_const_1 ,_sage_const_2 ,_sage_const_3 ); elems={ident:identity_matrix(K,_sage_const_3 )}; frontier=[ident]
for _ in range(_sage_const_100 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for gp in gens:
            ne=compose(gp,e)
            if ne not in elems: elems[ne]=gens[gp]*elems[e]; new.append(ne)
    frontier=new
ELEM=list(elems.values())
def rrStarBasis():
    idm=identity_matrix(K,_sage_const_3 ); boxX=diagonal_matrix(K,[_sage_const_1 ,-_sage_const_1 /_sage_const_2 ,-_sage_const_1 /_sage_const_2 ]); boxY=diagonal_matrix(K,[_sage_const_0 ,r3/_sage_const_2 ,-r3/_sage_const_2 ])
    def E(p):
        M=matrix(K,_sage_const_3 ,_sage_const_3 )
        for (i,j,v) in p: M[i,j]=v
        return M
    s1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_1 )]); s2=E([(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); s3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,_sage_const_1 )])
    a1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,-_sage_const_1 )]); a2=E([(_sage_const_0 ,_sage_const_2 ,-_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); a3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,-_sage_const_1 )])
    return [idm,boxX,boxY,s1,s2,s3,a1,a2,a3]
BR=rrStarBasis(); NAMES=["id","box_x","box_y","s1","s2","s3","a1","a2","a3"]
ANTI=[(_sage_const_6 ,_sage_const_7 ,_sage_const_8 ),(_sage_const_6 ,_sage_const_8 ,_sage_const_7 ),(_sage_const_7 ,_sage_const_6 ,_sage_const_8 ),(_sage_const_7 ,_sage_const_8 ,_sage_const_6 ),(_sage_const_8 ,_sage_const_6 ,_sage_const_7 ),(_sage_const_8 ,_sage_const_7 ,_sage_const_6 )]

def frobR(Xc,Ms,R):
    acc=R(_sage_const_0 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            if Xc[i,j]!=_sage_const_0 : acc += Xc[i,j]*Ms[i,j]
    return acc

def full_twisted_on(ai,bi,ci):
    R=PolynomialRing(K,_sage_const_9 ,[f"x{k}" for k in range(_sage_const_9 )]); xs=R.gens()
    m1=matrix(R,_sage_const_3 ,_sage_const_3 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ): m1[i,j]=xs[i*_sage_const_3 +j]
    s=sigma.change_ring(R); m2=s*m1*s.transpose(); s2=(sigma*sigma).change_ring(R); m3=s2*m1*s2.transpose()
    orb=R(_sage_const_0 )
    for gg in ELEM:
        gR=gg.change_ring(R)
        la=frobR(BR[ai],gR*m1*gR.transpose(),R)
        if la==_sage_const_0 : continue
        lb=frobR(BR[bi],gR*m2*gR.transpose(),R)
        if lb==_sage_const_0 : continue
        lc=frobR(BR[ci],gR*m3*gR.transpose(),R)
        if lc==_sage_const_0 : continue
        orb += la*lb*lc
    return orb

def full_decoupled_on(ai,bi,ci):
    R=PolynomialRing(K,_sage_const_27 ,[f"x{k}" for k in range(_sage_const_9 )]+[f"y{k}" for k in range(_sage_const_9 )]+[f"z{k}" for k in range(_sage_const_9 )]); g=R.gens()
    def seed(off):
        M=matrix(R,_sage_const_3 ,_sage_const_3 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ): M[i,j]=g[off+i*_sage_const_3 +j]
        return M
    m1=seed(_sage_const_0 ); m2=seed(_sage_const_9 ); m3=seed(_sage_const_18 )
    orb=R(_sage_const_0 )
    for gg in ELEM:
        gR=gg.change_ring(R)
        la=frobR(BR[ai],gR*m1*gR.transpose(),R)
        if la==_sage_const_0 : continue
        lb=frobR(BR[bi],gR*m2*gR.transpose(),R)
        if lb==_sage_const_0 : continue
        lc=frobR(BR[ci],gR*m3*gR.transpose(),R)
        if lc==_sage_const_0 : continue
        orb += la*lb*lc
    return orb

print("Antisymmetric directions reachable by the FULL (H={e}) seed?")
print("triple            | twisted_full | decoupled_full")
for (ai,bi,ci) in ANTI:
    tw = full_twisted_on(ai,bi,ci)
    dc = full_decoupled_on(ai,bi,ci)
    print(f"({NAMES[ai]},{NAMES[bi]},{NAMES[ci]})  | {'REACHES' if tw!=_sage_const_0  else 'zero':12s} | {'REACHES' if dc!=0 else 'zero'}")
print()
print("If twisted_full REACHES all 6 => GM's full-orbit construction DOES populate")
print("the antisymmetric directions; the restricted (catalog-H) failure is purely")
print("a RANK/RESTRICTION effect, fully consistent with GM rank-25 success.")

