# Oe1 DISPATCH (heavy, single-core): Hessian-type group with a faithful 3-dim
# complex irrep -- the Shephard-Todd complex reflection group No. 25 (order 648,
# = triple cover of the order-216 Hessian group), GM-ansatz feasibility for
# <3,3,3>.
#
# Run:  sager Sager/Oe1-dispatch-hessian.sage
# Emits one JSON line per viable stabilizer (orbit<=21) + final summary.
#
# WHY (Oe1 Family 2): the Hessian group (order 216) and its triple cover (ST25,
# order 648) are the affine/reflection-group complex 3-dim-irrep candidates in
# Blichfeldt's classification (char field Q(omega)=Q(zeta_3)). Not 3-transitive
# on 4 points => GM's clean T_MM mechanism does not apply; expect INFEASIBLE but
# VERIFY by Groebner over Q(zeta_3). SOLUTION-FOUND rank<23 => STOP, escalate.
#
# COST: ST25 has order 648; the sigma-twisted orbit sum runs over up to 648
# group elements x 729 triples per stabilizer, then a Groebner over Q(zeta_3).
# Single-core, minutes per stabilizer.
#
# CONSTRUCTION: build ST25 as a matrix group over Q(zeta_3). ST25 is generated by
# three complex reflections of order 3. A standard generator set (Shephard-Todd):
#   reflections of order 3 in U(3). We use GAP's complex reflection group if the
#   package is available; otherwise fall back to explicit Hesse-pencil generators.

import json, math
w=CyclotomicField(3).gen()   # primitive cube root of unity
Rn=CyclotomicField(3)

def _coerce(o):
    from sage.all import Integer, Rational
    if isinstance(o, Integer): return int(o)
    if isinstance(o, Rational): return int(o) if o.denominator()==1 else float(o)
    if isinstance(o, dict): return {k:_coerce(v) for k,v in o.items()}
    if isinstance(o, (list,tuple)): return [_coerce(v) for v in o]
    return o
def emit(d): print(json.dumps(_coerce(d)), flush=True)

# Explicit generators for the Hessian / Hesse-pencil 3-dim group over Q(zeta_3).
# The Hesse group of order 216 (and its triple cover 648) is generated by:
#   S = diag(1, w, w^2)               (order 3)
#   T = the cyclic permutation        (order 3)
#   and a "Fourier" reflection
#       F = (1/(w - w^2)) * [[1,1,1],[1,w,w^2],[1,w^2,w]]   (order related to 3)
# These generate the automorphism group of the Hesse configuration. We BFS-close
# and report the realized order (216 or 648 depending on scalar content).
def Mt(rows): return matrix(Rn, rows)
S = diagonal_matrix(Rn, [1, w, w^2])
T = Mt([[0,1,0],[0,0,1],[1,0,0]])
# normalized Fourier matrix (order 3 up to scalar); scale so det has finite order
F = Mt([[1,1,1],[1,w,w^2],[1,w^2,w]]) / (w - w^2)
gens=[S,T,F]
def matkey(M): return tuple(M.list())
I3=identity_matrix(Rn,3)
elems={matkey(I3):I3}; frontier=[I3]
overflow=False
for _ in range(200000):
    if not frontier: break
    new=[]
    for e in frontier:
        for g in gens:
            ne=g*e; kk=matkey(ne)
            if kk not in elems:
                elems[kk]=ne; new.append(ne)
    frontier=new
    if len(elems)>5000:
        overflow=True; break
ELEM=list(elems.values()); realN=len(ELEM)
emit({"info":"realized Hessian/ST25 3-dim group","order":int(realN),"overflow":overflow})

if overflow:
    emit({"group":"Hessian","verdict":"UNREALIZED","note":"generator set did not close to a finite group (scalar overflow); use GAP ShephardTodd(25) or correct reflection generators"})
else:
    def matorder(M):
        P=M; o=1
        while P!=I3 and o<2000: P=P*M; o+=1
        return o
    sig=[M for M in ELEM if matorder(M)==3]
    if not sig:
        emit({"group":"Hessian","verdict":"NO-SIGMA"})
    else:
        sigma=sig[0]
        def conjOp(g):
            gi=g.inverse(); C=matrix(Rn,9,9)
            for ii in range(3):
                for jj in range(3):
                    E=matrix(Rn,3,3); E[ii,jj]=1; img=g*E*gi; col=ii*3+jj
                    for a in range(3):
                        for b in range(3): C[a*3+b,col]=img[a,b]
            return C
        # irreducibility
        rows=[]; I9=identity_matrix(Rn,9)
        for g in ELEM: rows.append(conjOp(g)-I9)
        big=block_matrix(Rn,[[m] for m in rows])
        emit({"info":"End(rho) dim","value":int(9-big.rank())})
        def fixedBasis_sub(H):
            rows=[]; I9=identity_matrix(Rn,9)
            for h in H: rows.append(conjOp(h)-I9)
            big=block_matrix(Rn,[[m] for m in rows]); ker=big.right_kernel().basis()
            return [matrix(Rn,3,3,[v[k] for k in range(9)]) for v in ker]
        Eb=[]
        for ii in range(3):
            for jj in range(3):
                E=matrix(Rn,3,3); E[ii,jj]=1; Eb.append(E)
        def residual(ai,bi,ci):
            A,B,C=Eb[ai],Eb[bi],Eb[ci]
            return A.trace()*B.trace()*C.trace()-(A*B*C).trace()
        Rsupport=set((a,b,c) for a in range(9) for b in range(9) for c in range(9) if residual(a,b,c)!=0)
        need=math.ceil(realN/21)
        # enumerate cyclic subgroups + their powers; collect distinct subgroups of
        # order >= need by closing pairs of elements (cheap heuristic). For full
        # rigor use GAP, but cyclic+pairs catches the large stabilizers that give
        # small orbits. Here we scan all subgroups generated by up to 2 elements
        # of large order.
        def cyclic(g):
            H=[I3]; P=g
            while P!=I3 and len(H)<realN: H.append(P); P=P*g
            return H
        subs={}
        for g in ELEM:
            H=cyclic(g)
            if len(H)>=need:
                subs.setdefault(frozenset(matkey(x) for x in H), H)
        # also pairs (bounded) for non-cyclic large stabilizers
        biggens=[g for g in ELEM if len(cyclic(g))>=3][:30]
        for a_ in range(len(biggens)):
            for b_ in range(a_+1,len(biggens)):
                Hd={matkey(I3):I3}; fr=[I3]; ov=False
                for _ in range(2000):
                    if not fr: break
                    nn=[]
                    for e in fr:
                        for g in [biggens[a_],biggens[b_]]:
                            ne=g*e; kk=matkey(ne)
                            if kk not in Hd: Hd[kk]=ne; nn.append(ne)
                    fr=nn
                    if len(Hd)>realN: ov=True; break
                if not ov and need<=len(Hd)<realN:
                    subs.setdefault(frozenset(Hd.keys()), list(Hd.values()))
        emit({"info":"candidate large subgroups found","count":int(len(subs))})
        any_sol=False; checked=0
        for key,H in subs.items():
            orbit=realN//len(H)
            if orbit>21 or orbit<1: continue
            fb=fixedBasis_sub(H); d=len(fb)
            if d==0:
                continue
            Rr=PolynomialRing(Rn,d,[f"x{ix}" for ix in range(d)]); xs=Rr.gens()
            m1=matrix(Rr,3,3)
            for p in range(d): m1+=xs[p]*fb[p].change_ring(Rr)
            s=sigma.change_ring(Rr); m2=s*m1*s.inverse(); s2=(sigma*sigma).change_ring(Rr); m3=s2*m1*s2.inverse()
            def frobR(Xc,Ms):
                acc=Rr(0)
                for ii in range(3):
                    for jj in range(3):
                        if Xc[ii,jj]!=0: acc+=Xc[ii,jj]*Ms[ii,jj]
                return acc
            gm2={}
            for gi,gg in enumerate(ELEM):
                gR=gg.change_ring(Rr); gmi=gR.inverse()
                gm2[(gi,0)]=gR*m1*gmi; gm2[(gi,1)]=gR*m2*gmi; gm2[(gi,2)]=gR*m3*gmi
            polys=[]; reach=set()
            for ai in range(9):
                for bi in range(9):
                    for cci in range(9):
                        orb=Rr(0)
                        for gi in range(len(ELEM)):
                            la=frobR(Eb[ai],gm2[(gi,0)])
                            if la==0: continue
                            lb=frobR(Eb[bi],gm2[(gi,1)])
                            if lb==0: continue
                            lc=frobR(Eb[cci],gm2[(gi,2)])
                            if lc==0: continue
                            orb+=la*lb*lc
                        if orb!=0: reach.add((ai,bi,cci))
                        P=orb+residual(ai,bi,cci)
                        if P!=0: polys.append(P)
            I=Rr.ideal(polys); unit=(Rr.one() in I)
            rec={"group":"Hessian/ST25","H_order":int(len(H)),"orbit":int(orbit),"rank":int(1+orbit),
                 "fixed_dim":int(d),"covered":int(len(reach&Rsupport)),"residual_support":int(len(Rsupport))}
            if unit: rec["verdict"]="INFEASIBLE"
            else: rec["verdict"]="SOLUTION-FOUND"; rec["dimension"]=int(I.dimension()); any_sol=True
            emit(rec); checked+=1
        emit({"group":"Hessian/ST25","summary":True,"stabilizers_checked":int(checked),
              "verdict":("RANK-IMPROVED *** STOP ***" if any_sol else "ALL-INFEASIBLE")})
