

# This file was *autogenerated* from the file /workspace/Oe1-family1-reach.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12)# Oe1 Family 1 refinement: WHICH catalog orbit types reach the canonical
# box-box / rho'-rho' killer directions, and what does the 2-orbit Groebner
# verdict (all INFEASIBLE) actually imply for >=3 orbits?
#
# The naive "common obstructed intersection" gave 0 killers -- meaning some
# orbit reaches (id,box_x,box_x). But Or2 found ALL 18 two-orbit pairs
# INFEASIBLE via global Groebner. So the obstruction is not a single constant
# generator on a commonly-obstructed triple; it is a global incompatibility.
#
# Here we (1) report, per catalog orbit, whether the canonical box-box triple
# (0,1,1) and the canonical rho'-rho' triple are obstructed, and (2) for the
# box-box direction, show the actual orbit-sum polynomial each orbit produces
# there -- so we can see whether a 3rd orbit adds an INDEPENDENT direction or
# is linearly dependent on what 2 orbits already provide.

import json
K = QuadraticField(_sage_const_3 , names=('r3',)); (r3,) = K._first_ngens(1)
def Mt(rows): return matrix(K, rows)
rho_12 = Mt([[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); rho_23 = Mt([[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
rho_34 = Mt([[_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]]); sigma = Mt([[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
gens = {(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 ): rho_12, (_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ): rho_23, (_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 ): rho_34}
def compose(p,q): return tuple(p[q[i]] for i in range(_sage_const_4 ))
ident=(_sage_const_0 ,_sage_const_1 ,_sage_const_2 ,_sage_const_3 ); elems={ident: identity_matrix(K,_sage_const_3 )}; frontier=[ident]
for _ in range(_sage_const_100 ):
    if not frontier: break
    new=[]
    for e in frontier:
        for gp in gens:
            ne=compose(gp,e)
            if ne not in elems: elems[ne]=gens[gp]*elems[e]; new.append(ne)
    frontier=new
ELEM=list(elems.values())
def conjM(g,X): return g*X*g.transpose()
def rrStarBasis():
    idm=identity_matrix(K,_sage_const_3 ); boxX=diagonal_matrix(K,[_sage_const_1 ,-_sage_const_1 /_sage_const_2 ,-_sage_const_1 /_sage_const_2 ]); boxY=diagonal_matrix(K,[_sage_const_0 ,r3/_sage_const_2 ,-r3/_sage_const_2 ])
    def E(p):
        M=matrix(K,_sage_const_3 ,_sage_const_3 )
        for (i,j,v) in p: M[i,j]=v
        return M
    s1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_1 )]); s2=E([(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); s3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,_sage_const_1 )])
    a1=E([(_sage_const_1 ,_sage_const_2 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 ,-_sage_const_1 )]); a2=E([(_sage_const_0 ,_sage_const_2 ,-_sage_const_1 ),(_sage_const_2 ,_sage_const_0 ,_sage_const_1 )]); a3=E([(_sage_const_0 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_0 ,-_sage_const_1 )])
    return [idm,boxX,boxY,s1,s2,s3,a1,a2,a3]
BR=rrStarBasis(); NAMES=["id","box_x","box_y","s1","s2","s3","a1","a2","a3"]
def subgroup(gp):
    H={ident}; fr=[ident]
    while fr:
        nn=[]
        for e in fr:
            for g in gp:
                ne=compose(g,e)
                if ne not in H: H.add(ne); nn.append(ne)
        fr=nn
    return H
def conjOperator(g):
    C=matrix(K,_sage_const_9 ,_sage_const_9 )
    for i in range(_sage_const_3 ):
        for j in range(_sage_const_3 ):
            E=matrix(K,_sage_const_3 ,_sage_const_3 ); E[i,j]=_sage_const_1 ; img=conjM(elems[g],E); col=i*_sage_const_3 +j
            for a in range(_sage_const_3 ):
                for b in range(_sage_const_3 ): C[a*_sage_const_3 +b,col]=img[a,b]
    return C
def fixedBasis(gp):
    H=subgroup(gp); rows=[]; I9=identity_matrix(K,_sage_const_9 )
    for h in H: rows.append(conjOperator(h)-I9)
    big=block_matrix(K,[[m] for m in rows]); ker=big.right_kernel().basis()
    return [matrix(K,_sage_const_3 ,_sage_const_3 ,[v[k] for k in range(_sage_const_9 )]) for v in ker], len(H)
S3=[(_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_3 ),(_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 )]; K4=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_3 ,_sage_const_0 ,_sage_const_1 )]; Z4=[(_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_0 )]
Z3=[(_sage_const_1 ,_sage_const_2 ,_sage_const_0 ,_sage_const_3 )]; Z2t=[(_sage_const_1 ,_sage_const_0 ,_sage_const_2 ,_sage_const_3 )]; Z2d=[(_sage_const_1 ,_sage_const_0 ,_sage_const_3 ,_sage_const_2 )]
CATALOG=[("S_3",S3,_sage_const_4 ),("K_4",K4,_sage_const_6 ),("Z_4",Z4,_sage_const_6 ),("Z_3",Z3,_sage_const_8 ),("Z_2t",Z2t,_sage_const_12 ),("Z_2d",Z2d,_sage_const_12 )]

def orbit_poly_on_triple(gp, ai, bi, ci):
    """Return the symbolic orbit-sum polynomial on (A,B,C) for one orbit with
    stabilizer gp, in its own seed variables."""
    fb,hord=fixedBasis(gp); d=len(fb)
    R=PolynomialRing(K, d, [f"x{i}" for i in range(d)] if d>_sage_const_0  else ["x0"])
    xs=R.gens(); m1=matrix(R,_sage_const_3 ,_sage_const_3 )
    for p in range(d): m1 += xs[p]*fb[p].change_ring(R)
    s=sigma.change_ring(R); m2=s*m1*s.transpose()
    s2=(sigma*sigma).change_ring(R); m3=s2*m1*s2.transpose()
    def frobR(Xc,Ms):
        acc=R(_sage_const_0 )
        for i in range(_sage_const_3 ):
            for j in range(_sage_const_3 ):
                if Xc[i,j]!=_sage_const_0 : acc += Xc[i,j]*Ms[i,j]
        return acc
    orb=R(_sage_const_0 )
    for gi,g in enumerate(ELEM):
        gR=g.change_ring(R)
        gm0=gR*m1*gR.transpose(); gm1=gR*m2*gR.transpose(); gm2=gR*m3*gR.transpose()
        la=frobR(BR[ai],gm0)
        if la==_sage_const_0 : continue
        lb=frobR(BR[bi],gm1)
        if lb==_sage_const_0 : continue
        lc=frobR(BR[ci],gm2)
        if lc==_sage_const_0 : continue
        orb += la*lb*lc
    return orb, d

# The two canonical obstructed directions Or2 named.
canon_box  = (_sage_const_0 ,_sage_const_1 ,_sage_const_1 )   # (id, box_x, box_x)  -- box-box, eq (4box)
# rho'-rho' (antisymmetric): (id, a1, a1) is the natural analogue.
canon_anti = (_sage_const_0 ,_sage_const_6 ,_sage_const_6 )   # (id, a1, a1)

def residual(t):
    ai,bi,ci=t; A,B,C=BR[ai],BR[bi],BR[ci]
    return A.trace()*B.trace()*C.trace()-(A*B*C).trace()

for label,trip in [("box-box (id,box_x,box_x)",canon_box),("rho'-rho' (id,a1,a1)",canon_anti)]:
    print(f"=== {label} idx={trip}, residual={residual(trip)} ===")
    for name,g,orb in CATALOG:
        poly,d = orbit_poly_on_triple(g, *trip)
        zero = (poly==_sage_const_0 )
        print(f"  {name:5s} (dim {d}): orbit poly {'IDENTICALLY ZERO' if zero else 'NONZERO: '+str(poly)}")
    print()

