import GroupCount.Gnu

/-!
# Dennis's gnu-surjectivity conjecture (OEIS A046057)

`GroupCount.gnu m` is the number of groups of order `m` up to isomorphism (OEIS
A000001; certified layer: `GroupCount/Gnu.lean`).  This file archives **R. Keith
Dennis's conjecture** that every positive integer occurs as a value of `gnu`,
together with the sorry-free realization layer certifiable today.

## The conjecture (the file's single intended `sorry`)

OEIS A046057 (pulled live with `oeis show A046057`) is "Smallest order m > 0 for
which there are n nonisomorphic finite groups of order m, or 0 if no such order
exists", with terms (offset 1) `1, 4, 75, 28, 8, 42, 375, 510, 308, 90, 140, 88,
56, 16, 24, 100, …` and keyword `hard`.  (The offset is cross-checked against the
*live A000001 entry*: its terms give `gnu 8 = 5` and `gnu 16 = 14`, matching
`a(5) = 8` and `a(14) = 16` — neither value is certified by `GroupCount/Gnu.lean`,
so this is entry-to-entry consistency, not a certified-layer check — plus the
entry's comment `a(33) > 30500` against its 32 listed terms.)  The entry's first comment is the archived claim: **"R. Keith Dennis
conjectures that there are no 0's in this sequence"** — every `1 ≤ n` is the
number of groups of some order.  `GroupCount.dennis_gnu_surjective` states
exactly that, `∀ n, 1 ≤ n → ∃ m, gnu m = n`, and carries the file's single
intended `sorry`.  The OEIS side condition "order m > 0" costs nothing: the junk
value is pinned upstream (`GroupCount.gnu_zero`, `GroupCount.gnu_eq_zero_iff`),
so any witness for `1 ≤ n` is automatically a positive order
(`GroupCount.one_le_of_one_le_gnu`).

In Conway–Dietrich–O'Brien, *Counting groups: gnus, moas and other exotica*
(2008), A046057(n) is the "minimal order attaining n", denoted `moa(n)` (so
recorded on the entry by Daniel Forgues, Feb 15 2017) — hence the `moa_*` names
below.

## The companion A053403 (prose only, not formalized)

A053403 (`oeis show A053403`) considers "the set P of pairs (a,b) generated by
the rules: (1,1) is in P; if (a,b) is in P then (b,a+b) is in P; if (a,b) and
(a',b') are in P then (aa', bb') is in P" and lists the numbers not appearing in
P: `7, 11, 19, 29, 31, 47, 49, 53, …`.  Its comment carries the quantitative
evidence for Dennis's conjecture: the sequence "has 508 known terms, the largest
of which is 55487.  Conjecturally it is finite.  If it is and 55487 is the
largest term, then the function the number of groups of order n takes on all
positive integers as values."  The inductive pair-closure `P` and its bridge to
gnu-realizations (implicit constructions the entry does not state) are a genuine
formalization project of their own and are **not** attempted here.

## Certified (sorry-free) realization layer

Within the trust policy of `GroupCount/Gnu.lean` (zero `native_decide`; kernel
`decide` on exact `gnu` values stops at `n = 2`; classification proofs carry
`gnu 3` and `gnu 4`), exactly the instances `n = 1` and `n = 2` of the
conjecture are realizable today, and the corresponding A046057 entries can be
pinned *exactly* — value and minimality:

* `GroupCount.exists_gnu_eq_one`, `GroupCount.exists_gnu_eq_two` — the
  instances `n = 1` (witness `m = 1`) and `n = 2` (witness `m = 4`) of the
  conjecture; these double as its satisfiability witnesses.
* `GroupCount.moa_one` — **A046057(1) = 1**: `gnu 1 = 1`, and no `m < 1` has
  `gnu m = 1`.
* `GroupCount.moa_two` — **A046057(2) = 4**: `gnu 4 = 2`, and no `m < 4` has
  `gnu m = 2` (from the certified `gnu 0 = 0`, `gnu 1 = gnu 2 = gnu 3 = 1`).
* `GroupCount.isLeast_gnu_eq_one`, `GroupCount.isLeast_gnu_eq_two` — the same
  pinned facts in Mathlib-normal spelling, as `IsLeast` of the realization sets.
* `GroupCount.one_le_of_one_le_gnu` — an order realizing a positive value is
  positive (converse of `GroupCount.one_le_gnu`).

No totalized "A046057 function" (`smallest m, or 0 if none`) is defined: its `0`
branch is exactly the junk-value trap the statements above avoid by pinning each
sequence entry as a value-plus-minimality fact.  A046057(3) = 75 is out of
reach of this layer: pinning it needs `gnu` certified at every order up to `75`
(in particular `gnu 75 = 3`), far past both the kernel wall and the
classifications carried by `GroupCount/Gnu.lean`.

## Axiom audit

`dennis_gnu_surjective` carries the single intended `sorry` and reports
`sorryAx` by construction.  Every other declaration reports a subset of
`{propext, Classical.choice, Quot.sound}`.  The subset check is an *allowlist*
and is the sound detector for `native_decide`: on this toolchain a use surfaces
as a per-declaration `<decl>._native.native_decide.ax_*` axiom (`Lean.ofReduceBool`
is never emitted), so any use would break the subset.  There is no `native_decide`
in this file; the one anonymous disclosed example upstream
(`GroupCount/Structures.lean`, ground-truth section) persists no constant and
taints no theorem here.
-/

set_option autoImplicit false

namespace GroupCount

/-! ## Witness positivity: the OEIS "order m > 0" side condition is automatic -/

/-- An order realizing a positive `gnu` value is positive: `1 ≤ gnu m → 1 ≤ m`.
This is why `GroupCount.dennis_gnu_surjective` may say `∃ m, gnu m = n` with no
explicit `1 ≤ m` guard: for `1 ≤ n` any witness avoids the junk order `0`
(`GroupCount.gnu_zero`), so the "order m > 0" of the A046057 name is not
dropped.  Converse of `GroupCount.one_le_gnu`. -/
theorem one_le_of_one_le_gnu {m : ℕ} (h : 1 ≤ gnu m) : 1 ≤ m := by
  rcases Nat.eq_zero_or_pos m with rfl | hm
  · rw [gnu_zero] at h
    omega
  · exact hm

/-! ## The archived conjecture (OPEN, the file's single intended `sorry`) -/

/-- **Dennis's gnu-surjectivity conjecture** — OEIS A046057, first comment
(pulled live): "R. Keith Dennis conjectures that there are no 0's in this
sequence", the sequence being "Smallest order m > 0 for which there are n
nonisomorphic finite groups of order m, or 0 if no such order exists."
Equivalently: every positive integer is the number of groups of some order —
`gnu` is surjective onto the positive integers.  **OPEN**; this is the file's
single intended `sorry`.

Status, per the live entries:

* realized sorry-free in this file: `n = 1` (`GroupCount.exists_gnu_eq_one`)
  and `n = 2` (`GroupCount.exists_gnu_eq_two`);
* the companion A053403 records the search evidence (see the module docstring):
  conjecturally only finitely many candidate values are unaccounted for — 508
  known, the largest being `55487` — and if `55487` really is the largest, `gnu`
  takes all positive integer values;
* A046057 carries keyword `hard`, and even single values are open:
  `a(33) > 30500` (Muniru A Asiru's comment on the entry).

The hypothesis `1 ≤ n` restricts to the intended domain: `n = 0` is realized
only by the junk order `0` (`gnu 0 = 0`; see the ground-truth section), which
the OEIS name excludes by "order m > 0".  No `1 ≤ m` guard is needed on the
witness: by `GroupCount.one_le_of_one_le_gnu` any witness for `1 ≤ n` is
automatically positive. -/
theorem dennis_gnu_surjective (n : ℕ) (hn : 1 ≤ n) : ∃ m : ℕ, gnu m = n := by
  -- intended sorry: open conjecture (card A046057-dennis-surjectivity).
  -- ROUTE: the literature realizes values through Hölder-type classification
  -- formulas for gnu at orders p·q^k; none of those classifications is
  -- formalized here, and no proof of the full conjecture is known to anyone.
  sorry

/-! ## Sorry-free realization layer -/

/-- The instance `n = 1` of `GroupCount.dennis_gnu_surjective`, sorry-free: the
trivial group is the only group of order `1` (`GroupCount.gnu_one`). -/
theorem exists_gnu_eq_one : ∃ m : ℕ, gnu m = 1 := ⟨1, gnu_one⟩

/-- The instance `n = 2` of `GroupCount.dennis_gnu_surjective`, sorry-free:
`C₄` and the Klein four-group are the two groups of order `4`
(`GroupCount.gnu_four` — a classification proof, not a compiled evaluation). -/
theorem exists_gnu_eq_two : ∃ m : ℕ, gnu m = 2 := ⟨4, gnu_four⟩

/-! ## The pinned A046057 values: smallest witnesses -/

/-- **A046057(1) = 1** (`moa(1) = 1` in Conway–Dietrich–O'Brien notation): the
smallest order with exactly one group is `1` — `gnu 1 = 1`, and the only
smaller candidate, the junk order `0`, has `gnu 0 = 0`.  Stated directly as
value plus minimality; no "smallest m or 0" totalization of A046057 is
defined.  The minimality conjunct is *degenerate* at this index: `m < 1`
leaves only the junk order `0` (under the OEIS side condition `0 < m` it is
empty); the non-degenerate minimality content of this layer is
`GroupCount.moa_two`. -/
theorem moa_one : gnu 1 = 1 ∧ ∀ m : ℕ, m < 1 → gnu m ≠ 1 := by
  refine ⟨gnu_one, ?_⟩
  intro m hm
  interval_cases m
  rw [gnu_zero]
  omega

/-- **A046057(2) = 4** (`moa(2) = 4`): the smallest order with exactly two
groups is `4` — `gnu 4 = 2` (cyclic versus Klein four), while `gnu 0 = 0` and
`gnu 1 = gnu 2 = gnu 3 = 1`, the certified first terms `0, 1, 1, 1, 2` of
A000001. -/
theorem moa_two : gnu 4 = 2 ∧ ∀ m : ℕ, m < 4 → gnu m ≠ 2 := by
  refine ⟨gnu_four, ?_⟩
  intro m hm
  interval_cases m
  · rw [gnu_zero]; omega
  · rw [gnu_one]; omega
  · rw [gnu_two]; omega
  · rw [gnu_three]; omega

/-- `GroupCount.moa_one` in Mathlib-normal spelling: `1` is the least element
of the realization set `{m | gnu m = 1}` (lower-bound half degenerate — see
`GroupCount.moa_one`). -/
theorem isLeast_gnu_eq_one : IsLeast {m : ℕ | gnu m = 1} 1 := by
  constructor
  · exact gnu_one
  · intro m hm
    by_contra hlt
    exact moa_one.2 m (by omega) hm

/-- `GroupCount.moa_two` in Mathlib-normal spelling: `4` is the least element
of the realization set `{m | gnu m = 2}`. -/
theorem isLeast_gnu_eq_two : IsLeast {m : ℕ | gnu m = 2} 4 := by
  constructor
  · exact gnu_four
  · intro m hm
    by_contra hlt
    exact moa_two.2 m (by omega) hm

/-! ## Ground truth and satisfiability

The realization theorems double as the satisfiability witnesses STYLE demands
for the archived statement: hypothesis and conclusion of
`dennis_gnu_surjective` are jointly instantiated at `n = 1` and `n = 2`, and
every hypothesis-bearing proved declaration above is instantiated at a concrete
model. -/

section GroundTruth

-- the archived statement's shape, hypothesis and conclusion jointly
-- instantiated at the two certifiable values:
example : 1 ≤ 1 ∧ ∃ m : ℕ, gnu m = 1 := ⟨le_refl 1, exists_gnu_eq_one⟩
example : 1 ≤ 2 ∧ ∃ m : ℕ, gnu m = 2 := ⟨one_le_two, exists_gnu_eq_two⟩

-- `n = 0` is realized ONLY by the junk order `0` — the content of the `1 ≤ n`
-- guard and of the OEIS "order m > 0":
example : ∃ m : ℕ, gnu m = 0 := ⟨0, gnu_zero⟩
example : ∀ m : ℕ, gnu m = 0 → m = 0 := fun m h => (gnu_eq_zero_iff m).mp h

-- `one_le_of_one_le_gnu` at a concrete model: its hypothesis is satisfiable
-- (at `m = 4`), and every realization of `n = 2` is a positive order:
example : 1 ≤ gnu 4 := by rw [gnu_four]; omega
example (m : ℕ) (h : gnu m = 2) : 1 ≤ m := one_le_of_one_le_gnu (by rw [h]; omega)

-- the minimality conjunct of `moa_two` is not vacuous: it ranges over the
-- genuine group orders `1, 2, 3` (each with `1 ≤ gnu`), not only the junk `0`:
example : 1 ≤ gnu 3 ∧ gnu 3 ≠ 2 := ⟨one_le_gnu (by omega), moa_two.2 3 (by omega)⟩

-- witnesses are NOT unique — the "smallest" of A046057 (and the `IsLeast`
-- spelling) has content: two distinct orders both realize `n = 1`:
example : ∃ m₁ m₂ : ℕ, m₁ ≠ m₂ ∧ gnu m₁ = 1 ∧ gnu m₂ = 1 :=
  ⟨1, 2, by omega, gnu_one, gnu_two⟩

end GroundTruth

/-! ## Axiom audit

`dennis_gnu_surjective` carries the file's single intended `sorry` and reports
`sorryAx` by construction.  Everything else must report a subset of
`{propext, Classical.choice, Quot.sound}`.  The subset is the sound
`native_decide` detector: a use would appear as a per-declaration
`*._native.native_decide.ax_*` axiom on this toolchain (`Lean.ofReduceBool` is
never emitted, so grepping for it detects nothing). -/

#print axioms one_le_of_one_le_gnu
#print axioms dennis_gnu_surjective
#print axioms exists_gnu_eq_one
#print axioms exists_gnu_eq_two
#print axioms moa_one
#print axioms moa_two
#print axioms isLeast_gnu_eq_one
#print axioms isLeast_gnu_eq_two

end GroupCount
