#!/usr/bin/env sage
"""
decomp_stabilizer.sage — Compute symmetry groups of matmul decompositions.

For a decomposition T = sum_k U[:,k] (x) V[:,k] (x) W[:,k] of the <n,n,n>
matrix multiplication tensor, the symmetry group is the subgroup of the
isotropy group of T that permutes the set of rank-1 terms.

The isotropy group of <n,n,n> is GL(n)^3 / torus acting by sandwich
transforms, extended by the S3 of slot permutations (generated by cyclic
rotation and transpose). An element of the full symmetry group is a slot
symmetry s composed with a sandwich transform (A,B,C), such that the
composition maps the decomposition's column set to itself (up to scalars).

Method:
  For each of the 6 slot symmetries, apply it to get (U_s, V_s, W_s), then
  enumerate signature-compatible permutations sigma and check if sandwich
  matrices (A,B,C) exist.

Usage:
    load("decomp_stabilizer.sage")
    info = compute_stabilizer(U, V, W, n, label="Strassen")
"""

from itertools import permutations as iter_permutations
from collections import Counter
import sys
import time


# ═══════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════

def _col_as_matrix(M, k, n):
    """Reshape column k of M (n^2 x r) as an n x n matrix."""
    return Matrix(M.base_ring(), n, n, [M[i, k] for i in range(n * n)])


def _transpose_perm_matrix(n, F):
    """n^2 x n^2 permutation matrix for (i,j) -> (j,i)."""
    P = Matrix(F, n*n, n*n)
    for i in range(n):
        for j in range(n):
            P[i*n+j, j*n+i] = 1
    return P


# ═══════════════════════════════════════════════════════════════════
# Slot symmetries of <n,n,n>
# ═══════════════════════════════════════════════════════════════════

def apply_slot_symmetry(U, V, W, n, slot_type):
    """
    Apply a slot symmetry to a decomposition.
    Cyclic: trace(XYZ) = trace(YZX), acts as (U,V,W) -> (P*V, P*W, P*U).
    Transpose: trace(XYZ) = trace(Z^T Y^T X^T), acts as (U,V,W) -> (P*W, P*V, P*U).
    P is the (i,j)->(j,i) transpose permutation matrix on n^2 space; P^2 = I.
    """
    F = U.base_ring()
    P = _transpose_perm_matrix(n, F)
    if slot_type == 'id':
        return (U, V, W)
    elif slot_type == 'cyc':
        return (P * V, P * W, P * U)
    elif slot_type == 'cyc2':
        return (P * W, P * U, P * V)
    elif slot_type == 'tr':
        return (P * W, P * V, P * U)
    elif slot_type == 'tr_cyc':
        # tr . cyc: first cyc: (P*V, P*W, P*U), then tr on result:
        # tr(X,Y,Z) = (P*Z, P*Y, P*X), so tr(P*V, P*W, P*U) = (P*P*U, P*P*W, P*P*V) = (U, W, V)
        return (U, W, V)
    elif slot_type == 'tr_cyc2':
        # tr . cyc^2: first cyc^2: (P*W, P*U, P*V), then tr:
        # tr(P*W, P*U, P*V) = (P*P*V, P*P*U, P*P*W) = (V, U, W)
        return (V, U, W)
    else:
        raise ValueError(f"Unknown slot type: {slot_type}")


# ═══════════════════════════════════════════════════════════════════
# Ordered per-factor signature for tight pruning
# ═══════════════════════════════════════════════════════════════════

def term_signature_ordered(U, V, W, k, n):
    """
    Ordered per-factor invariant: (rank(U_k), rank(V_k), rank(W_k)).
    Rank is invariant under sandwich transforms (which act by independent
    invertible maps on each factor space). Using ORDERED tuples means this
    is only valid within a fixed slot symmetry context.

    NOTE: tr(M^T*M) and det(M) are NOT sandwich-invariant (sandwich
    transforms are general invertible maps, not orthogonal). Only rank
    is preserved.
    """
    Uk = _col_as_matrix(U, k, n)
    Vk = _col_as_matrix(V, k, n)
    Wk = _col_as_matrix(W, k, n)
    return (Uk.rank(), Vk.rank(), Wk.rank())


# ═══════════════════════════════════════════════════════════════════
# Core: check if a permutation is realizable by a sandwich transform
# ═══════════════════════════════════════════════════════════════════

def check_permutation(U_src, V_src, W_src, U_tgt, V_tgt, W_tgt, sigma, n):
    """
    Check if invertible A, B, C exist with per-column scalars satisfying
    the tensor identity, mapping source columns to permuted target columns.
    """
    r = U_src.ncols()
    n2 = n * n
    F = Sequence(list(U_src.list()) + list(U_tgt.list())).universe()

    U_p = Matrix(F, n2, r, lambda i, k: U_tgt[i, sigma[k]])
    V_p = Matrix(F, n2, r, lambda i, k: V_tgt[i, sigma[k]])
    W_p = Matrix(F, n2, r, lambda i, k: W_tgt[i, sigma[k]])

    # Try rigid first (scalars all = 1)
    ok_rigid = True
    for (src, tgt) in [(U_src, U_p), (V_src, V_p), (W_src, W_p)]:
        ok, _ = _solve_factor(src, tgt, n2, r, F)
        if not ok:
            ok_rigid = False
            break
    if ok_rigid:
        return True

    # Try with per-column sign scaling, determined by basis columns
    return _sign_enum_solve(U_src, V_src, W_src, U_p, V_p, W_p, n2, r, F)


def _solve_factor(source, target, n2, r, F):
    """
    Find invertible A such that A * source = target.
    Returns (True, A) or (False, None).
    """
    src_rank = source.rank()
    if src_rank == 0:
        return (target.is_zero(), identity_matrix(F, n2))
    if src_rank < n2:
        stacked = source.stack(target)
        if stacked.rank() != src_rank:
            return (False, None)
        st = source.transpose()
        piv = list(st.pivot_rows())
        S_sub = source.matrix_from_columns(piv)
        T_sub = target.matrix_from_columns(piv)
        # Extend to full rank
        S_ext = Matrix(F, S_sub)
        T_ext = Matrix(F, T_sub)
        for e_idx in range(n2):
            if S_ext.ncols() >= n2:
                break
            e = vector(F, n2)
            e[e_idx] = 1
            trial = S_ext.augment(matrix(F, n2, 1, list(e)))
            if trial.rank() > S_ext.rank():
                S_ext = trial
                T_ext = T_ext.augment(matrix(F, n2, 1, list(e)))
        if S_ext.rank() < n2:
            return (False, None)
        try:
            A = T_ext * S_ext.inverse()
        except Exception:
            return (False, None)
        if A.det() == 0:
            return (False, None)
        if A * source != target:
            return (False, None)
        return (True, A)
    else:
        st = source.transpose()
        piv = list(st.pivot_rows())
        S_sub = source.matrix_from_columns(piv[:n2])
        T_sub = target.matrix_from_columns(piv[:n2])
        try:
            A = T_sub * S_sub.inverse()
        except Exception:
            return (False, None)
        if A.det() == 0:
            return (False, None)
        if A * source != target:
            return (False, None)
        return (True, A)


def _sign_enum_solve(U_src, V_src, W_src, U_tgt, V_tgt, W_tgt, n2, r, F):
    """
    Enumerate sign patterns on basis columns to determine A (and B),
    then check W with determined scalars.
    """
    if n2 > 12:
        return False

    # Solve U factor: A determined by action on n2 independent columns
    Ut = U_src.transpose()
    piv_U = list(Ut.pivot_rows())
    rank_U = len(piv_U)
    if rank_U < n2:
        # U doesn't span; try direct scalar extraction
        return _direct_scalar_check(U_src, V_src, W_src, U_tgt, V_tgt, W_tgt, n2, r, F)

    basis_U = piv_U[:n2]
    U_basis = U_src.matrix_from_columns(basis_U)
    U_basis_inv = U_basis.inverse()

    for sign_bits in range(2**n2):
        signs = [1 - 2 * ((sign_bits >> i) & 1) for i in range(n2)]
        cols = [signs[i] * U_tgt.column(basis_U[i]) for i in range(n2)]
        A = column_matrix(F, cols) * U_basis_inv
        if A.det() == 0:
            continue

        # Determine all eps_U from A
        eps_U = _extract_scalars_from_map(A, U_src, U_tgt, n2, r)
        if eps_U is None:
            continue

        # Now solve V similarly
        Vt = V_src.transpose()
        piv_V = list(Vt.pivot_rows())
        rank_V = len(piv_V)
        if rank_V < n2:
            continue

        basis_V = piv_V[:n2]
        V_basis = V_src.matrix_from_columns(basis_V)
        V_basis_inv = V_basis.inverse()

        for sign_bits_V in range(2**n2):
            signs_V = [1 - 2 * ((sign_bits_V >> i) & 1) for i in range(n2)]
            cols_V = [signs_V[i] * V_tgt.column(basis_V[i]) for i in range(n2)]
            B = column_matrix(F, cols_V) * V_basis_inv
            if B.det() == 0:
                continue

            eps_V = _extract_scalars_from_map(B, V_src, V_tgt, n2, r)
            if eps_V is None:
                continue

            # W scalars determined: nu_k = 1/(eps_U[k]*eps_V[k])
            eps_W = []
            ok = True
            for k in range(r):
                prod = eps_U[k] * eps_V[k]
                if prod == 0:
                    ok = False
                    break
                eps_W.append(1 / prod)
            if not ok:
                continue

            W_scaled = Matrix(F, n2, r,
                              lambda i, k: eps_W[k] * W_tgt[i, k])
            ok_C, _ = _solve_factor(W_src, W_scaled, n2, r, F)
            if ok_C:
                return True

    return False


def _extract_scalars_from_map(A, source, target, n2, r):
    """Given map A, extract scalars eps_k such that A*source[:,k] = eps_k*target[:,k]."""
    eps = []
    for k in range(r):
        mapped = A * source.column(k)
        tgt = target.column(k)
        scalar = None
        ok = True
        for i in range(n2):
            if tgt[i] == 0 and mapped[i] == 0:
                continue
            if tgt[i] == 0 or mapped[i] == 0:
                ok = False
                break
            ratio = mapped[i] / tgt[i]
            if scalar is None:
                scalar = ratio
            elif ratio != scalar:
                ok = False
                break
        if not ok:
            return None
        eps.append(scalar if scalar is not None else 1)
    return eps


def _direct_scalar_check(U_src, V_src, W_src, U_tgt, V_tgt, W_tgt, n2, r, F):
    """
    When factor matrices don't span the full space, check if columns are
    directly proportional and the proportionality constants are compatible.
    """
    eps_U = _find_proportional_scalars(U_src, U_tgt, n2, r)
    if eps_U is None:
        return False
    eps_V = _find_proportional_scalars(V_src, V_tgt, n2, r)
    if eps_V is None:
        return False
    eps_W = []
    for k in range(r):
        prod = eps_U[k] * eps_V[k]
        if prod == 0:
            return False
        eps_W.append(1 / prod)
    W_scaled = Matrix(Sequence(list(W_src.list())).universe(), n2, r,
                      lambda i, k: eps_W[k] * W_tgt[i, k])
    ok, _ = _solve_factor(W_src, W_scaled, n2, r,
                          Sequence(list(W_src.list())).universe())
    return ok


def _find_proportional_scalars(source, target, n2, r):
    """Check if source[:,k] is proportional to target[:,k] for all k."""
    scalars = []
    for k in range(r):
        s = source.column(k)
        t = target.column(k)
        alpha = None
        ok = True
        for i in range(n2):
            if s[i] == 0 and t[i] == 0:
                continue
            if s[i] == 0 or t[i] == 0:
                ok = False
                break
            ratio = t[i] / s[i]
            if alpha is None:
                alpha = ratio
            elif ratio != alpha:
                ok = False
                break
        if not ok:
            return None
        scalars.append(alpha if alpha is not None else 1)
    return scalars


# ═══════════════════════════════════════════════════════════════════
# Main computation
# ═══════════════════════════════════════════════════════════════════

SLOT_TYPES = ['id', 'cyc', 'cyc2', 'tr', 'tr_cyc', 'tr_cyc2']
MAX_PERMS = 200000


def compute_stabilizer(U, V, W, n, label="decomp", verbose=True):
    """
    Compute the symmetry group of a decomposition of <n,n,n>.
    """
    r = U.ncols()
    n2 = n * n
    F = U.base_ring()
    t0 = time.time()

    if verbose:
        print(f"\n{'='*60}")
        print(f"  Stabilizer computation: {label} (rank {r}, <{n},{n},{n}> over {F})")
        print(f"{'='*60}")

    found_perms = []
    is_lower_bound = False

    for slot in SLOT_TYPES:
        U_s, V_s, W_s = apply_slot_symmetry(U, V, W, n, slot)

        # Compute ORDERED signatures for source (slot-transformed) and target (original)
        sigs_src = [term_signature_ordered(U_s, V_s, W_s, k, n) for k in range(r)]
        sigs_tgt = [term_signature_ordered(U, V, W, k, n) for k in range(r)]

        # Build compatibility: source term k can map to target term j iff sigs match
        src_by_sig = {}
        for k in range(r):
            src_by_sig.setdefault(sigs_src[k], []).append(k)
        tgt_by_sig = {}
        for j in range(r):
            tgt_by_sig.setdefault(sigs_tgt[j], []).append(j)

        # Check that every source signature class has a matching target class of same size
        class_pairs = []
        total_enum = 1
        feasible = True
        for sig, src_members in src_by_sig.items():
            tgt_members = tgt_by_sig.get(sig, [])
            if len(src_members) != len(tgt_members):
                feasible = False
                break
            class_pairs.append((src_members, tgt_members))
            total_enum *= factorial(len(tgt_members))

        if not feasible:
            if verbose:
                print(f"  Slot {slot}: no compatible permutations")
            continue

        if verbose:
            print(f"  Slot {slot}: {total_enum} candidates", end="")

        if total_enum > MAX_PERMS:
            if verbose:
                print(f" -> heuristic search")
            is_lower_bound = True
            _heuristic_search(U_s, V_s, W_s, U, V, W, n, r,
                              class_pairs, found_perms, verbose)
            continue

        # Enumerate all signature-compatible permutations
        count = 0
        found_this = 0

        def gen_perms(pairs, perm):
            if not pairs:
                yield list(perm)
                return
            src, tgt = pairs[0]
            rest = pairs[1:]
            for p in iter_permutations(tgt):
                new_perm = list(perm)
                for s, t in zip(src, p):
                    new_perm[s] = t
                yield from gen_perms(rest, new_perm)

        for sigma in gen_perms(class_pairs, list(range(r))):
            count += 1
            if check_permutation(U_s, V_s, W_s, U, V, W, sigma, n):
                found_perms.append([s + 1 for s in sigma])
                found_this += 1

        if verbose:
            print(f", tested {count}, found {found_this}")

    # Build permutation group
    if found_perms:
        G = PermutationGroup(found_perms)
    else:
        G = PermutationGroup([], domain=range(1, r+1))

    order = G.order()
    try:
        desc = G.structure_description()
    except Exception:
        desc = f"order {order}"

    orbits = G.orbits()
    orbits_0 = [sorted([x - 1 for x in orb]) for orb in orbits]
    orbits_0.sort(key=lambda o: (len(o), min(o)))
    orbit_sizes = sorted([len(o) for o in orbits_0])

    col_order = []
    for orb in orbits_0:
        col_order.extend(orb)

    elapsed = time.time() - t0
    status = "LOWER BOUND" if is_lower_bound else "EXACT"

    if verbose:
        print(f"\n  Result: {desc}, order {order} ({status})")
        print(f"  Orbits: {' + '.join(str(len(o)) for o in orbits_0)}")
        orbit_detail = ', '.join(
            '{' + ','.join(str(x+1) for x in o) + '}' for o in orbits_0
        )
        print(f"  Orbit partition: {orbit_detail}")
        print(f"  Elapsed: {elapsed:.2f}s")

    return {
        'label': label,
        'order': order,
        'lower_bound': is_lower_bound,
        'structure_desc': desc,
        'orbits': orbits_0,
        'orbit_sizes': orbit_sizes,
        'perm_group': G,
        'col_order': col_order,
    }


def _heuristic_search(U_s, V_s, W_s, U_tgt, V_tgt, W_tgt, n, r,
                      class_pairs, found_perms, verbose):
    """
    For large search spaces, use the "determine-then-deduce" approach:
    1. Enumerate permutations of the SMALL signature classes (size <= 5).
    2. For each small-class choice, solve for the sandwich matrix A.
    3. Use A to DEDUCE the forced permutation on the large classes.
    4. Verify B and C consistency on the full permutation.
    """
    from itertools import product as iter_product
    n2 = n * n
    F = Sequence(list(U_s.list()) + list(U_tgt.list())).universe()
    count = 0
    found_here = 0

    # Separate small classes (enumerate) from large classes (deduce)
    SMALL_THRESHOLD = 5
    small_pairs = []
    large_pairs = []
    for src, tgt in class_pairs:
        if len(tgt) <= SMALL_THRESHOLD:
            small_pairs.append((src, tgt))
        else:
            large_pairs.append((src, tgt))

    # All columns in small classes
    small_src_cols = []
    for src, tgt in small_pairs:
        small_src_cols.extend(src)

    # Check if small-class columns span enough dimensions to determine A
    small_src_mat = U_s.matrix_from_columns(small_src_cols) if small_src_cols else Matrix(F, n2, 0)
    small_rank = small_src_mat.rank() if small_src_cols else 0

    if verbose:
        total_small = 1
        for src, tgt in small_pairs:
            total_small *= factorial(len(tgt))
        print(f"    Small classes: {len(small_pairs)} pairs, {total_small} combos, rank coverage: {small_rank}/{n2}")

    if small_rank < n2 and not large_pairs:
        if verbose:
            print(f"    Insufficient rank for determine-deduce, skipping")
        return

    # If small classes don't span, augment with columns from large classes.
    # Pick source columns from each large class that extend the rank,
    # and enumerate their possible target assignments.
    augment_options = []  # list of (src_col, [possible_tgt_cols])
    augment_src_cols = []
    if small_rank < n2:
        needed = n2 - small_rank
        for src_large, tgt_large in large_pairs:
            if needed <= 0:
                break
            # Find source columns that extend the span
            cur_mat = small_src_mat
            for sc in augment_src_cols:
                cur_mat = cur_mat.augment(matrix(F, n2, 1, list(U_s.column(sc))))
            for s in src_large:
                trial = cur_mat.augment(matrix(F, n2, 1, list(U_s.column(s))))
                if trial.rank() > cur_mat.rank():
                    augment_src_cols.append(s)
                    augment_options.append((s, tgt_large))
                    cur_mat = trial
                    needed -= 1
                    if needed <= 0:
                        break

    # Generate per-class permutation options for small classes
    per_class_options = []
    for src, tgt in small_pairs:
        per_class_options.append((src, list(iter_permutations(tgt))))

    total_combos = 1
    for _, opts in per_class_options:
        total_combos *= len(opts)

    if total_combos > 500000:
        if verbose:
            print(f"    Too many small-class combos ({total_combos}), reducing")
        # Limit: only try cyclic shifts within each class
        per_class_options_reduced = []
        for src, opts in per_class_options:
            sz = len(src)
            reduced = [tuple(opts[0])]  # identity
            for shift in range(1, sz):
                tgt_list = list(opts[0])
                perm = tuple(tgt_list[(i + shift) % sz] for i in range(sz))
                reduced.append(perm)
            per_class_options_reduced.append((src, reduced))
        per_class_options = per_class_options_reduced
        total_combos = 1
        for _, opts in per_class_options:
            total_combos *= len(opts)

    # For each combination of small-class permutations + augment assignments:
    default = list(range(r))  # identity as default for large classes
    for src, tgt in class_pairs:
        for s, t in zip(src, tgt):
            default[s] = t

    combo_iterables = [opts for _, opts in per_class_options]
    if not combo_iterables:
        combo_iterables = [[()] ]  # single empty combo

    # Build augment iterables: for each augment column, iterate over
    # possible target columns (with +-1 sign)
    augment_iterables = []
    for aug_src, aug_tgts in augment_options:
        # Each option is (target_col, sign)
        aug_opts = [(t, 1) for t in aug_tgts] + [(t, -1) for t in aug_tgts]
        augment_iterables.append((aug_src, aug_opts))

    def _iter_augments():
        """Iterate over all augment assignments."""
        if not augment_iterables:
            yield []
            return
        opts_lists = [opts for _, opts in augment_iterables]
        for combo in iter_product(*opts_lists):
            yield list(combo)

    for combo in iter_product(*combo_iterables):
        # Build partial permutation from small classes
        sigma_base = list(default)
        for idx, (src, _) in enumerate(per_class_options):
            for i, s in enumerate(src):
                sigma_base[s] = combo[idx][i]

        if not large_pairs and not augment_options:
            count += 1
            if check_permutation(U_s, V_s, W_s, U_tgt, V_tgt, W_tgt, sigma_base, n):
                found_perms.append([s + 1 for s in sigma_base])
                found_here += 1
            continue

        for aug_combo in _iter_augments():
            count += 1
            sigma = list(sigma_base)

            # Set augment column assignments
            for idx, (aug_src, _) in enumerate(augment_iterables):
                aug_tgt, aug_sign = aug_combo[idx]
                sigma[aug_src] = aug_tgt

            # Determine A from small-class + augment columns
            all_fixed_src = list(small_src_cols) + list(augment_src_cols)
            all_fixed_tgt = [sigma[k] for k in all_fixed_src]
            U_src_fixed = U_s.matrix_from_columns(all_fixed_src)

            # Build target with signs from augment
            tgt_cols_list = []
            for k in all_fixed_src:
                if k in augment_src_cols:
                    idx_aug = augment_src_cols.index(k)
                    _, sign = aug_combo[idx_aug]
                    tgt_cols_list.append(sign * U_tgt.column(sigma[k]))
                else:
                    tgt_cols_list.append(U_tgt.column(sigma[k]))
            U_tgt_fixed = column_matrix(F, tgt_cols_list) if tgt_cols_list else Matrix(F, n2, 0)

            A = _find_A_with_signs(U_src_fixed, U_tgt_fixed, n2, F)
            if A is None:
                continue

            # Use A to deduce permutation on remaining large-class columns
            used_tgts = set(sigma[k] for k in all_fixed_src)
            ok = True
            for src_large, tgt_large in large_pairs:
                remaining_tgts = [t for t in tgt_large if t not in used_tgts]
                for s in src_large:
                    if s in augment_src_cols:
                        # Already assigned
                        used_tgts.add(sigma[s])
                        continue
                    mapped = A * U_s.column(s)
                    matched = False
                    for t in remaining_tgts:
                        scalar = _check_proportional(mapped, U_tgt.column(t), n2)
                        if scalar is not None:
                            sigma[s] = t
                            remaining_tgts.remove(t)
                            used_tgts.add(t)
                            matched = True
                            break
                    if not matched:
                        ok = False
                        break
                if not ok:
                    break

            if not ok:
                continue

            if len(set(sigma)) != r:
                continue

            if check_permutation(U_s, V_s, W_s, U_tgt, V_tgt, W_tgt, sigma, n):
                found_perms.append([s + 1 for s in sigma])
                found_here += 1

    if verbose:
        print(f"    Heuristic: tested {count}, found {found_here}")


def _find_A_with_signs(U_src_small, U_tgt_small, n2, F):
    """
    Find invertible A such that A * U_src_small[:,k] = eps_k * U_tgt_small[:,k]
    for some signs eps_k = +-1. Returns A or None.
    """
    r_small = U_src_small.ncols()
    if r_small == 0:
        return identity_matrix(F, n2)

    rank_src = U_src_small.rank()

    # First try rigid (no signs)
    ok, A = _solve_factor(U_src_small, U_tgt_small, n2, r_small, F)
    if ok:
        return A

    # Try with sign enumeration on basis columns
    st = U_src_small.transpose()
    piv = list(st.pivot_rows())
    if len(piv) < min(n2, rank_src):
        return None

    n_basis = min(n2, len(piv))
    basis = piv[:n_basis]
    U_basis = U_src_small.matrix_from_columns(basis)

    if n_basis < n2:
        # Need to extend basis to full rank
        U_ext = Matrix(F, U_basis)
        for e_idx in range(n2):
            if U_ext.ncols() >= n2:
                break
            e = vector(F, n2)
            e[e_idx] = 1
            trial = U_ext.augment(matrix(F, n2, 1, list(e)))
            if trial.rank() > U_ext.rank():
                U_ext = trial
        if U_ext.rank() < n2:
            return None
        U_basis_full = U_ext
    else:
        U_basis_full = U_basis

    U_basis_full_inv = U_basis_full.inverse()

    for sign_bits in range(2**n_basis):
        signs = [1 - 2 * ((sign_bits >> i) & 1) for i in range(n_basis)]

        # Build target columns for basis
        tgt_cols = [signs[i] * U_tgt_small.column(basis[i]) for i in range(n_basis)]
        # Extend with identity basis vectors for the extra columns
        if n_basis < n2:
            for e_idx in range(n2):
                if len(tgt_cols) >= n2:
                    break
                # Same extension as U_basis_full
                if U_basis_full.ncols() > n_basis:
                    tgt_cols.append(U_basis_full.column(len(tgt_cols)))
            if len(tgt_cols) < n2:
                continue
        A = column_matrix(F, tgt_cols) * U_basis_full_inv
        if A.det() == 0:
            continue

        # Verify on all small columns
        ok = True
        for k in range(r_small):
            mapped = A * U_src_small.column(k)
            tgt = U_tgt_small.column(k)
            s = _check_proportional(mapped, tgt, n2)
            if s is None:
                ok = False
                break
        if ok:
            return A

    return None


def _check_proportional(v1, v2, n):
    """If v1 = alpha * v2 for some nonzero scalar, return alpha. Otherwise None."""
    alpha = None
    for i in range(n):
        if v1[i] == 0 and v2[i] == 0:
            continue
        if v1[i] == 0 or v2[i] == 0:
            return None
        ratio = v1[i] / v2[i]
        if alpha is None:
            alpha = ratio
        elif ratio != alpha:
            return None
    return alpha


# ═══════════════════════════════════════════════════════════════════
# Standalone test
# ═══════════════════════════════════════════════════════════════════

if len(sys.argv) > 0 and 'decomp_stabilizer' in sys.argv[0]:
    print("decomp_stabilizer.sage — standalone test\n")

    U_str = Matrix(ZZ, [
        [1, 0, 0, 1], [0, 0, 1, 1], [1, 0, 0, 0], [0, 0, 0, 1],
        [1, 1, 0, 0], [-1, 0, 1, 0], [0, 1, 0, -1],
    ]).transpose()
    V_str = Matrix(ZZ, [
        [1, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, -1], [-1, 0, 1, 0],
        [0, 0, 0, 1], [1, 1, 0, 0], [0, 0, 1, 1],
    ]).transpose()
    W_str = Matrix(ZZ, [
        [1, 0, 0, 1], [0, 0, 1, -1], [0, 1, 0, 1], [1, 0, 1, 0],
        [-1, 1, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0],
    ]).transpose()

    info = compute_stabilizer(U_str, V_str, W_str, 2, label="Strassen")
    print(f"\nValidation: order={info['order']}, expected=36, "
          f"{'PASS' if info['order'] == 36 else 'FAIL'}")
