package main

import (
	"fmt"
	"os"
	"strings"
)

func writeMarkdown(path string, classes []invClass, res *results) {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# Tr1 — Degree-3 trace invariants on MM and low-rank tensors (results)\n\n")
	w("Generated by `cmd/probe-traceinv` (stdlib only). ")
	w("Seed `%d`, %d samples/cell, elapsed %s, complete=%v.\n\n", res.Seed, res.Samples, res.Elapsed, res.Complete)

	w("## Sanity checks\n\n")
	w("All hard assertions passed: **%v**.\n", res.SanityPassed)
	w("- `f = 1` on every random rank-one tensor, for all %d classes.\n", res.NumClasses)
	w("- All-identity class gives `f = 1` on arbitrary tensors.\n")
	w("- Every class is invariant under random QR-derived local unitaries (|Δ| < 1e-7).\n\n")

	w("## Degree-3 invariant classes\n\n")
	w("There are **%d** S_3^3-conjugation classes of degree-3 trace invariants ", res.NumClasses)
	w("(216 raw triples deduped by simultaneous conjugation σ_c ↦ τσ_cτ⁻¹).\n\n")
	disc := 0
	for _, ci := range res.Classes {
		if ci.Disconnected {
			disc++
		}
	}
	w("%d classes are **disconnected** (network factorizes — the invariant is a product of lower-degree invariants on the same tensor); %d are connected.\n\n", disc, res.NumClasses-disc)
	w("| # | representative (σ1,σ2,σ3) | orbit | connected | cost d^? |\n")
	w("|---|---|---|---|---|\n")
	for _, ci := range res.Classes {
		w("| %d | `%s` | %d | %v | %d |\n", ci.Index, ci.Rep, ci.OrbitSize, !ci.Disconnected, ci.CostExponent)
	}
	w("\nThe pure 3-cycle invariant is the class with representative `(120,120,120)` ")
	w("(σ=(123) on every leg); its inverse is `(201,201,201)` (σ=(132)).\n\n")

	w("## Catalog table\n\n")
	w("Normalized degree-3 invariants `f = tr/‖T‖^6` and flattening (degree-2) ranks for each catalog tensor.\n\n")
	w("Flattening ranks (numerical, threshold 1e-8 of top singular value):\n\n")
	w("| tensor | dims | known rank | flat ranks | f_(123) | f_(132) | f_id |\n")
	w("|---|---|---|---|---|---|---|\n")
	c123 := classIndexOf(classes, perm{1, 2, 0})
	c132 := classIndexOf(classes, perm{2, 0, 1})
	cid := indexOfRep(res.Classes, "(012,012,012)")
	for _, row := range res.Catalog {
		w("| %s | %dx%dx%d | %s | %d,%d,%d | %s | %s | %s |\n",
			row.Name, row.Dims[0], row.Dims[1], row.Dims[2], row.Rank,
			row.FlatRanks[0], row.FlatRanks[1], row.FlatRanks[2],
			fmtC(row.Invariants[c123]), fmtC(row.Invariants[c132]), fmtC(row.Invariants[cid]))
	}
	w("\nFull per-class invariant values are in the JSON (`catalog[].invariants`).\n\n")

	w("## Detection experiment: W_3 vs GHZ_2\n\n")
	w("Both live in C^2⊗C^2⊗C^2. Known: R(W_3)=3, R(GHZ_2)=2; all flattening ranks 2.\n\n")
	w("Flattening spectra equal after normalization: **%v** (max |Δ| = %.3e).\n\n",
		res.Detection.SpectraEqual, res.Detection.MaxSpectralDiff)
	if !res.Detection.SpectraEqual {
		w("> **Premise correction (computed, not assumed).** The task card's parenthetical ")
		w("that W_3 and GHZ_2 share normalized flattening spectra is FALSE. Their flattening ")
		w("*ranks* both equal 2, but the normalized *singular values* differ ")
		w("(W_3 = {√(2/3), √(1/3)} ≈ {0.8165, 0.5774}; GHZ_2 = {1/√2, 1/√2} ≈ {0.7071, 0.7071}). ")
		w("Hence the **degree-2 flattening singular spectra already separate** W_3 from GHZ_2; ")
		w("the degree-3 invariants below also separate them but are not required for this pair. ")
		w("The flattening *ranks* coincide, so a rank-only (not spectrum) reading of the detection ")
		w("hypothesis is what the degree-3 invariants address.\n\n")
	}
	w("Normalized flattening spectra:\n\n")
	for m := 0; m < 3; m++ {
		w("- mode %d: W_3 %s | GHZ_2 %s\n", m+1, fmtFloats(res.Detection.W3Spectra[m]), fmtFloats(res.Detection.GHZ2Spectra[m]))
	}
	w("\nDegree-3 classes that **separate** W_3 from GHZ_2 (|f(W_3) − f(GHZ_2)| > 1e-7): ")
	w("**%d of %d**.\n\n", len(res.Detection.SeparatingClasses), res.NumClasses)
	if len(res.Detection.SeparatingClasses) > 0 {
		w("| class # | representative | f(W_3) | f(GHZ_2) |\n|---|---|---|---|\n")
		for _, ci := range res.Detection.SeparatingClasses {
			w("| %d | `%s` | %s | %s |\n", ci, tripleString(classes[ci].rep),
				fmtC(res.Detection.W3Invariants[ci]), fmtC(res.Detection.GHZ2Invariants[ci]))
		}
		w("\n")
	}

	w("## Separation experiment\n\n")
	w("%s\n\n", res.Separation.Note)
	w("Throughput: %s.\n\n", res.Separation.Throughput)
	w("For each (n, r) cell we sample rank-r tensors in C^(n^2)^3 and ask whether ")
	w("`f(<n,n,n>)` lies INSIDE the sampled [min,max] of each invariant ")
	w("(both Re and Im). Inside ⟹ that invariant cannot certify rank ≥ r. ")
	w("The flattening bound is r = n^2 (= d).\n\n")
	w("Summary per cell — number of classes (of %d) whose MM value falls OUTSIDE the sampled range ", res.NumClasses)
	w("(i.e. a *potential* separation), and the two real 3-cycle combinations:\n\n")
	w("| n | r | r vs n^2 | samples | classes outside | combo_sym outside | combo_anti outside |\n")
	w("|---|---|---|---|---|---|---|\n")
	for _, cell := range res.Separation.Cells {
		outside := 0
		for ci := range cell.Stats {
			if !cell.Stats[ci].MMInside {
				outside++
			}
		}
		rel := "<"
		if cell.R == cell.FlatBound {
			rel = "="
		} else if cell.R > cell.FlatBound {
			rel = ">"
		}
		w("| %d | %d | %s n^2 | %d | %d | %v | %v |\n",
			cell.N, cell.R, rel, cell.Collected, outside, !cell.MMComboSymIn, !cell.MMComboAntiIn)
	}
	w("\nFull per-class min/max/quantiles per cell are in the JSON (`separation.cells[].stats_per_class`).\n\n")

	w("## Conclusion\n\n")
	cc := res.Conclusion
	w("**Methodological caveat (read first).** %s\n\n", cc.Caveat)

	w("**(a) Separation of <n,n,n> from sampled rank-r tensors.**\n\n")
	w("- The pure 3-cycle invariants `f_(123)`, `f_(132)` are **identically constant** ")
	w("(both ≡ 1 after normalization): the network factorizes into 3 disjoint T·conj pairs, ")
	w("so `tr = ‖T‖^6`. Their real combinations are also constant: ")
	w("`f_(123)+f_(132) ≡ 2`, `i·(f_(123)−f_(132)) ≡ 0`. ")
	w("Pure-3-cycle invariants constant: **%v**; 3-cycle combos separate MM: **%v**.\n", cc.PureCycleConstant, cc.CombosSeparateMM)
	w("- Of %d classes, **%d are constant** (sample-invariant, zero info); the other %d are informative.\n",
		res.NumClasses, cc.NumConstantClasses, res.NumClasses-cc.NumConstantClasses)
	w("- f(MM) lies OUTSIDE the finite sampled bounding box for some informative class at r ≥ n²: ")
	w("**%v** — but per the caveat this is an inner-approximation artifact, **not a rank certificate**.\n\n", cc.AnyOutsideAtFlatBound)
	w("Per-cell count of classes whose MM value falls outside the sampled box ")
	w("(informative classes only; the constant classes are always inside):\n\n")
	w("| n | r | r≥n² | classes outside | combo_sym out | combo_anti out |\n")
	w("|---|---|---|---|---|---|\n")
	for _, pc := range cc.PerCellOutsideCount {
		w("| %d | %d | %v | %d | %v | %v |\n", pc.N, pc.R, pc.AtOrAboveFlat, pc.OutsideCount, pc.ComboSymOut, pc.ComboAntiOut)
	}
	w("\nThe constant per-cell outside count (= informative-class count) across r confirms the clouds do not grow to engulf f(MM); but neither do they certifiably exclude it.\n\n")

	w("**(b) W_3 / GHZ_2.** Separated by a degree-3 class: **%v** (%d of %d classes). ",
		cc.W3GHZ2Separated, len(cc.W3GHZ2SeparatingClasses), res.NumClasses)
	w("Note: degree-2 flattening *singular spectra* already separate this pair ")
	w("(W_3 = {0.8165, 0.5774} vs GHZ_2 = {0.7071, 0.7071}), so the degree-3 separation is not the unique witness here. ")
	w("The flattening *ranks* coincide (both 2).\n")
	if len(cc.ConstantClasses) > 0 {
		w("\nConstant (uninformative) classes: %s.\n", strings.Join(cc.ConstantClasses, ", "))
	}
	w("\n_No interpretation beyond the above — Pl3 interprets._\n")

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
	}
}

func fmtC(c cmplxJSON) string {
	if abs(c.Im) < 1e-9 {
		return fmt.Sprintf("%.4f", c.Re)
	}
	return fmt.Sprintf("%.4f%+.4fi", c.Re, c.Im)
}

func fmtFloats(xs []float64) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprintf("%.4f", x)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func abs(x float64) float64 {
	if x < 0 {
		return -x
	}
	return x
}

func indexOfRep(infos []classInfo, rep string) int {
	for _, ci := range infos {
		if ci.Rep == rep {
			return ci.Index
		}
	}
	return 0
}
