import Mathlib.Order.Lattice.Nat

/-!
# Integer complexity of positive powers of three

This challenge uses an independent expression language over the constant `1`,
addition, and multiplication.  The cost is the number of `one` leaves, and
`complexity n` is the least cost among expressions evaluating to `n`.

The index is empty at zero, so `complexity 0 = 0` is a junk convention.  The
headline keeps the positive-exponent guard: at exponent zero its claimed right
side would be zero, while the complexity of `3 ^ 0 = 1` is one.
-/

set_option autoImplicit false

namespace Palomar.IntegerComplexityPowersOfThree

/-- An arithmetic expression generated by `1`, addition, and multiplication. -/
inductive Expr : Type
  | one : Expr
  | add : Expr → Expr → Expr
  | mul : Expr → Expr → Expr
  deriving DecidableEq, Repr

namespace Expr

/-- Evaluate an expression as a natural number. -/
def eval : Expr → ℕ
  | one => 1
  | add a b => eval a + eval b
  | mul a b => eval a * eval b

/-- Count the `one` leaves in an expression. -/
def cost : Expr → ℕ
  | one => 1
  | add a b => cost a + cost b
  | mul a b => cost a + cost b

example : (add one (add one one)).eval = 3 := rfl
example : (add one (add one one)).cost = 3 := rfl
example : (mul (add one one) (add one (add one one))).eval = 6 := rfl
example : (mul (add one one) (add one (add one one))).cost = 5 := rfl

end Expr

/-- The integer complexity of `n`: the least number of `one` leaves in an
expression over `1`, addition, and multiplication which evaluates to `n`.
At `n = 0` the indexing subtype is empty and the natural infimum is the junk
value zero. -/
noncomputable def complexity (n : ℕ) : ℕ :=
  ⨅ e : {e : Expr // e.eval = n}, e.1.cost

/-- Every positive power of three has integer complexity exactly three times
its exponent. -/
theorem complexity_three_pow {b : ℕ} (hb : 1 ≤ b) :
    complexity (3 ^ b) = 3 * b := by
  sorry

example : ∃ b : ℕ, 1 ≤ b ∧ complexity (3 ^ b) = 3 * b :=
  ⟨1, le_refl 1, complexity_three_pow (le_refl 1)⟩

end Palomar.IntegerComplexityPowersOfThree

#check @Palomar.IntegerComplexityPowersOfThree.complexity_three_pow
