import NumberComplexity.DoublingConjecture

/-!
# Integer complexity of positive powers of three

This solution repeats the challenge's independent expression language and
complexity definition; it does not import the challenge.  Recursive translations
in both directions preserve evaluation and cost.  They transport the independent
minimum to `NumberComplexity.complexity`, after which the repository's classical
powers-of-three theorem supplies the result.  Although the imported source also
contains an intentionally open powers-of-two conjecture, the selected theorem's
axiom closure is audited separately below and does not use that conjecture.
-/

set_option autoImplicit false

namespace Palomar.IntegerComplexityPowersOfThree

/-- An arithmetic expression generated by `1`, addition, and multiplication. -/
inductive Expr : Type
  | one : Expr
  | add : Expr → Expr → Expr
  | mul : Expr → Expr → Expr
  deriving DecidableEq, Repr

namespace Expr

/-- Evaluate an expression as a natural number. -/
def eval : Expr → ℕ
  | one => 1
  | add a b => eval a + eval b
  | mul a b => eval a * eval b

/-- Count the `one` leaves in an expression. -/
def cost : Expr → ℕ
  | one => 1
  | add a b => cost a + cost b
  | mul a b => cost a + cost b

example : (add one (add one one)).eval = 3 := rfl
example : (add one (add one one)).cost = 3 := rfl
example : (mul (add one one) (add one (add one one))).eval = 6 := rfl
example : (mul (add one one) (add one (add one one))).cost = 5 := rfl

end Expr

/-- The integer complexity of `n`: the least number of `one` leaves in an
expression over `1`, addition, and multiplication which evaluates to `n`.
At `n = 0` the indexing subtype is empty and the natural infimum is the junk
value zero. -/
noncomputable def complexity (n : ℕ) : ℕ :=
  ⨅ e : {e : Expr // e.eval = n}, e.1.cost

namespace Expr

/-- Translate an independent expression to the repository expression language. -/
def toSource : Expr → NumberComplexity.Expr
  | one => .one
  | add a b => .add (toSource a) (toSource b)
  | mul a b => .mul (toSource a) (toSource b)

/-- Translate a repository expression to the independent expression language. -/
def ofSource : NumberComplexity.Expr → Expr
  | .one => one
  | .add a b => add (ofSource a) (ofSource b)
  | .mul a b => mul (ofSource a) (ofSource b)

example : toSource (add one one) = NumberComplexity.Expr.add .one .one := rfl
example : ofSource (NumberComplexity.Expr.add .one .one) = add one one := rfl

/-- Translation to the repository language preserves evaluation. -/
theorem eval_toSource (e : Expr) : (toSource e).eval = e.eval := by
  induction e with
  | one => rfl
  | add a b iha ihb => simp only [toSource, NumberComplexity.Expr.eval, eval, iha, ihb]
  | mul a b iha ihb => simp only [toSource, NumberComplexity.Expr.eval, eval, iha, ihb]

/-- Translation to the repository language preserves cost. -/
theorem cost_toSource (e : Expr) : (toSource e).cost = e.cost := by
  induction e with
  | one => rfl
  | add a b iha ihb => simp only [toSource, NumberComplexity.Expr.cost, cost, iha, ihb]
  | mul a b iha ihb => simp only [toSource, NumberComplexity.Expr.cost, cost, iha, ihb]

/-- Translation from the repository language preserves evaluation. -/
theorem eval_ofSource (e : NumberComplexity.Expr) : (ofSource e).eval = e.eval := by
  induction e with
  | one => rfl
  | add a b iha ihb => simp only [ofSource, eval, NumberComplexity.Expr.eval, iha, ihb]
  | mul a b iha ihb => simp only [ofSource, eval, NumberComplexity.Expr.eval, iha, ihb]

/-- Translation from the repository language preserves cost. -/
theorem cost_ofSource (e : NumberComplexity.Expr) : (ofSource e).cost = e.cost := by
  induction e with
  | one => rfl
  | add a b iha ihb => simp only [ofSource, cost, NumberComplexity.Expr.cost, iha, ihb]
  | mul a b iha ihb => simp only [ofSource, cost, NumberComplexity.Expr.cost, iha, ihb]

end Expr

/-- Any independent expression evaluating to `n` gives an upper bound on the
independent complexity of `n`. -/
theorem complexity_le_cost {n : ℕ} {e : Expr} (he : e.eval = n) :
    complexity n ≤ e.cost := by
  change sInf (Set.range fun w : {w : Expr // w.eval = n} => w.1.cost) ≤ e.cost
  exact Nat.sInf_le ⟨⟨e, he⟩, rfl⟩

/-- On positive inputs, the independent complexity agrees with the repository's
integer-complexity definition. -/
theorem complexity_eq_source {n : ℕ} (hn : 1 ≤ n) :
    complexity n = NumberComplexity.complexity n := by
  apply le_antisymm
  · obtain ⟨e, he, hc⟩ := NumberComplexity.exists_cost_eq_complexity hn
    calc
      complexity n ≤ (Expr.ofSource e).cost :=
        complexity_le_cost ((Expr.eval_ofSource e).trans he)
      _ = e.cost := Expr.cost_ofSource e
      _ = NumberComplexity.complexity n := hc
  · change NumberComplexity.complexity n ≤
      sInf (Set.range fun e : {e : Expr // e.eval = n} => e.1.cost)
    have hne :
        (Set.range fun e : {e : Expr // e.eval = n} => e.1.cost).Nonempty := by
      obtain ⟨e, he, _⟩ := NumberComplexity.exists_cost_eq_complexity hn
      refine ⟨(Expr.ofSource e).cost, ⟨⟨Expr.ofSource e, ?_⟩, rfl⟩⟩
      exact (Expr.eval_ofSource e).trans he
    obtain ⟨⟨e, he⟩, hc⟩ := Nat.sInf_mem hne
    rw [← hc]
    calc
      NumberComplexity.complexity n ≤ (Expr.toSource e).cost :=
        NumberComplexity.complexity_le_cost ((Expr.eval_toSource e).trans he)
      _ = e.cost := Expr.cost_toSource e

/-- Every positive power of three has integer complexity exactly three times
its exponent. -/
theorem complexity_three_pow {b : ℕ} (hb : 1 ≤ b) :
    complexity (3 ^ b) = 3 * b := by
  rw [complexity_eq_source (Nat.one_le_pow _ _ (by omega))]
  exact NumberComplexity.complexity_three_pow hb

example : ∃ b : ℕ, 1 ≤ b ∧ complexity (3 ^ b) = 3 * b :=
  ⟨1, le_refl 1, complexity_three_pow (le_refl 1)⟩

example : complexity (3 ^ 0) ≠ 3 * 0 := by
  rw [complexity_eq_source (by norm_num), pow_zero, NumberComplexity.complexity_one]
  norm_num

end Palomar.IntegerComplexityPowersOfThree

#check @Palomar.IntegerComplexityPowersOfThree.complexity_three_pow
#print axioms Palomar.IntegerComplexityPowersOfThree.complexity_three_pow
#print axioms NumberComplexity.complexity_three_pow
#print axioms NumberComplexity.complexity_two_pow
