import Enumerative.PowerOfTwoDigitsCount
import Mathlib.Data.Nat.Totient
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.Algebra.Group.Subgroup.Finite

/-!
# Erdős #406, the method barrier: finite-depth digit information cannot decide the
conjecture — and a Wieferich-window instance where the same sieve does

## Source

The problem statement, its references, and the OEIS cross-references are pinned verbatim
in the grandparent `Enumerative.PowerOfTwoDigits` (pulled with `goof erdos fetch 406` on
2026-08-05). The truncated sieve `SieveAt`, the admissible classes `sieveClasses`, the
crux `two_pow_two_mul_three_pow`, and the counting bounds live in the parent
`Enumerative.PowerOfTwoDigitsCount`. This file proves the *sharpness package* for that
sieve: the counting bound of the parent is the **best** any finite-depth congruence
argument can do (§1–§4), and, by contrast, an instance where the identical method
terminates (§5).

### Literature pins

* **[DW16]** T. Dupuy, D. E. Weirich, *Bits of `3^n` in binary, Wieferich primes and a
  conjecture of Erdős*, J. Number Theory 158 (2016) 268–280,
  DOI 10.1016/j.jnt.2015.05.022 (read in full; PDF at repo root `dupuy15.pdf`). The
  window mechanism of §5 is their **Definition 5**, verbatim:

  > Let p and q be distinct primes. Let's call a prime q p-Wieferich at r if the
  > multiplicative group generated by p modulo q^r is isomorphic to the group generated
  > by p modulo q^{r+1}.

  and the finite-window law is their **Theorem 12** (*No higher Wieferich primes*),
  verbatim conclusion:

  > In particular if K_r denotes the kernel of the natural quotient map H_r → H_{r−1}
  > then for all r > s the kernel K_r is nontrivial (which means q is not p-Wieferich
  > at r).

* **[LZ26]** Li and Zhao, arXiv:2601.12753 (fetched at
  `References/arXiv-2601-12753/Li-Zhao-260119.tex`, the Definition at lines ≈145–148),
  the number-field generalisation of [DW16], verbatim:

  > We say that the prime ideal 𝔭 is α-Wieferich at r if the multiplicative group
  > generated by α modulo 𝔭^r is isomorphic to the multiplicative group generated by α
  > modulo 𝔭^{r-1}.

* **[La09]** Lagarias, *Ternary expansions of powers of 2* (as pinned in the parent):
  the *admissible congruence class* terminology for `sieveClasses`.

### What those papers contain and what they do not (honest novelty boundary)

[DW16] proves **averaged** digit equidistribution for `3^n` in base `2` (their Theorem
3; the per-`n` statement is their Conjecture 1, open); [LZ26] generalises the window law
to number fields. Neither paper — nor [La09] — contains digit-*set* membership
statements, survivor/admissible-class counting, or the decidability dichotomy packaged
here: *the pair `(2, base 3)` has window width `0` at every level, so its sieve is
immortal (§1–§4), while `(18, base 7)` has a Wieferich window, so the same sieve decides
its digit-set problem completely (§5)*. This dichotomy is **not stated in [La09], in
[DW16], or in [LZ26]** ([La09] and [DW16] read in full, [LZ26] probed); those three are
the sources checked, and no claim is made beyond them.

## What is proved

Everything in this file is `sorry`-free and kernel-checked (`decide`, never
`native_decide`).

* **B1, the exact order** (`orderOf_two_zmod_three_pow`; pure-ℕ form
  `two_pow_mod_eq_one_iff`): the multiplicative order of `2` mod `3^(j+1)` is *exactly*
  `2·3^j`. The parent's crux gives "order divides"; exactness is: odd divisors fail
  because `2^odd ≡ 2 (mod 3)` (`two_pow_odd_mod_three`), and divisors `2·3^i` with
  `i < j` fail because the crux at `i` has `3 ∤ c`. In [DW16] Definition 5 terms: `3` is
  `2`-Wieferich at **no** level — the group `⟨2⟩ mod 3^(j+1)` grows by a full factor `3`
  at every level, the window has width `0` everywhere. Concretely, `2^2 = 4 ≢ 1 (mod 9)`
  is the failure at the first level.
* **B2, full realization of admissible classes**
  (`sieveAt_of_mem_sieveClasses_of_modEq`; iff form
  `sieveAt_iff_mod_mem_sieveClasses`): the depth-`(j+1)` truncated constraint is
  *exactly* the union of the `2^j` admissible classes mod `2·3^j`. Within an admissible
  class the truncated constraint excludes **nothing**.
* **B3, local immortality**: (a) `setOf_sieveAt_infinite` — for every depth `j`, the set
  `{n | SieveAt (j+1) n}` is infinite (it contains the whole class of `0`, and `0` is
  admissible at every depth: `zero_mem_sieveClasses`); (b) `card_range_mul_filter_sieveAt`
  — the **exact density**: any `m` full periods contain exactly `m · 2^j` survivors. The
  parent's sieve bound is attained with equality at every depth: no congruence argument
  consuming only the low `j` base-3 digits can improve the exponent `log₃ 2`, let alone
  prove finiteness.
* **B4, fake solutions at every depth** (`exists_two_pow_mod_eq_of_not_dvd`,
  `exists_two_pow_mod_eq`, `exists_two_pow_mod_eq_of_base3ZeroOne`): every `v` prime to
  `3` is `2^n mod 3^(j+1)` for some `n` — by B1 the subgroup `⟨2⟩` has order `2·3^j`,
  which is the whole unit group since `φ(3^(j+1)) = 2·3^j` — and in particular every
  `{0,1}`-digit string with units digit `1` is realised by an actual power of `2`, by an
  exponent which moreover passes the depth-`(j+1)` sieve. `3`-adically, fake solutions
  are everywhere: no finite-depth digit observation of `2^n` can distinguish the
  conjectured world (`erdos406Set = {0, 2, 8}`) from a world with infinitely many
  solutions.
* **B5, the death pole** (`base7TwoFour_eighteen_pow_iff`): `18^n` has all base-`7`
  digits in `{2, 4}` **iff** `n = 1`. The identical three-step sieve (truncate to depth
  `3`, use periodicity `18^n ≡ 18^(n mod 3) (mod 7^3)`, check the surviving residues)
  here *terminates*: all three residues `{1, 18, 324}` carry a bad digit in positions
  `0..2`, so **zero** classes survive and the problem is decided. The mechanism is a
  Wieferich window in the [DW16] sense: `⟨18⟩` has order `3` modulo `7`, `7^2`, *and*
  `7^3` (kernel facts `18^3 % 7 = 1`, `18^3 % 49 = 1`, `18^3 % 343 = 1` in
  `eighteen_wieferich_window`) — the group does not grow for two consecutive levels, so
  the digit constraint deepens while the class count stays put, and the pruned classes
  die. The window then closes: `18^3 % 2401 = 1030 ≠ 1`. Colour from [DW16]'s own Table
  1: "2 is 3-Wieferich at 3" — the *dual* Erdős-adjacent pair (`3^n` in base `2`) is
  also windowed, while B1 proves `(2, base 3)` is windowless; the two pairs sit on
  opposite sides of the dichotomy.

## The barrier reading is metamathematical commentary, not a Lean theorem

What is formalised is exactly: realization (B2), infinitude and exact density (B3), and
unit-surjectivity (B1 + B4). The gloss — *"no proof of Erdős #406 can succeed if it
consumes only congruence information mod `3^j` (equivalently, finitely many low base-3
digits of `2^n`) for any fixed `j`"* — is a **metamathematical reading** of those
theorems: any such argument would have to fail on one of the infinitely many `n` that
B2/B3 produce, which satisfy every finite-depth truncation of the constraint. That
reading is stated here in the docstring only; there is no Lean formalisation of "proof
method" and none is claimed.

## Discrepancies with the dispatching brief

The brief's ground truth `Nat.digits 7 5832 = [1, 0, 0, 3, 2, 2]` is **wrong**: `7^5 =
16807 > 5832`, so `5832 = 2·7^4 + 3·7^3 + 1` has five base-7 digits, and the kernel
computes `[1, 0, 0, 3, 2]` (checked in `digits_seven_eighteen_pow`). The decomposition
the brief itself gives (`5832 = 1 + 3·343 + 2·2401`) confirms this. No theorem statement
is affected. Two deliberate reshapes, both strengthenings: the fake-solutions corollary
(B4) states its digit hypothesis as the parent's `Base3ZeroOne v` (definitionally the
brief's `∀ d ∈ Nat.digits 3 v, d ≤ 1`) and concludes `∃ n, 2^n % 3^(j+1) = v ∧ SieveAt
(j+1) n` — the extra conjunct makes the digit hypothesis load-bearing instead of unused.
-/

set_option autoImplicit false
set_option exponentiation.threshold 2000

namespace Erdos406

/-! ## §1 B1: the order of `2` mod `3^(j+1)` is exactly `2·3^j`

The parent's crux `two_pow_two_mul_three_pow_mod` gives `2^(2·3^j) ≡ 1`; exactness needs
every proper divisor of `2·3^j` to fail, and the proper divisors are the odd ones (which
fail mod `3` already) and `2·3^i` with `i < j` (which fail because the crux at `i` has
`3 ∤ c`). Packaged through Mathlib's `orderOf` via the prime-divisor criterion. -/

/-- Odd exponents already fail at depth 1: `2^k ≡ 2 (mod 3)` for odd `k`. (This is the
depth-1 sieve of the grandparent — `even_of_base3ZeroOne_two_pow` — in pure residue
form.) -/
theorem two_pow_odd_mod_three {k : ℕ} (hk : Odd k) : 2 ^ k % 3 = 2 := by
  obtain ⟨m, rfl⟩ := hk
  rw [pow_succ, pow_mul, Nat.mul_mod, Nat.pow_mod]
  norm_num

/-- The ℕ ↔ `ZMod` bridge: `2^d ≡ 1` as a kernel-checkable statement about `%` is the
same as `2^d = 1` in the ring `ZMod (3^(j+1))`. -/
theorem two_pow_zmod_eq_one_iff (j d : ℕ) :
    (2 : ZMod (3 ^ (j + 1))) ^ d = 1 ↔ 2 ^ d % 3 ^ (j + 1) = 1 % 3 ^ (j + 1) := by
  have h := ZMod.natCast_eq_natCast_iff' (2 ^ d) 1 (3 ^ (j + 1))
  simpa using h

/-- **B1, the exact order.** `orderOf (2 : ZMod (3^(j+1))) = 2 · 3^j`: `2` generates a
subgroup of the maximal possible order at every level, i.e. the pair `(2, 3)` has no
Wieferich window ([DW16] Definition 5) at any level. Divisibility is the parent's crux;
exactness checks the two maximal proper divisors `3^j` (odd — fails mod `3` by
`two_pow_odd_mod_three`) and `2·3^(j-1)` (fails because the crux at `j-1` gives
`2^(2·3^(j-1)) = 1 + c·3^j` with `3 ∤ c`, so it is `≢ 1 (mod 3^(j+1))`). -/
theorem orderOf_two_zmod_three_pow (j : ℕ) :
    orderOf (2 : ZMod (3 ^ (j + 1))) = 2 * 3 ^ j := by
  refine orderOf_eq_of_pow_and_pow_div_prime (by positivity) ?_ ?_
  · rw [two_pow_zmod_eq_one_iff]
    exact two_pow_two_mul_three_pow_mod j
  · intro p hp hpd
    have hp23 : p = 2 ∨ p = 3 := by
      rcases (Nat.Prime.dvd_mul hp).mp hpd with h2 | h3
      · exact Or.inl ((Nat.prime_dvd_prime_iff_eq hp Nat.prime_two).mp h2)
      · exact Or.inr ((Nat.prime_dvd_prime_iff_eq hp Nat.prime_three).mp
          (hp.dvd_of_dvd_pow h3))
    rcases hp23 with rfl | rfl
    · -- `p = 2`: `2^(3^j) ≢ 1`, because `3^j` is odd, so `2^(3^j) ≡ 2 (mod 3)`
      rw [Nat.mul_div_cancel_left _ (by norm_num : (0:ℕ) < 2)]
      intro heq
      rw [two_pow_zmod_eq_one_iff] at heq
      have hdvd : (3 : ℕ) ∣ 3 ^ (j + 1) := dvd_pow_self 3 (Nat.succ_ne_zero j)
      have h1 : 2 ^ 3 ^ j % 3 = 1 % 3 ^ (j + 1) % 3 := by
        rw [← Nat.mod_mod_of_dvd _ hdvd, heq]
      have h2 : 2 ^ 3 ^ j % 3 = 2 := two_pow_odd_mod_three (Odd.pow ⟨1, by norm_num⟩)
      rw [Nat.mod_mod_of_dvd _ hdvd] at h1
      omega
    · -- `p = 3`: forces `j = i + 1`; the crux at `i` gives `2^(2·3^i) = 1 + c·3^(i+1)`,
      -- `3 ∤ c`, hence `≢ 1 (mod 3^(i+2))`
      rcases j with - | i
      · norm_num at hpd
      · have hdiv : 2 * 3 ^ (i + 1) / 3 = 2 * 3 ^ i := by
          rw [pow_succ, ← mul_assoc, Nat.mul_div_cancel _ (by norm_num : (0:ℕ) < 3)]
        rw [hdiv]
        intro heq
        rw [two_pow_zmod_eq_one_iff] at heq
        obtain ⟨c, hc, hc3⟩ := two_pow_two_mul_three_pow i
        rw [hc] at heq
        have hdvd2 : 3 ^ (i + 2) ∣ c * 3 ^ (i + 1) := by
          have hmodeq : (1 + c * 3 ^ (i + 1)) ≡ 1 [MOD 3 ^ (i + 2)] := heq
          have h := (Nat.modEq_iff_dvd' (Nat.le_add_right 1 _)).mp hmodeq.symm
          simpa using h
        have h3c : (3 : ℕ) ∣ c := by
          have h1 : 3 ^ (i + 1) * 3 ∣ 3 ^ (i + 1) * c := by
            rw [← pow_succ] at *
            calc 3 ^ (i + 2) ∣ c * 3 ^ (i + 1) := hdvd2
              _ = 3 ^ (i + 1) * c := by ring
          exact (Nat.mul_dvd_mul_iff_left (by positivity : (0:ℕ) < 3 ^ (i + 1))).mp h1
        exact hc3 h3c

/-- **B1, pure-ℕ form.** `2^d ≡ 1 (mod 3^(j+1))` **iff** `2·3^j ∣ d`: the set of
exponents fixing the residue `1` is exactly the multiples of the period — the least
period of the depth-`(j+1)` sieve is `2·3^j` on the nose, at every depth. -/
theorem two_pow_mod_eq_one_iff (j d : ℕ) :
    2 ^ d % 3 ^ (j + 1) = 1 % 3 ^ (j + 1) ↔ 2 * 3 ^ j ∣ d := by
  rw [← two_pow_zmod_eq_one_iff, ← orderOf_two_zmod_three_pow j,
    orderOf_dvd_iff_pow_eq_one]

/-! ## §2 B2: every admissible class is fully realized

`sieveAt_mod_period` (parent) says the depth-`(j+1)` sieve only sees `n mod 2·3^j`;
these two theorems record the barrier consequence: the truncated constraint is *exactly*
a union of admissible classes, and within an admissible class it excludes nothing. -/

/-- **B2, iff form.** Passing the depth-`(j+1)` sieve is *exactly* membership of the
class `n mod 2·3^j` in the admissible set: the truncated constraint carries no
information beyond the congruence class. -/
theorem sieveAt_iff_mod_mem_sieveClasses (j n : ℕ) :
    SieveAt (j + 1) n ↔ n % (2 * 3 ^ j) ∈ sieveClasses j := by
  constructor
  · exact mod_mem_sieveClasses_of_sieveAt
  · intro h
    obtain ⟨-, hs⟩ := mem_sieveClasses.mp h
    exact (sieveAt_mod_period j n).mpr hs

/-- **B2, realization.** Every `n` congruent to an admissible class passes the
depth-`(j+1)` sieve: each of the `2^j` admissible classes is realised *in full* — the
truncated constraint excludes not a single exponent inside an admissible class. -/
theorem sieveAt_of_mem_sieveClasses_of_modEq {j r : ℕ} (hr : r ∈ sieveClasses j)
    {n : ℕ} (hn : n ≡ r [MOD 2 * 3 ^ j]) : SieveAt (j + 1) n := by
  obtain ⟨hrlt, hrs⟩ := mem_sieveClasses.mp hr
  have hmod : n % (2 * 3 ^ j) = r := by
    have h' : n % (2 * 3 ^ j) = r % (2 * 3 ^ j) := hn
    rwa [Nat.mod_eq_of_lt hrlt] at h'
  rw [sieveAt_mod_period, hmod]
  exact hrs

/-! ## §3 B3: local immortality — infinitude and exact density at every depth -/

/-- `2^0 = 1 = (1)₃` passes every truncated sieve. -/
theorem sieveAt_zero (D : ℕ) : SieveAt D 0 := by
  intro i _
  rcases Nat.eq_zero_or_pos i with rfl | hi
  · norm_num
  · have h1 : 1 < 3 ^ i := Nat.one_lt_pow (by omega) (by norm_num)
    norm_num [Nat.div_eq_of_lt h1]

/-- The class of `0` is admissible at every depth. -/
theorem zero_mem_sieveClasses (j : ℕ) : 0 ∈ sieveClasses j :=
  mem_sieveClasses.mpr ⟨by positivity, sieveAt_zero _⟩

/-- **B3(a), local immortality.** At every depth `j` the truncated constraint has
infinitely many solutions: the whole class of `0` mod `2·3^j` survives. No finite-depth
truncation of the Erdős #406 constraint is finitely satisfiable — the full constraint
distinguishes itself from every one of its truncations only "at infinity". -/
theorem setOf_sieveAt_infinite (j : ℕ) : {n : ℕ | SieveAt (j + 1) n}.Infinite :=
  Set.infinite_of_injective_forall_mem (f := fun k : ℕ => k * (2 * 3 ^ j))
    (fun a b hab => Nat.eq_of_mul_eq_mul_right (by positivity) hab)
    (fun k => sieveAt_of_mem_sieveClasses_of_modEq (zero_mem_sieveClasses j)
      (Nat.modEq_zero_iff_dvd.mpr (dvd_mul_left _ _)))

/-- **B3(b), exact density.** Any `m` full periods contain *exactly* `m · 2^j` survivors
of the depth-`(j+1)` sieve: the parent's counting bound is attained with equality on
every full window. This is the sharpness statement behind the exponent `log₃ 2` — the
survivor density at depth `j+1` is exactly `2^j/(2·3^j) = (1/2)·(2/3)^j > 0`, so no
argument consuming only the low base-3 digits can prove finiteness, nor lower the
exponent. Proof: the map `n ↦ (n mod P, n div P)`, `P = 2·3^j`, is a bijection from the
survivors below `m·P` onto `sieveClasses j × range m`, by B2. -/
theorem card_range_mul_filter_sieveAt (j m : ℕ) :
    ((Finset.range (m * (2 * 3 ^ j))).filter fun n => SieveAt (j + 1) n).card
      = m * 2 ^ j := by
  have hP : 0 < 2 * 3 ^ j := by positivity
  have hcard : ((Finset.range (m * (2 * 3 ^ j))).filter fun n => SieveAt (j + 1) n).card
      = (sieveClasses j ×ˢ Finset.range m).card := by
    refine Finset.card_bij' (fun n _ => (n % (2 * 3 ^ j), n / (2 * 3 ^ j)))
      (fun p _ => p.1 + p.2 * (2 * 3 ^ j)) ?_ ?_ ?_ ?_
    · -- forward: a survivor's class is admissible, and its period index is `< m`
      intro n hn
      obtain ⟨hnr, hns⟩ := Finset.mem_filter.mp hn
      rw [Finset.mem_range] at hnr
      refine Finset.mem_product.mpr ⟨mod_mem_sieveClasses_of_sieveAt hns,
        Finset.mem_range.mpr ?_⟩
      rw [Nat.div_lt_iff_lt_mul hP]
      exact hnr
    · -- backward: an admissible class lifts into the window, and survives by B2
      intro p hp
      obtain ⟨hp1, hp2⟩ := Finset.mem_product.mp hp
      rw [Finset.mem_range] at hp2
      obtain ⟨hplt, -⟩ := mem_sieveClasses.mp hp1
      refine Finset.mem_filter.mpr ⟨Finset.mem_range.mpr ?_, ?_⟩
      · have hstep : p.1 + p.2 * (2 * 3 ^ j) < (1 + p.2) * (2 * 3 ^ j) := by
          rw [add_mul, one_mul]
          omega
        exact lt_of_lt_of_le hstep (Nat.mul_le_mul_right _ (by omega))
      · exact sieveAt_of_mem_sieveClasses_of_modEq hp1
          (show (p.1 + p.2 * (2 * 3 ^ j)) % (2 * 3 ^ j) = p.1 % (2 * 3 ^ j) from
            Nat.add_mul_mod_self_right p.1 p.2 (2 * 3 ^ j))
    · -- left inverse
      intro n hn
      exact Nat.mod_add_div' n (2 * 3 ^ j)
    · -- right inverse
      intro p hp
      obtain ⟨hp1, -⟩ := Finset.mem_product.mp hp
      obtain ⟨hplt, -⟩ := mem_sieveClasses.mp hp1
      have h1 : (p.1 + p.2 * (2 * 3 ^ j)) % (2 * 3 ^ j) = p.1 := by
        rw [Nat.add_mul_mod_self_right, Nat.mod_eq_of_lt hplt]
      have h2 : (p.1 + p.2 * (2 * 3 ^ j)) / (2 * 3 ^ j) = p.2 := by
        rw [Nat.add_mul_div_right _ _ hP, Nat.div_eq_of_lt hplt, Nat.zero_add]
      rw [h1, h2]
  rw [hcard, Finset.card_product, card_sieveClasses, Finset.card_range, mul_comm]

/-! ## §4 B4: fake solutions at every depth

By B1 the subgroup `⟨2⟩` of `(ZMod (3^(j+1)))ˣ` has order `2·3^j = φ(3^(j+1))`, i.e. it
is the whole unit group: *every* unit is a power of `2` to every finite depth. -/

/-- **B4, unit surjectivity.** Every `v` prime to `3` is `2^n mod 3^(j+1)` for some `n`
(`v % 3 = 2` included): `⟨2⟩` is the full unit group mod `3^(j+1)`, since its order
(B1) equals `φ(3^(j+1)) = 2·3^j`. -/
theorem exists_two_pow_mod_eq_of_not_dvd (j v : ℕ) (hv : ¬ 3 ∣ v) :
    ∃ n : ℕ, 2 ^ n % 3 ^ (j + 1) = v % 3 ^ (j + 1) := by
  haveI : NeZero (3 ^ (j + 1)) := NeZero.of_pos (by positivity)
  have hcop2 : Nat.Coprime 2 (3 ^ (j + 1)) :=
    Nat.Coprime.pow_right _ (by norm_num)
  have hcopv : Nat.Coprime v (3 ^ (j + 1)) :=
    (Nat.Coprime.pow_left _
      ((Nat.Prime.coprime_iff_not_dvd Nat.prime_three).mpr hv)).symm
  have hord : orderOf (ZMod.unitOfCoprime 2 hcop2) = 2 * 3 ^ j := by
    rw [← orderOf_units, ZMod.coe_unitOfCoprime]
    have h2 : ((2 : ℕ) : ZMod (3 ^ (j + 1))) = (2 : ZMod (3 ^ (j + 1))) := by
      push_cast
      rfl
    rw [h2, orderOf_two_zmod_three_pow]
  have hcard : Nat.card (ZMod (3 ^ (j + 1)))ˣ = 2 * 3 ^ j := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient,
      Nat.totient_prime_pow Nat.prime_three (Nat.succ_pos j), Nat.succ_sub_one]
    norm_num [mul_comm]
  have htop : Subgroup.zpowers (ZMod.unitOfCoprime 2 hcop2) = ⊤ := by
    apply Subgroup.eq_top_of_card_eq
    rw [Nat.card_zpowers, hord, hcard]
  have hmem : ZMod.unitOfCoprime v hcopv ∈
      Submonoid.powers (ZMod.unitOfCoprime 2 hcop2) := by
    rw [mem_powers_iff_mem_zpowers, htop]
    exact Subgroup.mem_top _
  obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff _ _).mp hmem
  refine ⟨n, ?_⟩
  have hcast : ((2 ^ n : ℕ) : ZMod (3 ^ (j + 1))) = ((v : ℕ) : ZMod (3 ^ (j + 1))) := by
    have hval := congrArg (Units.val) hn
    simpa [ZMod.coe_unitOfCoprime] using hval
  exact (ZMod.natCast_eq_natCast_iff' _ _ _).mp hcast

/-- **B4, reduced-representative form.** Every `v < 3^(j+1)` prime to `3` is hit exactly:
`2^n % 3^(j+1) = v` for some `n`. -/
theorem exists_two_pow_mod_eq (j v : ℕ) (hlt : v < 3 ^ (j + 1)) (hv : ¬ 3 ∣ v) :
    ∃ n : ℕ, 2 ^ n % 3 ^ (j + 1) = v := by
  obtain ⟨n, hn⟩ := exists_two_pow_mod_eq_of_not_dvd j v hv
  exact ⟨n, by rw [hn, Nat.mod_eq_of_lt hlt]⟩

/-- **B4, fake solutions.** Every `{0,1}`-digit string with units digit `1` — i.e. every
`v < 3^(j+1)` with `Base3ZeroOne v` and `v % 3 = 1` — is the low-digit block of an
actual power of `2`, and the realising exponent passes the depth-`(j+1)` sieve (its low
`j+1` digits *are* the digits of `v`). The digit hypothesis is not needed for the bare
existence (`exists_two_pow_mod_eq` above is strictly more general); it is the barrier
statement that matters: to every finite depth, "solutions" of the Erdős #406 digit
constraint exist in abundance — `3`-adically, the conjectured finiteness is invisible. -/
theorem exists_two_pow_mod_eq_of_base3ZeroOne (j v : ℕ) (hlt : v < 3 ^ (j + 1))
    (hv1 : v % 3 = 1) (hdig : Base3ZeroOne v) :
    ∃ n : ℕ, 2 ^ n % 3 ^ (j + 1) = v ∧ SieveAt (j + 1) n := by
  obtain ⟨n, hn⟩ := exists_two_pow_mod_eq j v hlt (by omega)
  refine ⟨n, hn, fun i hi => ?_⟩
  have hvmod : 2 ^ n % 3 ^ (j + 1) = v % 3 ^ (j + 1) := by
    rw [hn, Nat.mod_eq_of_lt hlt]
  rw [digit_eq_digit_of_mod_pow_eq (j + 1) hvmod hi]
  exact (base3ZeroOne_iff_forall_index v).mp hdig i

/-! ## §5 B5: the death pole — `(18, base 7, digits {2,4})` is decided by the same sieve

The identical method: truncate the digit constraint to depth `3`, reduce `18^n mod 7^3`
by periodicity, check the finitely many residues. For `(2, base 3)` the check leaves
`2^j` admissible classes at every depth (B2/B3); here it leaves **zero**, because `⟨18⟩`
mod `7^3` still has order `3` — a Wieferich window ([DW16] Definition 5, [LZ26]
"α-Wieferich at r") — so three levels of digit constraint press on a group of only three
elements, and all of `{1, 18, 324}` carry a digit outside `{2, 4}` among positions
`0..2`. -/

/-- Generic-base periodicity: `a^n % M` is periodic in `n` with period `d` whenever
`a^d ≡ 1 (mod M)`. Generalises the grandparent's `two_pow_mod_eq_of_pow_mod_one`
(whose proof is verbatim base-independent) from `a = 2` to arbitrary `a`. -/
theorem pow_mod_eq_of_pow_mod_one {a M d : ℕ} (hd : a ^ d % M = 1 % M) (n : ℕ) :
    a ^ n % M = a ^ (n % d) % M := by
  conv_lhs => rw [← Nat.div_add_mod n d, pow_add, pow_mul]
  rw [Nat.mul_mod, Nat.pow_mod, hd, ← Nat.pow_mod, one_pow, ← Nat.mul_mod, one_mul]

/-- Generic-base digit congruence: digits at positions `i < D` only depend on the value
mod `b^D`. Generalises the parent's base-3 `digit_eq_digit_of_mod_pow_eq` to arbitrary
base `b`. -/
theorem digit_eq_digit_of_mod_pow_eq_base {b m m' : ℕ} (D : ℕ)
    (h : m % b ^ D = m' % b ^ D) {i : ℕ} (hi : i < D) :
    m / b ^ i % b = m' / b ^ i % b := by
  have key : ∀ x : ℕ, x / b ^ i % b = x % b ^ (i + 1) / b ^ i := fun x => by
    rw [pow_succ, Nat.mod_mul_right_div_self]
  have hdvd : b ^ (i + 1) ∣ b ^ D := pow_dvd_pow b (by omega)
  rw [key, key, ← Nat.mod_mod_of_dvd m hdvd, h, Nat.mod_mod_of_dvd m' hdvd]

/-- **The genuine-position bridge.** If position `i` is genuine (`b^i ≤ m`), the
positional digit `m / b^i % b` really occurs in `Nat.digits b m`. (The unconditioned
version is false for predicates failing at `0` — out-of-range positions read the digit
`0` — which is exactly why `{2,4}`-digit constraints need this bounded form.) -/
theorem div_pow_mod_mem_digits {b m i : ℕ} (hb : 1 < b) (him : b ^ i ≤ m) :
    m / b ^ i % b ∈ Nat.digits b m := by
  have hlen : i < (Nat.digits b m).length := by
    by_contra hcon
    have hlt : m < b ^ i :=
      (Nat.digits_length_le_iff hb m).mp (Nat.le_of_not_lt hcon)
    omega
  rw [← Nat.getD_digits m i (by omega)]
  rw [List.getD_eq_getElem _ 0 hlen]
  exact List.getElem_mem hlen

/-- `Base7TwoFour m`: every base-`7` digit of `m` is `2` or `4`. The contrast instance:
same shape as the grandparent's `Base3ZeroOne`, base `7`, digit set `{2, 4}`. -/
def Base7TwoFour (m : ℕ) : Prop := ∀ d ∈ Nat.digits 7 m, d = 2 ∨ d = 4

instance (m : ℕ) : Decidable (Base7TwoFour m) := by
  unfold Base7TwoFour; infer_instance

/-- Ground truth for `Nat.digits 7` at the first four powers of `18` (little-endian):
`1 = (1)₇`, `18 = (24)₇`, `324 = (642)₇`, `5832 = (23001)₇`. In particular the brief's
claimed `[1, 0, 0, 3, 2, 2]` for `18^3 = 5832` is off — five digits, not six. -/
theorem digits_seven_eighteen_pow :
    Nat.digits 7 (18 ^ 0) = [1] ∧ Nat.digits 7 (18 ^ 1) = [4, 2] ∧
      Nat.digits 7 (18 ^ 2) = [2, 4, 6] ∧ Nat.digits 7 (18 ^ 3) = [1, 0, 0, 3, 2] := by
  decide

/-- **The Wieferich-window witnesses, kernel-checked.** `18^3 ≡ 1` mod `7`, mod `49`,
and mod `343` — so `⟨18⟩` has order `3` at all three levels (it is nontrivial mod `7`
since `18 ≡ 4`), i.e. the group does not grow from level 1 to level 3 — and the window
closes at level 4: `18^3 % 2401 = 1030 ≠ 1`. -/
theorem eighteen_wieferich_window :
    18 ^ 3 % 7 = 1 ∧ 18 ^ 3 % 49 = 1 ∧ 18 ^ 3 % 343 = 1 ∧ 18 ^ 3 % 2401 = 1030 := by
  decide

/-- **B5, the sieve kills everything above the window.** For `n` with `3 ≤ n`, some
base-`7` digit of `18^n` lies outside `{2, 4}`: by periodicity `18^n ≡ 18^(n mod 3)
(mod 7^3)`, and each residue has a bad genuine digit — `1` has digit `1` at position
`0`; `18` has digit `0` at position `2`; `324` has digit `6` at position `2`. -/
theorem not_base7TwoFour_eighteen_pow_of_three_le {n : ℕ} (hn : 3 ≤ n) :
    ¬ Base7TwoFour (18 ^ n) := by
  intro h
  have hper : 18 ^ n % 7 ^ 3 = 18 ^ (n % 3) % 7 ^ 3 :=
    pow_mod_eq_of_pow_mod_one (by decide) n
  have h49 : 7 ^ 2 ≤ 18 ^ n :=
    le_trans (by norm_num) (Nat.pow_le_pow_right (by norm_num) hn)
  rcases (by omega : n % 3 = 0 ∨ n % 3 = 1 ∨ n % 3 = 2) with h0 | h1 | h2
  · -- residue `1`: the units digit of `18^n` is `1`
    have hm : 18 ^ n % 7 ^ 3 = 1 % 7 ^ 3 := by rw [hper, h0, pow_zero]
    have hd : 18 ^ n / 7 ^ 0 % 7 = 1 / 7 ^ 0 % 7 :=
      digit_eq_digit_of_mod_pow_eq_base 3 hm (by norm_num)
    have hmem : 18 ^ n / 7 ^ 0 % 7 ∈ Nat.digits 7 (18 ^ n) :=
      div_pow_mod_mem_digits (by norm_num)
        (le_trans (by norm_num) (Nat.one_le_pow _ _ (by norm_num)))
    have hval : (1 : ℕ) / 7 ^ 0 % 7 = 1 := by norm_num
    rw [hd, hval] at hmem
    rcases h 1 hmem with h' | h' <;> omega
  · -- residue `18 = (024)₇`: the digit of `18^n` at position `2` is `0`
    have hm : 18 ^ n % 7 ^ 3 = 18 % 7 ^ 3 := by rw [hper, h1, pow_one]
    have hd : 18 ^ n / 7 ^ 2 % 7 = 18 / 7 ^ 2 % 7 :=
      digit_eq_digit_of_mod_pow_eq_base 3 hm (by norm_num)
    have hmem : 18 ^ n / 7 ^ 2 % 7 ∈ Nat.digits 7 (18 ^ n) :=
      div_pow_mod_mem_digits (by norm_num) h49
    have hval : (18 : ℕ) / 7 ^ 2 % 7 = 0 := by norm_num
    rw [hd, hval] at hmem
    rcases h 0 hmem with h' | h' <;> omega
  · -- residue `324 = (642)₇`: the digit of `18^n` at position `2` is `6`
    have hm : 18 ^ n % 7 ^ 3 = 324 % 7 ^ 3 := by
      rw [hper, h2]
      norm_num
    have hd : 18 ^ n / 7 ^ 2 % 7 = 324 / 7 ^ 2 % 7 :=
      digit_eq_digit_of_mod_pow_eq_base 3 hm (by norm_num)
    have hmem : 18 ^ n / 7 ^ 2 % 7 ∈ Nat.digits 7 (18 ^ n) :=
      div_pow_mod_mem_digits (by norm_num) h49
    have hval : (324 : ℕ) / 7 ^ 2 % 7 = 6 := by norm_num
    rw [hd, hval] at hmem
    rcases h 6 hmem with h' | h' <;> omega

/-- **B5, the death pole.** `18^n` has all base-`7` digits in `{2, 4}` **iff** `n = 1`:
the digit-set problem for the windowed pair `(18, 7)` is *completely decided* by the
same truncate–periodicity–check sieve that, for the windowless pair `(2, 3)` of Erdős
#406, provably decides nothing (B2–B4). Cases `n = 0, 1, 2` are the kernel facts
`digits_seven_eighteen_pow`; `3 ≤ n` is the sieve
(`not_base7TwoFour_eighteen_pow_of_three_le`). -/
theorem base7TwoFour_eighteen_pow_iff (n : ℕ) : Base7TwoFour (18 ^ n) ↔ n = 1 := by
  constructor
  · intro h
    rcases n with - | - | - | k
    · exact absurd h (by decide)
    · rfl
    · exact absurd h (by decide)
    · exact absurd h (not_base7TwoFour_eighteen_pow_of_three_le (by omega))
  · rintro rfl
    decide

/-! ## §6 Joint satisfiability of every hypothesis, and concrete instantiations

Mirroring the parents' instantiation sections: every hypothesis-bearing declaration
above is instantiated at a concrete model, with independent kernel cross-checks. -/

/-- `two_pow_odd_mod_three` at `k = 3`, with kernel cross-check `8 % 3 = 2`. -/
example : 2 ^ 3 % 3 = 2 := two_pow_odd_mod_three ⟨1, by norm_num⟩

example : 2 ^ 3 % 3 = 2 := by decide

/-- B1 at `j = 1`, `d = 12` (both sides true: `2^12 = 4096 ≡ 1 (mod 9)`, `6 ∣ 12`) —
with independent kernel checks of `2^12 % 9 = 1` and of the *failure* at `d = 4`
(`2^4 = 16 ≡ 7 (mod 9)`, `6 ∤ 4`), consistent with the iff. -/
example : 2 ^ 12 % 3 ^ (1 + 1) = 1 % 3 ^ (1 + 1) ↔ 2 * 3 ^ 1 ∣ 12 :=
  two_pow_mod_eq_one_iff 1 12

example : 2 ^ 12 % 9 = 1 ∧ 2 ^ 4 % 9 = 7 := by decide

/-- B2 at `j = 1`, `r = 2`, `n = 8`: `2 ∈ sieveClasses 1` and `8 ≡ 2 (mod 6)` give
`SieveAt 2 8` — consistent with `8 ∈ erdos406Set` via the parent's chain. -/
example : SieveAt (1 + 1) 8 :=
  sieveAt_of_mem_sieveClasses_of_modEq (j := 1) (r := 2) (by decide) (by decide)

example : SieveAt 2 8 := sieveAt_of_base3ZeroOne witness_two_pow_eight 2

/-- B3(a) at `j = 1`: infinitude of the depth-2 survivors. -/
example : {n : ℕ | SieveAt (1 + 1) n}.Infinite := setOf_sieveAt_infinite 1

/-- B3(b) at `j = 1`, `m = 3`: the window `range 18` contains exactly `3 · 2 = 6`
depth-2 survivors. -/
example : ((Finset.range (3 * (2 * 3 ^ 1))).filter fun n => SieveAt (1 + 1) n).card
    = 3 * 2 ^ 1 := card_range_mul_filter_sieveAt 1 3

/-- Kernel cross-check of the same count, and the pruning between depths: the depth-2
survivors below `18` are `{0, 2, 6, 8, 12, 14}` (six of them — exactly `3·2^1`), of
which only `{0, 2, 6, 8}` also survive depth 3 (four — exactly `2^2`, one full period
of the depth-3 sieve since `18 = 2·3^2`). Each deepening kills a third of the classes;
none of the survivors is ever killed by *congruence* information again — only by deeper
digits. -/
example : ((Finset.range 18).filter fun n => SieveAt 2 n) = {0, 2, 6, 8, 12, 14} := by
  decide

example : ((Finset.range 18).filter fun n => SieveAt 3 n) = {0, 2, 6, 8} := by decide

/-- B4, general form, at `j = 1`, `v = 5` (a `v ≡ 2 (mod 3)` instance): some `2^n ≡ 5
(mod 9)` — kernel witness `2^5 = 32 = 27 + 5`. -/
example : ∃ n : ℕ, 2 ^ n % 3 ^ (1 + 1) = 5 % 3 ^ (1 + 1) :=
  exists_two_pow_mod_eq_of_not_dvd 1 5 (by norm_num)

example : 2 ^ 5 % 3 ^ 2 = 5 := by decide

/-- B4, fake solutions, at `j = 2`, `v = 10`: all three hypotheses hold jointly
(`10 < 27`, `10 % 3 = 1`, `10 = (101)₃` has digits `≤ 1`), so some power of `2` is
`≡ 10 (mod 27)` and its exponent passes the depth-3 sieve. Kernel witness: `2^6 = 64 =
2·27 + 10`, and indeed `SieveAt 3 6` (the low three digits of `64 = (2101)₃` are
`1, 0, 1`). -/
example : ∃ n : ℕ, 2 ^ n % 3 ^ (2 + 1) = 10 ∧ SieveAt (2 + 1) n :=
  exists_two_pow_mod_eq_of_base3ZeroOne 2 10 (by norm_num) (by norm_num) (by decide)

example : 2 ^ 6 % 3 ^ 3 = 10 ∧ SieveAt 3 6 ∧ Nat.digits 3 10 = [1, 0, 1] := by decide

/-- `pow_mod_eq_of_pow_mod_one` at `a = 18`, `M = 343`, `d = 3`, `n = 5` (the hypothesis
`18^3 % 343 = 1 % 343` is satisfied — `eighteen_wieferich_window`), with kernel
cross-check `18^5 % 343 = 324 = 18^2 % 343`. -/
example : 18 ^ 5 % 7 ^ 3 = 18 ^ (5 % 3) % 7 ^ 3 :=
  pow_mod_eq_of_pow_mod_one (by decide) 5

example : 18 ^ 5 % 343 = 324 := by decide

/-- `digit_eq_digit_of_mod_pow_eq_base` at `b = 7`, `D = 3`, `m = 5832`, `m' = 1`,
`i = 0` (`5832 ≡ 1 (mod 343)`): both units digits are `1` — kernel cross-check. -/
example : 5832 / 7 ^ 0 % 7 = 1 / 7 ^ 0 % 7 :=
  digit_eq_digit_of_mod_pow_eq_base 3 (by norm_num) (by norm_num)

example : 5832 % 7 = 1 := by decide

/-- `div_pow_mod_mem_digits` at `b = 7`, `m = 5832`, `i = 3` (both hypotheses jointly:
`1 < 7`, `343 ≤ 5832`): the position-3 digit `5832 / 343 % 7 = 3` occurs in
`digits 7 5832 = [1, 0, 0, 3, 2]` — kernel cross-check. -/
example : 5832 / 7 ^ 3 % 7 ∈ Nat.digits 7 5832 :=
  div_pow_mod_mem_digits (by norm_num) (by norm_num)

example : 5832 / 7 ^ 3 % 7 = 3 := by decide

/-- `Base7TwoFour` ground truth at the three small powers: `18 = (24)₇` passes, `1` and
`324 = (642)₇` fail. -/
example : Base7TwoFour 18 ∧ ¬ Base7TwoFour 1 ∧ ¬ Base7TwoFour 324 := by decide

/-- `not_base7TwoFour_eighteen_pow_of_three_le` at `n = 3` (hypothesis `3 ≤ 3`), with
independent kernel check on the digit list of `5832`. -/
example : ¬ Base7TwoFour (18 ^ 3) :=
  not_base7TwoFour_eighteen_pow_of_three_le le_rfl

example : ¬ Base7TwoFour (18 ^ 3) := by decide

/-- The death pole, both directions: `n = 1` passes, `n = 5` (unreachable by `decide`
on digit lists without cost — the point of the theorem) fails. -/
example : Base7TwoFour (18 ^ 1) := (base7TwoFour_eighteen_pow_iff 1).mpr rfl

example : ¬ Base7TwoFour (18 ^ 5) :=
  fun h => absurd ((base7TwoFour_eighteen_pow_iff 5).mp h) (by omega)

end Erdos406

#print axioms Erdos406.two_pow_odd_mod_three
#print axioms Erdos406.two_pow_zmod_eq_one_iff
#print axioms Erdos406.orderOf_two_zmod_three_pow
#print axioms Erdos406.two_pow_mod_eq_one_iff
#print axioms Erdos406.sieveAt_iff_mod_mem_sieveClasses
#print axioms Erdos406.sieveAt_of_mem_sieveClasses_of_modEq
#print axioms Erdos406.sieveAt_zero
#print axioms Erdos406.zero_mem_sieveClasses
#print axioms Erdos406.setOf_sieveAt_infinite
#print axioms Erdos406.card_range_mul_filter_sieveAt
#print axioms Erdos406.exists_two_pow_mod_eq_of_not_dvd
#print axioms Erdos406.exists_two_pow_mod_eq
#print axioms Erdos406.exists_two_pow_mod_eq_of_base3ZeroOne
#print axioms Erdos406.pow_mod_eq_of_pow_mod_one
#print axioms Erdos406.digit_eq_digit_of_mod_pow_eq_base
#print axioms Erdos406.div_pow_mod_mem_digits
#print axioms Erdos406.digits_seven_eighteen_pow
#print axioms Erdos406.eighteen_wieferich_window
#print axioms Erdos406.not_base7TwoFour_eighteen_pow_of_three_le
#print axioms Erdos406.base7TwoFour_eighteen_pow_iff
